\pagebreak

# LEÇONS APPRISES DES APPLICATIONS DANS LE CADRE DES ÉTUDES DE CAS

Les trois UGS qui ont servi comme études de cas ont été sélectionnées pour représenter un éventail de niveaux de disponibilité des données, allant d’abondantes à limitées. Pour chaque étude de cas, l’ensemble des méthodes d’estimation des PRL considérées (tableau \@ref(tab:lrpapproaches)) dépendait des données disponibles et des méthodes d’évaluation déjà mises au point pour l’UGS. Chaque étude de cas comprend sa propre section de discussion mettant en évidence les conclusions qui lui sont propres. Dans la présente section, nous présentons un résumé des principales leçons apprises lors de l’examen des trois études de cas. Ces leçons ont servi à éclairer l’élaboration de lignes directrices visant la définition des PRL pour les UGS de saumons du Pacifique, comme décrit dans @holtGuidelinesDefiningLimitInpress.

&nbsp;

**Leçon 1 : les PRL fondés sur l’état des UC d’après l’algorithme multidimensionnel de l’Explorateur pouvaient être facilement estimés pour toutes les UGS sur un large éventail de disponibilités de données, et ils étaient conformes à l’approche multidimensionnelle qui a été élaborée pour les évaluations selon la PSS. Ce n’était pas le cas pour les PRL fondés sur l’abondance agrégée.**

Les PRL fondés sur l’état des UC d’après l’Explorateur ont pu être appliqués aux trois études de cas, tandis que les méthodes fondées sur l’abondance agrégée exigeaient une forte relation positive entre l’abondance agrégée observée et les logarithmes du rapport des cotes que toutes les UC se trouvent au-dessus de leur PRI (PRL de régression logistique) ou qu’il y ait assez de données sur les UC pour paramétrer un modèle de dynamique de la population (PRL de projection). Bien que l’étude de cas sur le saumon coho du Fraser intérieur satisfaisait à ces deux exigences, celle qui portait sur le saumon chinook de la COIV ne pouvait répondre qu’à la deuxième, et celle sur le saumon kéta de la CSI ne pouvait satisfaire à aucune de ces exigences. L’utilisation de l’Explorateur pour estimer les états multidimensionnels des PRL fondés sur l’état des UC a été particulièrement utile pour les UGS à données limitées, car elle a permis d’appliquer une combinaison de la qualité des données et des types de points de référence, selon ce qui était disponible pour une UC donnée au cours d’une année donnée. Par exemple, dans l’étude de cas sur le saumon kéta de la CSI, l’application de l’Explorateur pour élaborer des PRL fondés sur l’état des UC a permis d’inclure les sept UC au moment d’évaluer l’état à l’échelle de l’UGS en utilisant d’autres paramètres fondés sur les tendances pour les UC sans points de référence fondés sur le centile. La capacité d’évaluer les UC sans PRI fondé sur l’abondance est particulièrement importante lorsqu’une UGS est composée d’UC ayant de faibles niveaux de synchronie dans lesquels les UC présentant des lacunes en matière de données ne peuvent être représentées par substitution, comme ce fut le cas pour le saumon kéta de la CSI. 

&nbsp;

**Leçon 2 : l’élaboration de paramètres et de points de référence sur la répartition des géniteurs d’une UC est une priorité élevée pour faciliter les évaluations de l’état selon la PSS qui, à leur tour, appuieront l’élaboration de PRL fondés sur l’état des UC à l’échelle de l’UGS.**

Les études de cas sur le saumon coho du Fraser intérieur et sur le saumon chinook de la COIV ont appliqué des méthodes d’estimation du PRL qui tenaient compte de la répartition de l’abondance des géniteurs entre les petites sous-unités au sein des UC; cependant, différentes approches ont été utilisées dans chaque cas. Pour le saumon coho du Fraser intérieur, nous nous sommes appuyés sur des cibles de répartition établies antérieurement qui reconnaissaient l’importance biologique du maintien de l’abondance des géniteurs dans onze sous-populations recensées nichant dans les cinq UC. Dans le cas du saumon chinook de la COIV, l’avis d’experts pris en compte dans l’élaboration de l’étude de cas a déterminé que les inlets constituaient une importante échelle spatiale de diversité pour l’UGS (D. McHugh, comm. pers., Évaluation des stocks de la côte sud du MPO). Par conséquent, les PRL ont été établis de manière préserver la diversité à l’échelle des inlets plutôt qu’à l’échelle de l’UC pour cette étude de cas.  

Des recherches futures sont nécessaires pour élaborer et évaluer des paramètres de répartition et des points de référence connexes qui délimitent les zones d’état selon la PSS. L’établissement de points de référence distributionnels permettrait d’intégrer directement la répartition de l’abondance des géniteurs au sein d’une UC dans les évaluations multidimensionnelles de l’état selon la PSS, ce qui permettrait à son tour d’adopter une approche normalisée pour considérer la répartition des géniteurs à une échelle plus petite lors de la détermination des PRL à l’échelle de l’UGS.

&nbsp;

**Leçon 3 : dans certains cas, les estimations annuelles de l’état des PRL fondés sur l’abondance agrégée et des PRL fondés sur l’état des UC seront différentes les unes des autres.**

Bien que les estimations annuelles de l’état obtenues des méthodes fondées sur l’abondance agrégée étaient généralement cohérentes avec les estimations des méthodes fondées sur l’état des UC à l’aide de l’Explorateur recommandé, elles ne concordaient pas toujours. Pour l’étude de cas sur le saumon coho du Fraser intérieur, l’état a eu tendance à chuter sous le PRL fondé sur l’état des UC lorsque l’abondance des UC individuelles était faible, et à descendre sous le PRL fondé sur l’abondance agrégée lorsque l’abondance agrégée était faible. Bien que ces conditions aient correspondu la plupart des années, cela n’a pas toujours été le cas. Dans le cadre de notre étude de cas sur le saumon coho du Fraser intérieur, nous avons constaté que la proportion d’années pour lesquelles les estimations de l’état correspondaient aux PRL fondés sur l’état des UC et sur l’abondance agrégée variait de 72 à 86 %, selon la méthode utilisée pour estimer l’état des UC.

&nbsp;

**Leçon 4 : dans la mesure du possible, il faut utiliser les données de toutes les UC constituantes. Lorsqu’il manque des données sur une ou plusieurs UC, il faut examiner attentivement s’il est possible de déduire l’état à partir d’autres UC de l’UGS. Bien qu’il puisse y avoir des cas où cette déduction est possible, l’incertitude entourant les évaluations de l’état ainsi obtenues sera plus grande et il faudra clairement indiquer cette incertitude dans les évaluations de l’état.**

Dans le cas du saumon kéta de la CSI, l’utilisation des données des sept UC lorsqu’elles étaient disponibles (même s’il ne s’agissait que d’un sous-ensemble d’années) a entraîné une chute de l’état sous le PRL plus fréquemment que lorsqu’un sous-ensemble d’UC seulement était utilisé pour toutes les années. Ce résultat s’explique par le fait que, dans le cas des PRL fondés sur l’état des UC, il y a une asymétrie dans la façon dont les UC manquantes peuvent avoir une incidence sur l’état à l’échelle de l’UGS par rapport au PRL. L’ajout d’UC peut faire passer l’état des UC d’au-dessus à au-dessous du PRL si l’état d’une UC supplémentaire est en zone rouge et que l’état de toutes les autres UC est en zone ambre ou verte. Toutefois, l’ajout d’une UC ne fera jamais passer l’état d’au-dessous à au-dessus du PRL, car si l’état d’une UC est déjà en zone rouge, le seuil de 100 % de toutes les UC dont l’état se trouve au-dessus de la zone rouge ne peut pas être atteint dans ce cas. Étant donné que les UC de saumon kéta de la CSI présentent de faibles corrélations entre l’abondance des géniteurs au fil du temps et qu’elles présentent différents facteurs environnementaux dans leurs habitats d’eau douce, il n’est pas recommandé de déduire l’état des UC manquantes à partir d’autres UC comportant des données. Par conséquent, les estimations de l’état qui comprennent seulement une partie des UC sont potentiellement biaisées.  

Dans le cas du saumon coho du Fraser intérieur, les résultats des scénarios de données manquantes pour l’approche de régression logistique ont montré qu’il pourrait être possible d’utiliser des UC à données abondantes comme indicateurs pour les UC pour lesquelles il manque des données.  Cependant, les PRL fondés sur la régression logistique étaient plus incertains lorsque plus d’une UC manquait, et le modèle de régression logistique ne convergeait souvent pas; il faut donc faire preuve de prudence lorsqu’on applique cette méthode aux UGS pour lesquelles il manque de données. De plus, le saumon coho du Fraser intérieur affiche des niveaux plus élevés de corrélation entre les UC dans l’abondance des géniteurs au fil du temps que le saumon kéta de la CSI, de sorte que la mesure dans laquelle ce résultat peut être appliqué à d’autres UGS devrait dépendre du niveau de covariance de l’état entre les UC au sein d’une UGS.

&nbsp;

**Leçon 5 : les PRL de régression logistique comportent plusieurs limites et ne doivent être utilisés que lorsque (i) des PRL fondés sur l’abondance agrégée sont nécessaires et (ii) toutes les hypothèses du modèle de régression logistique peuvent être respectées.**

Les PRL de régression logistique sont calculés empiriquement à partir des observations antérieures de l’abondance à l’échelle de l’UGS et des états des UC. En ajustant une régression logistique aux données historiques, nous avons déterminé les niveaux d’abondance historiques associés aux probabilités que toutes les UC constituantes aient des états se trouvant au-dessus de leur PRI. À l’instar du PRL fondé sur l’état des UC, cette méthode fondée sur l’abondance agrégée dépend des résultats des évaluations d’UC individuelles, qui sont sensibles aux hypothèses structurelles sous-jacentes aux points de référence à l’échelle de l’UC et à la disponibilité des données.


Les PRL de régression logistique n’ont pu être estimés que pour l’une des UGS étudiées, ce qui donne à penser qu’ils pourraient ne constituer une option que pour une petite proportion d’UGS. Même pour le saumon coho du Fraser intérieur, où un ajustement de régression logistique était possible, les estimations ne convergeaient pas pour toutes les années rétrospectives, et les estimations de l’état étaient sensibles aux données manquantes. Dans l’ensemble, notre examen des PRL de régression logistique pour nos trois études de cas a mis en évidence certaines limites de cette approche.


Premièrement, les PRL de régression logistique se limitent aux conditions qui ont été observées par le passé. Cela peut poser un problème lorsqu’il y a un faible contraste dans les données historiques, comme ce fut le cas pour le saumon chinook de la COIV. Dans ce cas, il n’y a pas eu d’année où toutes les populations d’inlet constituantes ont dépassé leur PRI. Toutefois, des difficultés semblables pourraient survenir dans les cas où aucune UC ne chute au-dessous de son PRI. La dépendance aux conditions observées par le passé constitue une autre limite lorsqu’il y a eu des changements dans la corrélation de la dynamique de la population entre les UC au fil du temps, de sorte que les corrélations actuelles (ou futures) ne sont pas représentées par des données historiques.


Deuxièmement, les diagnostics du modèle ne prennent pas en charge les régressions logistiques et leurs PRL associés lorsque les abondances à l’échelle de l'UC ne sont pas corrélées ou qu’elles le sont seulement faiblement. Ici, nous avons constaté que les PRL de régression logistique pouvaient être estimés pour le saumon coho du Fraser intérieur (corrélation moyenne de 0,56 pour l’abondance des géniteurs entre les UC), mais pas pour le saumon kéta de la CSI (corrélation moyenne de 0,12 entre les UC). De plus, la vaste gamme de productivités et de capacités entre les UC pour l’étude de cas sur le saumon kéta de la CSI a contribué à la faible relation entre l’abondance agrégée et les états à l’échelle de l’UC. En général, les diagnostics de modèle décrits à la section \@ref(MethodsChapter) peuvent être utilisés pour soutenir ou rejeter les PRL de régression logistique. Nous illustrons comment ces diagnostics sont utilisés pour évaluer l’adéquation du modèle aux sections \@ref(IFCChapter) et \@ref(ISCchumChapter).    

Enfin, des analyses préliminaires des PRL de régression logistique pour le saumon rouge du Fraser (non présentées dans le présent document) ont montré que la méthode n’était pas facilement appliquée aux stocks cycliques.  

&nbsp;

**Leçon 6 : on peut recourir à des projections stochastiques pour estimer les PRL fondés sur l’abondance agrégée selon diverses hypothèses sur la dynamique de la population et la covariance de la dynamique entre les UC. Cette approche permet de représenter de façon plus exhaustive les incertitudes dans notre compréhension de la dynamique des populations que les autres méthodes de PRL.**

Les PRL de projection s’appuient sur des modèles de simulation en boucle fermée pour quantifier la relation émergente entre les abondances agrégées à l’échelle de l’UGS et les probabilités que toutes les UC dépassent leur PRI, compte tenu d’un niveau d’exploitation prédéfini. Les exigences les plus importantes pour cette approche sont les estimations propres à l’UC des paramètres de stock-recrutement (productivité et capacité) et la covariance dans le recrutement entre les UC. Les estimations des paramètres pour la productivité et la capacité peuvent être fondées sur les distributions a posteriori à partir des analyses du stock-recrutement (voir l’étude de cas sur le saumon coho du Fraser intérieur, à la section \@ref(IFCChapter)) ou plus qualitativement à partir des commentaires d’experts, des modèles de l’étape du cycle de vie ou des estimations des modèles de la zone du bassin hydrographique (voir l’étude de cas sur le saumon chinook de la COIV, à la section \@ref(WCVIchinookChapter)). 


De plus, nous avons démontré une approche servant à choisir les paramètres et les hypothèses de modèle utilisés dans les projections de sorte que les corrélations dans l’abondance des géniteurs dans les projections étaient semblables aux corrélations observées. Nous recommandons que les corrélations entre les UC dans les projections soient explorées dans le cadre de diverses hypothèses de modèle, et que les paramètres du modèle soient ajustés pour calculer des corrélations réalistes.


L’approche des PRL de projection est souple, car elle permet de tenir compte de l’incertitude structurelle dans la dynamique des populations de l’UGS en tenant compte de scénarios de rechange. Par exemple, pour l’étude de cas sur le saumon chinook de la COIV, des analyses de sensibilité ont été effectuées pour évaluer les répercussions des corrélations dans les résidus du recrutement et la variabilité de l’exploitation entre les populations d’inlet. Dans le cas de l’étude sur le saumon coho du Fraser intérieur, l’incertitude structurelle dans la formulation du modèle de stock-recrutement a été prise en compte dans d’autres scénarios de projection. Dans ce cas, nous avons démontré comment une approche de calcul de la moyenne des modèles pourrait être utilisée pour combiner les projections de ces deux scénarios en un seul PRL.  


Les futures mises en œuvre des PRL de projection pourraient également tenir compte des changements temporels dans les paramètres de stock-recrutement, de la possibilité d’une dynamique anticompensatoire pour une population de petite taille et de la variabilité future des taux d’exploitation des pêches. Les décisions sur les scénarios à prendre en considération doivent être prises au cas par cas et dépendre de la compréhension actuelle des principales incertitudes pour chaque UGS.

&nbsp;

**Leçon 7 : les PRL de projection sont très sensibles aux taux d’exploitation.**

Les analyses de sensibilité ont montré que les PRL de projection sont sensibles aux niveaux d’exploitation supposés dans les projections. Des taux d’exploitation plus élevés ont donné lieu à une abondance agrégée requise plus élevée à l’échelle de l’UGS pour veiller à ce que toutes les UC demeurent au-dessus de leur PRI. La sensibilité au taux d’exploitation augmente à mesure que la variabilité des paramètres de stock-recrutement entre les UC augmente et que l’incertitude dans les estimations des paramètres augmente. Cette propriété des PRL de projection est explorée à l’annexe \@ref(app:ERsensitivity-appendix). Par conséquent, les PRL de projection établis en fonction des taux d’exploitation historiques et actuels ne peuvent pas nécessairement servir de base à l’évaluation de procédures de gestion de rechange. Toutefois, le fait de démontrer que les changements dans l’abondance agrégée requise pour que toutes les UC dépassent les PRI (c’est-à-dire les changements dans le PRL projeté) selon différents scénarios d’exploitation peut aider les analystes et les gestionnaires à comprendre les répercussions de l’évolution des taux d’exploitation sur la capacité d’atteindre les objectifs de la PSS.
