---
title: "Application de méthodes d’estimation des points de référence limites à des unités de gestion des stocks de saumons du Pacifique dans le cadre d’études de cas"
author: |
  Kendra Holt^1^
  Carrie A. Holt^2^
  Luke Warkentin^3^
  Catarina Wor^2^
  Brooke Davis^3^
  Michael Arbeider^4^
  Jessy Bokvist^5^
  Sabrina Crowley^6^
  Sue Grant^7^
  Wilf Luedke^5^
  Diana McHugh^5^
  Candace Picco^8^
  Pieter Van Will^5^

author_list: "Holt, K.R., Holt, C.A., Warkentin, L., Wor, C., Davis, B., Arbeider, M., Bokvist, J., Crowley, S., Grant, S., Luedke, W., McHugh, D., Picco, C., et Van Will, P."
address: |
 ^1^Pêches et Océans Canada, Institut des sciences de la mer\
     9860, chemin West Saanich\
     Sidney (C.-B.)  V8L 5T5\
     \
  ^2^Pêches et Océans Canada, Station biologique du Pacifique\
     3190, chemin Hammond Bay\
     Nanaimo (C.-B.)  V9T 6N7
     \
  ^3^Pêches et Océans Canada, bureau d’Annacis\
     100, promenade Annacis, unité 3\
     Delta (C.-B.)  V3M 6A2\
     \
  ^4^Pêches et Océans Canada, bureau du secteur de l’intérieur de la Colombie-Britannique\
     986, place McGill\
     Kamloops (C.-B.)  V2C 6X6\
     \
  ^5^Pêches et Océans Canada, bureau du secteur de la côte sud\
     3225, chemin Stephenson Point\
     Nanaimo (C.-B.)  V9T 1K3\
     \
  ^6^Conseil tribal de Nuu-chah-nulth\\
     5001, chemin Mission\
     Port Alberni (C.-B.)  V9Y 8X9\
     \
  ^7^Pêches et Océans Canada, administration régionale du Pacifique\
     401, rue Burrard, bureau 200\
     Vancouver (C.-B.)  V6C 3S4\
     \
  ^8^Ha'oom Fisheries Society\
     320, chemin Opitsaht IR\
     Tofino (C.-B.)  V0R 2Z0\

month: Month # fill in
year: 2022
report_number: nnn
region: Région du Pacifique
citation_other_language: "Holt, K.R., Holt, C.A., Warkentin, L., Wor, C., Davis, B., Arbeider, M., Bokvist, J., Crowley, S., Grant, S., Luedke, W., McHugh, D., Picco, C., and Van Will, P. Case Study Applications of LRP Estimation Methods to Pacific Salmon Stock Management Units. DFO Secr. Can._.... 2022/nnn. iv + xxx p."
abstract: |
  La *Loi sur les pêches* révisée exige que des points de référence limite (PRL) soient déterminés pour tous les grands stocks de poissons. Pour les saumons du Pacifique, les grands stocks de poissons sont représentés par des unités de gestion des stocks (UGS). Une UGS est composée d’une ou de plusieurs unités de conservation (UC) du saumon, qui sont les unités utilisées lors des évaluations en vertu de la Politique concernant le saumon sauvage (PSS). Nous présentons des méthodes d’estimation des PRL au à l’échelle de l’UGS qui intègrent les états des UC selon la PSS. Dans le cadre d’études de cas, nous démontrons et évaluons les PRL pour trois UGS : saumon coho du Fraser intérieur (*Oncorhynchus kisutch*), saumon chinook de la côte ouest de l’île de Vancouver (*O. tshawytscha*) et saumon kéta de la côte sud intérieure (*O. Keta*), à l’exclusion des UC du fleuve Fraser. Les méthodes sont divisées en deux catégories : PRL fondés sur l’état des UC et PRL fondés sur l’abondance agrégée. Les PRL fondés sur l’état des UC sont recommandés comme méthode par défaut et sont fondés sur la proportion d’UC se situant au-dessus des niveaux associés à un risque accru d’extinction (au-dessus de la zone rouge) selon la PSS. Les méthodes fondées sur l’abondance agrégée peuvent être utilisées en complément pour répondre à des exigences particulières de gestion des pêches. Les PRL fondés sur l’abondance agrégée sont subdivisés en PRL de régression logistique et en PRL de projection. Les deux types de PRL fondés sur l’abondance agrégée sont définis comme l’abondance à l’échelle de l’UGS associée à une probabilité souhaitée que l’état de toutes les UC constituantes se trouve au-dessus de la zone rouge, mais ils diffèrent en ce sens que les PRL de régression logistique sont déterminés directement à partir des données historiques et que les PRL de projection sont déterminés à partir des projections de la dynamique des populations à l’échelle de l’UC. Nous discutons de la pertinence et des exigences de l’application des diverses méthodes d’estimation des PRL, en nous inspirant d’une variété de quantités de données disponibles lors des études de cas. En général, l’application des PRL fondés sur l’abondance agrégée peut se limiter aux UGS où il y a une covariance des populations à l’échelle de l’UC, comme le démontre l’étude de cas sur le saumon coho du Fraser intérieur, et où la covariance n’a pas changé au fil du temps ou, pour les PRL de projection, où ces changements peuvent être mesurés.
header:
output:
 csasdown::resdoc_pdf:
   french: true
   copy_sty: true
   line_nums: false
   line_nums_mod: 1

# ------------
# End of options to set
knit: bookdown::render_book
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
  - \usepackage{amsmath} \usepackage{graphics} \usepackage{tcolorbox} \usepackage{afterpage} \usepackage{needspace} \usepackage{tikz} \usetikzlibrary{shapes, arrows.meta, positioning}

---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(# Prevent xtable from adding a timestamp comment to the table code it produces
        xtable.comment = FALSE,
        # Don't allow kableExtra to load packages, we add them manually in csasdown
        kableExtra.latex.load_packages = FALSE,
        # Stop chunk output (echo) running into the margins
        width = 80,
        # Don't use scientific notation (stops tables from showing 1.2e3, etc.)
        scipen = 999)
```


```{r load-libraries, cache=FALSE}
meta <- rmarkdown::metadata$output
if (is.null(meta)) {
  # This knitr chunk has been run in R without running bookdown::render_book("index.Rmd")
  # so rmarkdown::metadata$output is not populated
  options(french = FALSE)
} else {
  if (length(grep("pdf", names(meta)))) {
    options(french = meta$`csasdown::resdoc_pdf`$french)
    prepub <- meta$`csasdown::resdoc_pdf`$prepub
  } else if (length(grep("word", names(meta)))) {
    options(french = meta$`csasdown::resdoc_word`$french)
    prepub <- meta$`csasdown::resdoc_word`$prepub
  }
}
csl <- "csl/csas.csl"
if (is.null(getOption("french"))) {
  stop("`french` was not set up correctly in YAML header in index.Rmd. ",
       "It must be true or false",
       call. = FALSE)
}
if (getOption("french")) {
  csl <- "csl/csas-french.csl"
  options(OutDec = ",")
}
# This hook simplifies document translation for the author.
# When building in French, it draws a box around paragraphs contained in chunks
#  which have the option `needs_trans = TRUE`. It also labels
#  the box with a 'Needs translation' tag in red and the chunk label in blue.
# You need to change the `needs_trans` option to `FALSE` for a chunk once you
#  have inserted the translated text into it. You will get a utf-8 error if
#  you leave it as `TRUE` and there is French in the chunk.
#  This function assumes you are translating from English to French.
#  If you wrote your document in French and want to translate to English,
#  put a ! before `getOption("french")` below and add the `need_trans`
#  chunk options to your English paragraph chunks instead of the French ones.
#  
#  IMPORTANT NOTES
#  - You must use double backslashes in all paragraph chunks, so anywhere you
#    would normally use a single backslash, use two backslashes.
#    Examples are \@ref() which needs to be \\@ref() and \pi which must now be \\pi.
#  - French latex places a space before the colon by default so if you need a colon
#    with no space before it, use \\hc .
knit_hooks$set(needs_trans = function(before, options){
  if(getOption("french") && options$needs_trans){
    if (before){
      paste0("\\
       \\begin{lrbox}{\\userinput}
       \\begin{minipage}{\\dimexpr\\linewidth-2\\fboxsep-2\\fboxrule}
       \\textcolor{red}{\\textbf{Needs translation - \\textcolor{blue}{knitr chunk: ", options$label, "}}}
       \\begin{lstlisting}
      ")
    } else {
      "
       \\end{lstlisting}
       \\end{minipage}
       \\end{lrbox}
       \\noindent
       \\fbox{\\usebox{\\userinput}}
      "
    }
  }
})

# add other packages here:
library(dplyr)
library(readr)
library(tibble)
library(csasdown)
library(kableExtra)
library(ggplot2)
library(viridis)
library(tidyr)

```

---
csl: `r csl`    
---
