# PRINCIPES POUR L’ÉLABORATION DES POINTS DE RÉFÉRENCE LIMITES (PRL) {#principles}


\begin{tcolorbox}[standard jigsaw,opacityback=0.8,colframe=black,boxrule=0.7pt,left=0.1in, sharp corners]
\subsection*{Principaux points:}
\begin{itemize}
\item Les principes de détermination des PRL du saumon du Pacifique sont adaptés des directives nationales sur les PRL.%, as:
\item \textbf{Principe 1.} Les PRL doivent être choisis en fonction des meilleures informations disponibles. 
\item \textbf{Principe 2.} Les PRL doivent être compatibles avec l’objectif d’éviter tout dommage grave. 
\item \textbf{Principe 3.} Les PRL doivent être opérationnels, c’est-à-dire calculables et pertinents pour le contexte stratégique et la gestion. 
\item \textbf{Principe 4.} Les PRL doivent être plausible et pouvoir être estimés de manière fiable. 
\item \textbf{Principe 5.} Au moment de choisir entre plusieurs méthodes pour déterminer les PRL, il faut tenir compte de l’incertitude. 
\item \textbf{Principe 6.} Les PRL du saumon du Pacifique doivent être compatibles avec les buts et objectifs de la Politique concernant le saumon sauvage (PSS).
\item Ces principes visent à guider notre approche pour l’élaboration des PRL du saumon du Pacifique tout en offrant une certaine souplesse en raison des différences entre les espèces et les stocks de saumon pour ce qui touche les caractéristiques biologiques locales ainsi que la qualité des données et leur quantité.
\end{itemize}
\end{tcolorbox}


## PRINCIPES

Nous présentons ici les principes d’élaboration des PRL pour le saumon du Pacifique, adaptés de ceux développés pour les directives nationales sur les PRL (Marentette et al. en cours de révision). Ces lignes directrices permettent une certaine souplesse dans l’élaboration des PRL afin de respecter les différences dans les cycles biologiques des espèces et les types, quantités et qualités de données, et ne se veut pas prescriptive. En suivant des principes similaires, les PRL du saumon du Pacifique sont harmonisés avec les directives nationales.  



**Principe 1**. Les PRL doivent être choisis selon les meilleures informations disponibles pour l’unité de gestion des stocks (UGS), y compris les signes de dommages graves, les données et les connaissances sur les processus biologiques sous-jacents, les connaissances autochtones et la comparaison avec des UGS similaires (Marentette et al. en cours de révision). Les critères d’évaluation des meilleures informations scientifiques élaborés pour les normes nationales américaines peuvent s’appliquer ici [@USCodeFederal2021]. Ces critères sont les suivants: la pertinence, l’inclusivité, l’objectivité, la transparence et l’ouverture, le caractère opportun, la vérification et la validation, et l’examen par les pairs. En outre, les informations scientifiques doivent inclure une évaluation des incertitudes et cerner les lacunes dans notre compréhension ou nos informations. Lorsqu’il existe une incertitude dans la détermination de l’approche la plus appropriée pour définir un PRL, ces incertitudes doivent être reconnues et prises en compte lors de la formulation de recommandations sur le PRL. Lorsque le poids de la preuve soutient un ensemble de suppositions ou d’hypothèses associées à un PRL potentiel, alors ce PRL peut être recommandé. Lorsque les preuves ne sont pas concluantes, cette incertitude doit être intégrée dans l’estimation de l’état et les incertitudes doivent être clairement communiquées.

Dans le cadre de ce principe, il est reconnu que la science n’est pas statique et que de nouvelles découvertes font continuellement progresser notre compréhension des meilleures informations disponibles. En particulier, l’examen par les pairs est nécessaire pour garantir que la qualité et la crédibilité des données et des méthodes d’élaboration du PRL répondent aux normes de la communauté scientifique. Pour déterminer s’il y a lieu de procéder à un examen par les pairs, il faut tenir compte du niveau de nouveauté et de complexité, ainsi que de toute évaluation de stock antérieure examinée par les pairs. Bien que les mises à jour régulières puissent ne pas nécessiter d’examen officiel par les pairs, les nouveaux PRL ou l’application des points de référence et des PRL à de nouvelles unités de conservation (UC) et UGS peuvent nécessiter un examen par les pairs. 

De même, les meilleures pratiques, ou les pratiques dont il a été démontré qu’elles fonctionnent bien, peuvent être utilisées pour éclairer les points de référence, tels que définis par @sainsburyBestPracticeReference2008: « Le concept de pratique exemplaire est basé sur la pratique exemplaire qui a été démontrée par l’utilisation, et reconnaît que les points de vue sur ce qui est meilleur s’amélioreront continuellement avec l’expérience. Les pratiques exemplaires ne sont pas une entité absolue ou fixe, ni une garantie d’adéquation. Elles sont fondées sur l’expérience acquise à ce jour et devraient évoluer avec le temps ».


**Principe 2**. Les PRL doivent être compatibles avec l’objectif d’éviter tout dommage grave à l’UGS, comme il est décrit dans @dfoFisheryDecisionmakingFramework2009 et dans la section \@ref(intro) du présent document. Le PRL devrait être fixé au-dessus du niveau où des dommages graves se produisent et devrait éviter les pertes à long terme qui peuvent accompagner ces états indésirables, comme celles liées à la pêche et aux composantes de l’écosystème, par exemple les prédateurs dépendants [@dfoFisheryDecisionmakingFramework2009; @dfoPolicyNewFisheries2009]. En outre, les PRL doivent être représentatifs de l’ensemble de l’UGS. Dans les cas où seuls les composants d’une UGS sont surveillés (par exemple, les UC), le composant surveillé peut être utilisé pour évaluer l’état de l’UGS lorsqu’il est considéré comme représentant l’ensemble de l’UGS (section \@ref(guidelines)). 


<!--Marentette et al Principle 2:
2.1	Indicators and LRPs should be at minimum conceptually linked to one or more interpretations of serious harm such as impaired recruitment, productivity, resilience or ability to recover from perturbation.  
2.2	Indicators and LRPs should be representative of the entire stock.
2.3	Indicators should generally be proportional to the stock attributes they are intended to represent.
"Under a default assumption that loss of stock structure is serious harm and is to be avoided, the configuration of indicator(s) chosen should typically be representative of the entire “stock.” This could include scenarios where representative or index subcomponents are monitored or combined in various ways to represent the entire “stock.” Indicators should also proportionality with stock attributes they are intended to measure (e.g., CPUE should be an acceptable proxy for stock size), particularly when management measures respond but the relative importance of these characteristics in driving the choice of indicator may be context-dependent"-->
<!--CH: collapse this principle  into principles 1 and 2 based on discussions with NHQ 14 Jan 2022-->

<!--CH to consider further emphasizing possibility of using TK for identifying LRPs in other places in this WP?-->

**Principe 3**. Les PRL doivent être opérationnels. Ils doivent pouvoir être calculés selon les données disponibles et pertinentes pour le contexte stratégique et la gestion de la pêche dans les UGS. <!--KH: do you need to say ‘management of fisheries on SMUs’, or can it just be ‘management’ more broadly?? Not sure. I’m leaing towards keeping as fisheries for now.--> La disponibilité des données varie considérablement entre les UC et les UGS, ce qui nécessite diverses approches pour les évaluations au niveau des UC et des UGS. Aucune méthode ne sera opérationnelle dans tous les cas. De plus, il est avantageux que les PRL soient faciles à communiquer aux gestionnaires, aux Premières Nations et aux intervenants, de manière à éclairer les décisions à des échelles de temps pertinentes pour la gestion. D’autres considérations opérationnelles sont le rapport coût-efficacité et la simplicité de compréhension.  

<!-- CW: How is this different from the previous principle, "based on best available information" I suggest we leave this principle with just the relevant to the policy and easy to communicate (although I think that "easy" is debatable, I would not say that Sgen and SPR40 are easy to communicate, I don't think most people understand them, but they can be used to inform decisions) 
CH: this idea of 'feasible to calculate' came from Julie's recap at the TESA workshop where she mentioned how participants interpreted 'operational'. I'd prefer to leave in for now, but can take out in a later draft.
-->

<!--CH consider Marentette et al.: 

"3.1	At minimum, indicators and LRPs should be feasible to estimate on time scales relevant for management.
3.2	Consider what indicators are most useful for harvest strategies.
3.3	While status relative to the LRP triggers the need for a rebuilding plan, reference points in general do not need to be operational control points in harvest control rules.
3.4	Consider how often LRP estimates will be updated.
3.5	Consider how advice on stock status will be given.
3.6	While there is no universal choice, weigh benefits and challenges of less common indicators and LRPs.
LRPs are part of harvest strategies and success in achieving an objective to avoid serious harm to the stock (and more broadly, the sustainability of the fishery) will depend on other elements such as target harvest rates, tolerable risks of breaching limits and over timeframes risks are considered, not just the LRP.
At minimum, indicators, LRPs and therefore status should be feasible to measure or estimate. Other operational reasons to consider indicators, LRPs or status metrics may be: cost-effectiveness (impacting the ease and frequency of estimating stock status), communicability (affecting the ease of understanding), simplicity, the role that LRPs or stock status may play in HCRs or triggering the need for a rebuilding plan, or the need to estimate stock status to evaluate either trends over time or performance of management measures. These reasons are not mutually exclusive, and the relative priority of reasons that make a choice of indicator, LRP or metric of status “operationally useful” will be context-dependent, both within or across traditional versus procedural paradigms."
-->

**Principe 4**. Les PRL doivent être estimés de manière fiable. Dans la mesure du possible, les PRL doivent indiquer un niveau au-dessus duquel un préjudice grave se produit avec une exactitude et une précision acceptables, au lieu de saisir le bruit aléatoire ou les erreurs d’observation. La fiabilité de l’estimation dépendra de la qualité et de la fréquence de la collecte des données, de la spécification du modèle et des preuves à l’appui des relations sous-jacentes et de la dynamique des populations utilisées pour dériver les PRL. La fiabilité peut être abordée en vérifiant la sensibilité des PRL aux incertitudes des données, des modèles ou des hypothèses sous-jacentes au moyen d’analyses de sensibilité ou d’évaluations par simulation, ou simplement en évaluant la plausibilité compte tenu des informations biologiques ou du cycle biologique de l’UGS (Marentette et al. en cours de révision).

Les PRL peuvent être calculés à l’aide de plusieurs approches analytiques. Si les PRL ne peuvent pas être estimés de manière fiable à l’aide d’une méthode ou d’une approche, il est conseillé d’envisager d’autres approches basées sur des ensembles d’hypothèses et/ou de données différents. Lorsque les estimations du PRL convergent à l’aide de différentes approches, cela renforce le fait que les méthodes saisissent la dynamique sous-jacente de la population malgré des hypothèses différentes et l’utilisation des données disponibles.

<!--RE: pgh below
CW: 'statistically integrated' or sequential Bayes? i.e. sampling from posterior. 
CH: I think the point of Staton et al. 2017 is that for salmon, statistical integration wasn't always essential and the standard sequential approach may be sufficient in many cases (though underestimating uncertainty). I don't think they necessarily recommended Bayes over frequentest. For the watershed-area model, I used TMB, but draw random draws from 95%CI of SREP to get uncertainties in benchmarks. We used TMB to minimize estimation time as we thought we would be running simulation evaluations.  So, I'd prefer not to include recommendation on Bayes vs Freq analyses. However, instead of recommending integrated analyses always,  we could recommend that it be considered. 
ÇW: agreed. --> 

Dans la mesure du possible, il convient d’envisager une approche statistiquement intégrée pour l’estimation des PRL afin de propager les incertitudes tout au long des analyses et de se conformer aux meilleures pratiques actuelles en matière d’évaluation des stocks de pêche [@puntEssentialFeaturesNextgeneration2020]. @statonSequentialIntegratedBayesian2017a et @defilippoImprovingShorttermRecruitment2021 fournissent des exemples récents de modèles intégrés utilisés pour l’évaluation des saumons. Les deux études montrent que la propagation de l’incertitude augmente le réalisme des estimations du modèle et de l’incertitude associée. Cependant, @statonSequentialIntegratedBayesian2017a ont démontré que des estimations ponctuelles similaires de l’état actuel peuvent être obtenues en utilisant des approches d’estimation séquentielles et que les avantages des approches statistiquement intégrées peuvent ne pas être suffisamment importants pour justifier une analyse intégrée dans tous les cas.  


<!--CH: consider Marentette et al: 
"4.1	Check for consistency and robustness of estimates to uncertainties.
4.2	Consider whether estimates are plausible given other information about the stock.
4.3	Consider using historical or empirical proxies if direct estimates are unreliable.
4.4	Consider the quality of input data.
4.5	Consider smoothing to address inter-annual variability.
4.6	Consider simulation testing of estimability.
Reliable estimation of limit reference points or stock status metrics can mean acceptable consistency, accuracy or precision of estimates (i.e., acceptably low variance or low bias),  and robustness to a range of possible uncertainties (assumptions, stock scale, data points and/or model structure). Reliability of reference points or status may also depend on reliable and consistent data collection. Reliability may be evaluated by examining uncertainty in estimates, sensitivity tests, evaluating the reasonableness of assumptions, simulation testing and/or by comparison to other similar stocks.
"
-->

**Principe 5**. Lors de la sélection parmi plusieurs méthodes pour définir les PRL, le choix doit tenir compte de l’incertitude <!-- CW: Risk or uncertainty? I think of risk as associated with FM and objectives. i.e. prob of achieving something. LW: Ya I’m not sure on risk vs. uncertainty here. I understand the intent of accounting for uncertainty in data/assumptions. At the same time when I think of risk I think of probability*magnitude of something happening, e.g., risk of climate change impacts on productivity. Uncertainty/assumptions in data and methods result in a risk of an LRP not being set above the point where serious harm occurs. Also, I think of setting an LRP at a certain probability of the SMU not reaching the point of serious harm (as mentioned in Ch 1 and in Kronlund et al. 2018). Is what we’re trying to get at here that selection of methods should be precautionary, as in http://publications.gc.ca/collections/Collection/CP22-70-2003E.pdf? -->. Les méthodes candidates pour les PRL varient dans la manière et l’étendue de leur prise en compte de l’incertitude des données sous-jacentes, de la dynamique de la population modélisée (hypothèses de paramètres et structure du modèle), et de l’établissement des états à l’échelle des UC. Ces incertitudes créent des risques que les PRL fournissent un seuil trompeur de dommage grave. Toutes choses égales par ailleurs, il convient de privilégier les méthodes qui reposent sur des données de haute qualité, comportent moins d’hypothèses et tiennent compte explicitement des incertitudes sous-jacentes <!-- KH: not clear on the remainder of this sentence, so suggest removing “.., and explicitly account for underlying uncertainties should be preferred”. CH. I think a comma after high-qulaity data was missing before which changed the meaning of the sentence. I’ve kept the last phrase in, with the new comma.-->. 

Lors de l’examen des PRL en fonction d’autres hypothèses de modèle, les PRL peuvent être choisis en fonction de la force des preuves pour les hypothèses sous-jacentes ou en fonction de la moyenne lorsque d’autres hypothèses sont tout aussi plausibles. En outre, la sensibilité des PRL à diverses hypothèses de modèles sous-jacents ou à des qualités et quantités de données peut être évaluée par simulation, les PRL les moins sensibles aux principales incertitudes étant préférables.



<!--CH: This principle supports use of ppn-based LRPs over aggregate abundance-based LRPs (b/c of uncertain assumptions in LR), with some justification for considering aggregate abundance-based LRPs that are statistically integrated so account of uncertainty in CU benchmarks. I have added to chapter on guidelines  -->

<!--CH: from Marentette et al:
Principle 5: When selecting from multiple alternatives, the choice of stock status indicators and LRPs should take into account risk.
5.1	If working with fixed values?, consider averaging among plausible alternatives.
5.2	Consider the highest of several plausible alternatives.
5.3	Evaluate plausible LRPs with simulation.

-->


**Principe 6**. En plus des principes dérivés pour les espèces marines en général (principes 1 à 5) et pour atteindre l’objectif d’éviter les dommages graves en vertu de la politique de l’approche de précaution du MPO (principe 2), les PRL du saumon du Pacifique devraient être conformes aux buts et objectifs de la PSS. La PSS exige à la fois la définition d’unités biologiques et l’évaluation de leur état selon des paramètres biologiques, les points de référence inférieurs étant utilisés pour représenter le niveau qui évite le risque d’extinction. Cette approche est compatible avec la volonté d’éviter tout préjudice grave à l’UC. Au-dessus des points de référence inférieurs (au-dessus de l’état rouge), les répercussions irréversibles ou lentement réversibles sont évitées. Ignorer l’état au niveau de l’UC en se concentrant uniquement sur l’état au niveau de l’UGS peut entraîner l’épuisement en série (ou la perte) d’UC faibles au sein d’une UGS, entraînant un état indicateur éventuellement trompeur et un dommage grave. Par conséquent, par souci de cohérence avec la PSS, les PLR doivent prendre en compte l’états des UC composant l’UGS.

## APPLICATION DES PRINCIPES À L’ÉLABORATION DES PRL

Notre objectif est de fournir des directives générales sur l’élaboration des PRL en suivant les principes énumérés ci-dessus tout en offrant une certaine souplesse en raison des différences entre les espèces de saumon du Pacifique et les UGS sur le plan des caractéristiques biologiques, du type de données, de la quantité de données et de la qualité des données. Nous indiquons dans quelle mesure les méthodes de PRL potentiels proposés ici sont conformes à ces principes. <!--KH: can you be more specific on how / where we demonstrate this? - or, would it be more correct to say “We demonstrate the application of candidate LRP methods that are aligned with these principles? CH: I explain alignment to principles in the text of the next section. I think it’s okay to leave as is, though I changed ‘demonstrate’ to ‘indicate’-->D’autres méthodes de détermination des PRL pourraient être élaborées à l’avenir afin de saisir un plus large éventail de disponibilité, de qualité et de types de données, et/ou de dimensions de l’état biologique; l’élaboration de ces méthodes supplémentaires devrait s’harmoniser avec les principes clés résumés ici.


Dans la section suivante, les méthodes d’estimation de l’état des UC sont décrites, telles qu’elles ont été mises en œuvre dans les évaluations précédentes de l’état des UC dans le cadre de la PSS, et des PRL potentiels sont proposés. Les directives sur la façon de choisir parmi les PRL sont décrites dans la section \@ref(guidelines). 
 




