# LIGNES DIRECTRICES POUR L'APPLICATION DES POINTS DE RÉFÉRENCE LIMITES (PRL) {#guidelines}

## APPROCHE ÉTAPE PAR ÉTAPE POUR LA SÉLECTION DES PRL

\begin{tcolorbox}[standard jigsaw,opacityback=0.8,colframe=black,boxrule=0.7pt,left=0.1in, sharp corners]
\subsection*{Principaux points:}
\begin{itemize} 
\item Nous recommandons une approche par étapes pour l’élaboration des PRL qui met en évidence les étapes, les considérations et les décisions importantes lors de la détermination des PRL. Ces étapes constituent nos lignes directrices pour le choix et la mise en œuvre des méthodes candidates de PRL.
\item  \textbf{Étape 1.} Compiler les données 
\item  \textbf{Étape 2.} Évaluer les lacunes dans les données de l’unité de conservation (UC)
\item  \textbf{Étape 3.} Évaluer si les UC sans données peuvent être représentées par des UC avec des données.
\item  \textbf{Étape 4.} Déterminer quelle proportion d’UC au-dessus de l’état rouge (parmi celles disposant de données) est nécessaire pour éviter un dommage grave. Nous recommandons 100\ % comme valeur par défaut.
\item  \textbf{Étape 5.} Évaluer l’état de l’unité de gestion des stocks (UGS) par rapport au PRL fondé sur l’état des UC
\item  \textbf{Étape 6.} Effectuer un examen par les pairs de l’état par rapport au PRL fondé sur l’état des UC
\item  \textbf{Étape 7.} Déterminer si les PRL fondés sur l’abondance globale sont nécessaires pour la gestion des pêches. 
\item  \textbf{Étape 8.} Si oui, estimer les PRL fondés sur l’abondance globale et évaluer dans quelle mesure les hypothèses sous-jacentes sont respectées.
\item  \textbf{Étape 9.} Si oui, appliquer les PRL fondés sur l’abondance globale pour obtenir un état au niveau de l’UGS.
\end{itemize}
\end{tcolorbox}

Nous recommandons une approche progressive pour déterminer les PRL, avec la proportion d'UC composantes dont l'état est supérieur à rouge comme méthode par défaut (fig. \@ref(fig:flowchart)). C'est la méthode recommandée pour répondre à l'exigence de la *Loi sur les pêches* pour les PRL, et étant basée sur l'unité biologique de l'UC, elle peut être appliquée à de nombreux aspects de la gestion du saumon, y compris l'éclosion, la récolte et la gestion de l'habitat. Les PRL d'abondance globale sont présentés comme une option pour les cas où ils sont requis pour la gestion des pêches (par exemple, à l'échelle locale ou internationale), mais ils sont considérés comme complémentaires à la proportion d'UC dont l'état est supérieur à rouge. L'approche par étapes présentée ci-dessous tient compte de la disponibilité des données pour les méthodes potentielles d'établissement du PRL et fournit des conseils lorsque des incohérences dans l'état apparaissent suite à l'application de plusieurs méthodes de PRL. Ces étapes peuvent être adaptées à l'avenir, à mesure que d'autres méthodes sont élaborées et/ou que ces méthodes sont appliquées et évaluées dans d'autres UGS et contextes. Ces étapes ont été élaborées pour être cohérentes avec les principes décrits dans la section \@ref(principles). <!-- CH: old colours: fill=yellow! 10, fill=cyan! 10, fill=magenta! 10, fill=brown! 10, fill=green! 10, boxgray, intead of box,-->


\begin{figure}[ht]
\centering
\tikzstyle{box} = [rectangle, rounded corners, minimum width=10cm, minimum height=1cm, text width = 10cm, draw=black]
\tikzstyle{boxgray} = [rectangle, rounded corners, minimum width=10cm, minimum height=1cm, text width = 10cm, draw=black, fill=gray!10]
\tikzstyle{boxno} = [rectangle, rounded corners, minimum width=4cm, minimum height=1cm, text centered, text width = 4cm, draw=black]
\tikzstyle{arrow} = [thick,->,>=stealth]
\begin{tikzpicture} [node distance = 1.5cm]
\node(1) [box, fill=yellow!10] {1. Compiler les données};
\node(2) [box, fill=yellow!10, below of=1] {2. Évaluer les lacunes dans les données des UC};
\node(3) [box, fill=yellow!10, below of= 2] {3. Déterminer si l’état des UC manquant de données peut être déduit des UC avec des données};
\node(4) [box, fill=yellow!10, below of= 3] {4. Quelle proportion d’UC au-dessus de l’état rouge est nécessaire pour éviter des dommages graves? Valeur par défaut  = 100\%};
\node(5) [box, fill=yellow!10, below of=4] {5. Évaluer l’état par rapport au PRL fondé sur l’état des UC};
\node(6) [box, fill=yellow!10, below of=5] {6. Effectuer un examen par les pairs des états des UC étayant le PRL fondé sur l’état des UC (y compris l’examen des étapes 1-5)};
\node(7) [box, below of=6, fill=blue!10] {7. Les PRL fondés sur l’abondance globale sont-ils nécessaires pour les décisions de gestion des pêches?};
\node(8) [box, below of=7, fill=blue!10, yshift=-1.7cm] {8. Estimer les PRL de l’abondance globale\\(a) Établir la probabilité acceptable que tous les UC $>$ points de référence inférieurs \\b) Choisir le PRL de régression logistique et/ou le PRL de projection, selon les hypothèses qui sont satisfaites\\c) Estimer les PRL};
\node(8n) [boxno, right of=8, xshift=6cm, yshift=2.0cm] {S’appuyer uniquement sur les PRL fondés sur l’état des UC (étape 5)};
\node(9) [box, fill=blue!10, below of=8, yshift=-1.7cm] {9. Évaluer l’état par rapport aux PRL d’abondance globale et le comparer à celui des PRL fondés sur l’état des UC (étape 5)};
\node(9n) [boxno, right of=9, xshift=6cm, yshift=1.0cm] {Les PRL fondés sur l’abondance globale ne peuvent être estimés};
\draw[arrow] (1) -- (2);
\draw[arrow] (2) -- (3);
\draw[arrow] (3) -- (4);
\draw[arrow] (4) -- (5);
\draw[arrow] (5) -- (6);
\draw[arrow] (6) -- (7);
\draw[arrow] (7) -- node[anchor=east] {Oui} (8);
\draw[arrow] (7) -| node[anchor=west] {Non} (8n);
\draw[arrow] (8) -- node[anchor=east] {Hypothèses confirmées} (9);
\draw[arrow] (8) -| node[anchor=west] {Hypothèses non confirmées} (9n);
\end{tikzpicture}
\caption{Étapes de l’établissement des PRL et de l’évaluation de l’état. Les cases jaune pâle indiquent celles pour l’estimation des PRL fondés sur l’état des UC. Les cases bleues indiquent celles des PRL fondés sur l’abondance globale. Les cases blanches indiquent les cas où il n’est pas recommandé d’utiliser une méthode du PRL fondé sur l’abondance globale.}
(\#fig:flowchart)
\end{figure}

### Étape 1: Compilation des données

La première étape consiste à colliger les données au niveau des UC pour soutenir les évaluations de l'état biologique, comme le décrit la Politique concernant le saumon sauvage (PSS) [@holtIndicatorsStatusBenchmarks2009; @holtEvaluatingBenchmarksBiological2018]. Ces données comprennent (mais sans s'y limiter) des séries chronologiques d'abondances de géniteurs, de recrutement, de contributions d'écloserie, de productivité et de points de référence biologiques sur les abondances de géniteurs. Cette étape comprend généralement le regroupement des données au niveau du site de fraie ou du cours d'eau jusqu'au niveau de l'UC.

Dans certains cas, des échelles spatiales plus fines que les UC (par exemple, les bassins versants ou les sous-populations au sein des UC) peuvent être considérées pour définir un dommage grave à une UGS. Bien que les UC soient l'unité de population d'évaluation et de conservation requise par la PSS, la répartition de la fraie au sein des UC (par exemple, parmi les bassins versants ou les sous-populations) peut être une composante importante de l'état [@holtIndicatorsStatusBenchmarks2009] et ces échelles plus fines peuvent être prises en compte lorsque les données ou les informations justificatives le permettent. La répartition est une composante communément citée de la viabilité et du rétablissement du saumon [@mcelhanyViableSalmonidPopulations2000]. Lors de l'application à la détermination des objectifs de rétablissement du saumon du Pacifique, @bradfordReviewBiologicalPrinciples2004 ont défini l'échelle de répartition pertinente en unités de sous-populations qui sont démographiquement indépendantes, où la dynamique de la population d'une sous-population est peu susceptible d'affecter la dynamique d'une autre. Les échanges génétiques entre les sous-populations devraient se produire à des taux plus élevés que ceux observés entre les UC (ou les populations), et dépasseraient probablement 10 migrants effectifs par génération. En appliquant ces critères au saumon coho du Fraser intérieur, @bradfordReviewBiologicalPrinciples2004 ont défini des sous-populations en fonction de grands bassins versants ou de lacs, ou d'obstacles partiels à la migration.

Nous recommandons que la décision sur la répartition et l'échelle spatiale de conservation pour les évaluations biologiques fasse partie du processus d'examen par les pairs pour les évaluations des UC et de l'UGS, et qu'elle soit basée sur les principes biologiques de conservation et de viabilité [p. ex., comme il est examiné dans @bradfordReviewBiologicalPrinciples2004; @mcelhanyViableSalmonidPopulations2000].

Dans le cadre de cette étape, les informations sur l'apport des écloseries sont utilisées pour identifier les populations où la production est dominée par des poissons provenant d'écloseries. Ces populations (identifiées par des valeurs de l'influence naturelle proportionnelle (INP) $<$ 0,5, ou par l'avis d'experts lorsque les données sur la proportion de géniteurs issus d'écloseries ne sont pas disponibles) sont généralement exclues des analyses, tandis que celles qui sont dominées par des poissons d'origine naturelle (par exemple, les valeurs de l'INP sont $\geqslant$ 0,5), sont généralement incluses [@withlerGeneticallyBasedTargets2018]. De plus, lorsque des séries chronologiques de la proportion de saumons issus d'écloseries dans les frayères sont disponibles et que la production est dominée par des poissons d'origine naturelle, ces proportions peuvent être utilisées pour générer des séries chronologiques du recrutement d'origine naturelle pour l'estimation des points de référence et des géniteurs d'origine naturelle pour l'évaluation de l'état par rapport aux points de référence. Lorsque l'influence de la production en écloserie est ainsi éliminée, les évaluations sont moins sensibles à la présence d'écloseries et à la variation annuelle des pratiques d'écloserie.

En ce qui concerne les cours d'eau et les sites de fraie, le comblement pour les années où il y a des données manquantes est couramment utilisé lors de la compilation des séries d'abondance des géniteurs au niveau des UC [p. ex., voir @grantEvaluationUncertaintyFraser2012; @brown2020SummaryAbundance2020]. Lorsque des séries chronologiques comblées sont utilisées pour estimer les PRL et surveiller l'état des stocks par rapport aux PRL, il faut tenir compte de l'échelle à laquelle le comblement est effectué. Si les PRL sont basés sur le maintien de la diversité au niveau des UC, le comblement des données manquantes ne devrait généralement pas être basé sur les échappées provenant de l'extérieur de l'UC. Le comblement entre les UC augmente l'incertitude et peut fournir un état trompeur pour l'UC qui est remplie, si les UC divergent sur le plan de l'état et de tendances (voir étape 3). En outre, l'apport des écloseries doit être soigneusement pris en compte lors du comblement afin d'éviter de surestimer les abondances lorsque les chiffres du comblement sont basés sur des sites qui sont artificiellement renforcés et lorsque les niveaux d'aménagement varient au cours de la série chronologique.

### Étape 2: Évaluer les lacunes dans les données des UC

Ensuite, les UC disposant de données pour soutenir les évaluations biologiques sont identifiées; celles qui ne disposent pas de données suffisantes sont considérées comme manquant de données. Les UC sont évaluées en fonction de divers paramètres, dont l'abondance et les tendances, et les exigences en matière de données pour ces paramètres varient. Au minimum, une UC doit avoir un indice des séries chronologiques de l'abondance des géniteurs. Ces données peuvent être utilisées pour estimer les tendances dans le temps par rapport à des points de référence communs à toutes les UC [@holtIndicatorsStatusBenchmarks2009]. Pour les analyses de tendances à court terme, les données sont considérées comme insuffisantes lorsqu'elles incluent moins de la moitié des années disponibles dans les trois dernières générations ou qu'elles sont de faible qualité et ne représentent que la présence/l'absence. Ces critères de détection des tendances sont similaires aux critères décrits dans @brown2020SummaryAbundance2020 et appliqués aux sites de fraie du saumon chinook dans le sud de la Colombie-Britannique.

En outre, l'abondance actuelle des géniteurs peut être comparée à des repères basés sur l'abondance, où l'abondance actuelle des géniteurs est généralement définie comme la moyenne géométrique de l'abondance des géniteurs sur la génération la plus récente. Pour cette mesure, il est nécessaire de disposer d'au moins une année d'abondance de géniteurs dans la génération actuelle pour pouvoir la comparer à des références. Les repères spécifiques à l'UC sur l'abondance des géniteurs peuvent être dérivés de modèles de recrutement de géniteurs, de percentiles de séries temporelles de géniteurs, ou de caractéristiques d'habitat. Les besoins en données pour l'estimation de points de référence sur l'abondance des géniteurs diffèrent selon les méthodes appliquées et ne sont pas explicitement définis ici. Une expertise biologique locale est nécessaire pour examiner les données et les points de référence disponibles avant les évaluations afin d'identifier les lacunes dans les données. Par exemple, <!--spawner-recruitment benchmarks developed from hierarchical multi-stock models require fewer years of data than those based on individual stock-recruitment models. In addition, -->les changements dans les conditions environnementales au fil du temps peuvent entraîner des données historiques qui ne sont plus représentatives des conditions actuelles, ce qui entraîne des lacunes dans les données.

<!--In addition, a CU may be data deficient when data to resolve the existence of the CU are insufficient. For example, @holtbyConservationUnitsPacific2007 describe provisional CUs pending acquisition of genetic samples to differentiate them from neighbouring CUs. Further work verifying, expanding, and updating these guidelines for data deficiencies in the context of different salmon species, life-histories, and assessment metrics is warranted. -->

### Étape 3: Déterminer si l'état des UC manquant de données peut être déduit des UC avec des données

Troisièmement, la mesure dans laquelle l'état des UC manquant de données peut être déduit des UC disposant de données est évaluée. Par définition, les UC pauvres en données ne disposent pas de données sur la dynamique des populations pour évaluer rigoureusement dans quelle mesure d'autres UC disposant de données pourraient être utilisées pour représenter leur état, bien que des informations sur les menaces et les caractéristiques biologiques puissent être disponibles. Pour déduire l'état des UC avec peu de données, nous recommandons au minimum de fournir des preuves que: i) les menaces ayant une incidence sur les UC à données insuffisantes sont probablement les mêmes que pour les UC avec des données et leur ampleur est similaire, ii) les facteurs environnementaux dominants sont similaires entre les UC, par exemple, comme le reflète la répartition des UC dans les écosystèmes d'eau douce et marins, iii) les caractéristiques biologiques, telles que le type de cycle biologique et l'âge dominant à la maturité des UC sans données, sont représentées dans les UC avec données, et iv) la capacité de charge des UC sans données est probablement du même ordre que celle des UC avec données. Les preuves à l'appui de ces critères doivent être clairement documentées et examinées par des experts locaux. Le poids de la preuve est d'indiquer que les UC manquant de données ont des propriétés similaires aux UC voisines, avec l'hypothèse par défaut que chaque UC représente une biodiversité unique dont l'état et les tendances ne peuvent être représentés par d'autres UC. Nous donnons un aperçu des quatre critères dans le tableau \@ref(tab:CUrepres) et décrivons chacun d'eux plus en détail ci-dessous.


\renewcommand*{\arraystretch}{1.3}
\begin{longtable}[]{p{2.1cm} p{5.1cm} p{3.9cm} p{4cm}}
\caption{Critères d’évaluation de la représentativité des UC au sein des UGS.}\\
\hline
Critères & Justification et exemples de caractéristiques & Exemples de sources d’information\\ 
\hline
\endhead
Menaces  & Les menaces propres à l’UC peuvent avoir une incidence sur les taux de survie, la croissance et/ou le succès de la reproduction et, par conséquent, sur les états et les tendances & Les modifications de l’écosystème, y compris l’extraction de l’eau, la foresterie, les incendies, l’agriculture ainsi que le développement, la pêche, la pollution, l’aquaculture et les impacts génétiques des écloseries & Évaluations publiées sur les menaces et l’habitat par UC \\
Facteurs environ-nementaux  & Les conditions climatiques propres à l’UC peuvent avoir une incidence sur la survie, la croissance, la maturation ou le succès de reproduction et donc sur l’état et les tendances, soit en raison des facteurs environnementaux eux-mêmes, soit en raison de l’interaction de différents environnements avec des menaces anthropiques communes  & Eau douce: gradient fluvial, connectivité, macroclimat de l’habitat de fraie et d’élevage, régime hydrologique (p. ex., (1) pour le saumon chinook). Milieu marin: remontée d’eau, courants, productivité de l’environnement littoral à l’entrée de l’océan  &  Répartition des zones d’adaptation d’eau douce et marine (2), zones biogéoclimatiques décrivant les macroclimats, comme dans (3), caractéristiques de l’habitat fournies dans les évaluations des stocks propres à l’UC, savoir autochtone.\\
Caractéris-tiques du cycle biologique &  Les UC ayant les mêmes caractéristiques du cycle biologique, comme l’âge à l’entrée dans l’océan, sont plus susceptibles de se chevaucher dans la répartition spatiale et temporelle et donc de répondre de manière similaire aux menaces communes et aux facteurs environnementaux, par rapport à celles qui ont des caractéristiques divergentes & Type de cycle biologique (type fluvial par opposition à type océanique pour le saumon chinook), âge à l’entrée dans l’océan, âge au retour, période de migration  &  Informations biologiques propres aux UC provenant des évaluations de stocks, savoir autochtone. \\
Capacité de charge &  La taille de la population est liée à la probabilité de tomber en dessous des seuils critiques de conservation et donc à la vulnérabilité aux menaces et/ou aux perturbations aléatoires  & Abondance des géniteurs  &  Les informations biologiques propres à l’UC provenant d’évaluations de stocks, taille du bassin versant (4), savoir autochtone\\
\hline
(\#tab:CUrepres)
\end{longtable}
\footnotesize (1) [@beechieHydrologicRegimeConservation2006] (2) [@holtbyConservationUnitsPacific2007] (3) [@medingerEcosystemsBritishColumbia1991] (4) [@parkenHabitatbasedMethodsEstimate2006] 
\normalsize

**Les menaces** sont définies comme une activité ou un processus anthropique qui cause des dommages à une espèce, sa mort ou des modifications de son comportement, ou la destruction, la détérioration ou la perturbation de son habitat jusqu'au point où des effets sur la population peuvent se produire [@dfoGuidanceAssessingThreats2014]. Les UC qui sont exposées à différentes menaces en eau douce et en milieu marin au sein d'une UGS peuvent diverger en termes de caractéristiques biologiques telles que la survie, la croissance et le succès de la reproduction et, par conséquent, d'états et de tendances.

Les UC peuvent varier dans leur exposition aux **conditions environnementales** liées à la variabilité des écosystèmes d'eau douce et marins, du macroclimat et de l'hydrologie dans une UGS. Bien que les UGS soient généralement définies comme des groupes d'UC cohésives dans l'espace, les différences de conditions environnementales entre UC voisines peuvent entraîner des différences d'état et de tendances.

Les UC ayant des caractéristiques similaires **sur le plan du cycle biologique** sont plus susceptibles de répondre de la même manière aux menaces communes et aux facteurs environnementaux que celles ayant des caractéristiques divergentes. Des différences dans les caractéristiques du cycle biologique ont évolué parmi les UC en raison de l'exposition à des conditions environnementales différentes et de la disponibilité de la nourriture [p. ex., @bourretDiversityJuvenileChinook2016]. Dans certains cas, les UGS ont été définies pour harmoniser les UC avec des cycles biologiques similaires (par exemple, le saumon chinook du Fraser où les UGS sont définies en partie selon les âges dominants à la maturité et le moment de la montaison des adultes). Dans d'autres UGS, les UC de divers types de cycle biologique sont combinées en fonction de leur emplacement géographique (p. ex. l'UGS du saumon chinook du bras de mer continental qui contient des UC de poissons de type océanique et de type fluvial).

Les UC ayant des **capacités de charge** différentes peuvent réagir différemment à des menaces similaires. Par exemple, les très petites UC peuvent être plus vulnérables à une pression de pêche modérée si les abondances baissent en dessous des seuils critiques de conservation (p. ex., 1 500 poissons, un seuil d'abondance dans l'explorateur de l'état du saumon du Pacifique), alors que les UC plus grandes peuvent être plus résilientes aux menaces communes.

La covariation de la productivité intrinsèque entre les populations qui sont situées à proximité l'une de l'autre est bien documentée chez les diverses espèces de saumon du Pacifique [@petermanPatternsCovariationSurvival1998; @pyperSpatialCovariationSurvival2002; @dornerSpatialTemporalPatterns2018], ce qui fournit un certain appui pour l'utilisation des UC riches en données pour éclairer les UC sans données. Dans une méta-analyse des séries chronologiques de géniteurs pour les espèces de saumon du Pacifique dans toute la Colombie-Britannique, à l'aide de données extraites de l'outil Pacific Salmon Explorer (Fondation du saumon du Pacifique 2020), les corrélations par paires dans les abondances de géniteurs entre les UC au sein des UGS avaient tendance à être positives (annexe \@ref(app:meta-analysis-appendix), fig. \@ref(fig:lrp-smu-corr-plot)).

Dans l'ensemble, nous suggérons d'être prudent lorsque l'on représente l'état des UGS avec seulement un sous-ensemble d'UC, et nous recommandons d'évaluer et de documenter les risques d'attribuer incorrectement un état aux UC manquant de données d'après les UC voisines. Nous recommandons également une évaluation quantitative plus poussée de ces critères en utilisant des données empiriques désagrégées en groupes d'UC ayant des conditions environnementales, des types de cycle biologique et une intensité de gestion similaires, entre autres variables. Ces critères ne se veulent pas normatifs, mais visent à fournir des directives générales pour tirer des conclusions pour les UC dont les données sont insuffisantes.

Si les UC manquant de données ne répondent pas aux critères d'inférence à partir des UC restantes au sein d'une UGS, nous recommandons la collecte de données au niveau des UC pour éclairer les évaluations biologiques. La collecte de données serait donc prioritaire pour les UC qui divergent des UC voisines sur le plan des menaces, des facteurs environnementaux, des caractéristiques du cycle biologique et/ou de la capacités de charge.

### Étape 4: Quelle proportion d'UC au-dessus de l'état rouge est nécessaire pour éviter un dommage grave?

Afin d'appliquer des PRL basés sur l'état des UC, il faut définir une limite inférieure à la proportion d'UC au-dessus de l'état rouge. Le @dfoFisheryDecisionmakingFramework2009 indique que les PRL sont basés sur des critères biologiques identifiés par les Sciences, indépendamment des processus de gestion. Étant donné que l'objectif de la PSS est de protéger la biodiversité du saumon du Pacifique en partie en maintenant les UC au-dessus des points de référence biologiques inférieurs, nous avons indiqué un seuil de 100 % des UC au-dessus de l'état rouge comme un PRL qui évitera un dommage grave. Des exceptions à ce PRL peuvent survenir lorsqu'il y a une incertitude ou une mauvaise identification dans la délimitation des UC [p. ex., comme pour certaines UC transfrontalières, @holtbyConservationUnitsPacific2007] ou des UC sont désignées comme étant disparues. Ces UC seraient omises du nombre total d'UC (existantes) au sein de l'UGS. <!--LW: question, so if a CU goes extinct it doesn’t count in the 100% LRP for the SMU anymore? Wouldn’t a CU going extinct represent serious harm/impaired productivity? - CH: but when it’s extinct by definition it can’t be recovered so a rebuliding plan is moot; unlike extirpated or critically endangered. CH: if it’s extinct it cannot be rebuilt by definition. I think out goal is to  assess serious harm on extant CUs. Proof of extinction takes a long time (.e., 30-50 years under COSEWIC), so I don’t think this the case for many; Until it’s designated extinct it would still be considered serious harm. -->

Cette étape omet les décisions sur la façon de prioriser les UC pour la conservation étant donné la variabilité de leur capacité à se rétablir. Pour certaines UC, le potentiel de rétablissement au-dessus de la zone rouge peut être extrêmement faible en raison de conditions naturelles ou de menaces anthropiques. Par exemple, certaines UC sont naturellement plus vulnérables aux menaces en raison de leurs caractéristiques biologiques (par exemple, la disponibilité limitée de l'habitat), ce qui les place dans la zone rouge. Toutefois, cette vulnérabilité naturelle ne diminue pas le dommage grave associé à la perte de biodiversité si cette UC est perdue. Le rétablissement peut également être limité par des menaces anthropiques telles que le changement climatique. De récentes évaluations de la vulnérabilité indiquent que de nombreuses populations de saumon ne résisteront pas au changement climatique au cours des prochaines décennies [@crozierClimateVulnerabilityAssessment2019; @crozierClimateChangeThreatens2021]. Ces considérations peuvent être indiquées dans les analyses du potentiel de rétablissement afin d'éclairer les décisions sur l'affectation des ressources dans tout plan de rétablissement ultérieur élaboré [par exemple, @carwardinePriorityThreatManagement2019]. <!--CH omit: Considerations on rebuilding potential should be part of the management objectives [@kronlundConsiderationsDesignRebuilding2021] and are outside the scope of identifying LRPs. Those analyses can then inform decisions about prioritizing CUs and management actions, with various sectors, First Nations, and stakeholders.-->

En outre, contrairement à de nombreuses autres pêches marines, les menaces et les leviers de gestion du saumon du Pacifique vont au-delà de ceux associés aux pêches qui sous-tendent la définition des UGS et des PRL. L'échelle des UGS est souvent incongrue avec l'échelle des menaces dominantes et des leviers de gestion. Par conséquent, les PRL fondés sur le fait que 100 % des UC sont au-dessus de l'état rouge peuvent déclencher l'élaboration de plans de rétablissement en vertu des dispositions sur les stocks de poissons lorsqu'une seule composante (p. ex. une seule UC) nécessite une intervention. De plus, les interventions les plus appropriées au niveau des UC peuvent ne pas être liées à la récolte (par exemple, les écloseries ou l'amélioration de l'habitat). Néanmoins, nous avons mentionné que 100 % des UC au sein de l'UGS devraient être au-dessus de leurs points de référence pour éviter un dommage grave en vertu des dispositions relatives aux stocks de poissons. Les déclencheurs et les interventions à des échelles spatiales plus fines et plus grossières seront également essentiels pour assurer la pérennité du saumon du Pacifique.<!--CH: This is meant to capture the concern that we might trigger RP when CU is already being managed in other ways, and at a different scales-->


<!--CH: not needed?? 
Once LRPs are identified, SMU-level objectives can be specified and management procedures evaluated to identify approaches that best meet objectives, including the prioritization of CU-specific interventions. Furthermore, objectives and management actions can be adapted to a range of spatial scales from CU to regional or multi-SMU scales and then evaluated in a hierarchical context. Deriving LRPs through this approach (100% of component CUs above Red status within an SMU) is a first step in that process.
-->

### Étape 5: Évaluer l'état par rapport à un PRL fondé sur l'état des UC

Nous recommandons que les PRL fondés sur l'état des UC soient l'approche par défaut pour déterminer les PRL du saumon du Pacifique. Cette méthode assure la cohérence avec les évaluations publiées précédemment dans le cadre de la PSS [@dfoWildSalmonPolicy2015; @dfoIntegratedBiologicalStatus2016; @grant2017FraserSockeye2020; @grantIntegratedBiologicalStatus2013] et permet d'évaluer l'état à une hiérarchie d'échelles pertinentes pour le rétablissement du saumon. <!--KH: suggest removing the next part of this sentence as I don;t think it will make sense without more description: “ by aggregating CUs as appropriate”-->.

En utilisant cette approche, l'état des UC individuelles est évalué et la proportion d'UC avec un état supérieur à rouge est ensuite comparée au PRL indiqué à l'étape 4. Lorsqu'elles sont disponibles, nous recommandons d'appliquer les évaluations des UC provenant d'évaluations récentes de l'état de la PSS évaluées par des pairs, dans lesquelles de multiples paramètres, tels que les abondances et les tendances à court et à long terme, sont intégrés pour attribuer l'état des UC dans le cadre d'un processus dirigé par des experts [@holtIndicatorsStatusBenchmarks2009; @dfoWildSalmonPolicy2015; @dfoIntegratedBiologicalStatus2016; @grant2017FraserSockeye2020]. En règle générale, nous suggérons que le terme « récent » signifie la génération la plus récente, bien que des perturbations majeures telles que des glissements de terrain puissent rendre les évaluations récentes non représentatives de l'état actuel. <!--CH remove: Over time-periods longer than a generation, the extent to which the assessment is still representative depends on the dynamics of the specific system.-->

Étant donné que les évaluations officielles de l'état selon la PSS, qui sont examinées par les pairs, sont des processus qui exigent beaucoup de ressources, notamment de grands groupes d'experts pendant plusieurs jours [@grantIntegratedBiologicalStatus2013], et qu'elles ne sont pas disponibles pour la plupart des UC, nous démontrons l'application d'un outil pour déterminer rapidement l'état: l'explorateur de l'état du saumon du Pacifique (Pestal et al. en révision). Dans ce cadre multidimensionnel, l'état des UC dépend de divers paramètres de population, où le choix des paramètres dépend de la disponibilité des données et peut différer entre les UC au sein d'une UGS. L'explorateur des saumons intègre l'état des mesures disponibles pour obtenir un état global comparable entre les UC. <!--CH: the following 2 lines give a line break before the next heading-->
\
&nbsp;

**État des UGS dont les UC manquent de données**

Les PRL basés sur l'état des UC sont considérés comme dépassés lorsqu'au moins une UC a un état rouge, que l'état des UC pauvres en données puisse être déduit ou non des UC riches en données (tableau \@ref(tab:GuidanceDDCUs), colonne de droite). Une seule UC avec un état rouge peut déclencher un plan de rétablissement en vertu des dispositions relatives aux stocks de poissons, étant donné que l'amélioration de la surveillance des UC dont les données sont insuffisantes n'entraînera pas à elle seule une augmentation de l'état de l'UGS à 100 % (c.-à-d. toutes les UC au-dessus de l'état rouge). Une surveillance plus poussée des UC manquant de données est encore justifiée dans ce cas pour éclairer l'état des composantes restantes de l'UGS et des efforts de rétablissement connexes.

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp;

**État provisoire de l'UGS**

Lorsque des UC dont les données sont insuffisantes sont représentées par des UC disposant de données, nous qualifions l'état résultant de « provisoire » si toutes les UC incluses dans l'évaluation sont supérieures à l'état rouge (tableau \@ref(tab:GuidanceDDCUs)). Cet état présente une plus grande incertitude et est donc considéré comme provisoire jusqu'à ce que toutes les UC qui le composent puissent être évaluées directement. Dans certains cas, la variabilité naturelle seule peut faire en sorte que des UC non évaluées aient un état rouge, même si les critères énumérés pour la représentativité des UC à l'étape 3 sont respectés.

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp;

**État de l'UGS manquant de données**

En revanche, lorsque les UC dont les données sont insuffisantes ne sont pas représentées par des UC comportant des données (c'est-à-dire que les critères de l'étape 3 ne sont pas respectés) et que toutes les UC incluses dans l'évaluation ont un état supérieur à rouge, l'UGS est considérée comme manquant de données et son état ne peut être évalué. Dans ce cas, nous recommandons d'améliorer la surveillance et l'évaluation pour combler les lacunes de l'évaluation au niveau des UC.


\renewcommand*{\arraystretch}{1.6}
\begin{longtable}[]{p{5cm} p{3.5cm} p{3.5cm}}
\caption{Lignes directrices sur l’évaluation de l’état pour les PRL fondés sur l’état des UC correspondant à 100\% des UC étant au-dessus de l’état rouge, lorsqu’au moins une UC est dépourvue de données.}\\
\hline
& État des UC riches en données : tous les états supérieurs à rouge & État des UC riches en données : au moins un état rouge\\ 
\hline
\endhead
L’état des UC manquant de données peut être déduit de celui des UC riches en données & État provisoire de l’UGS au-dessus du PRL avec une grande incertitude & État de l’UGS = inférieur au PRL\\
L’état des UC manquant de données {\it ne peut pas} être déduit des UC riches en données & État de l’UGS = données insuffisantes & État de l’UGS = inférieur au PRL\\

\hline
(\#tab:GuidanceDDCUs)
\end{longtable}


<!--
+--------------------------+-------------------------+-------------------------+
|                          | Status of data-rich CUs:| Status of data-rich CUs:                         
|                          | all above red status    | at least one red status 
+==========================+=========================+=========================+
| Status of data-deficient | Interim SMU status=     | SMU Status = below LRP  
| CUs can be inferred from | above LRP               |                         
| data-rich CUs            |                         |                         
+--------------------------+-------------------------+-------------------------+
| Status of data-deficient | SMU status = data-      | SMU Status = below LRP  
| CUs cannot be inferred   | deficient               |                         
| from data-rich CUs       |                         |                         
+--------------------------+-------------------------+-------------------------+


Table: (\#tab:GuidanceDDCUs2) Guidelines on assessing status for CU status-based LRPs of 100\% of CUs being above red status, when at least one CU is data-deficient. 

-->


<!--CW: From the PA Policy:

"In resource management, the PA is, in general, about being cautious when scientific information is uncertain, unreliable or inadequate and not using the absence of adequate scientific information as a reason to postpone or fail to take action to avoid serious harm to the resource."
But also:
"In data deficient cases, priority should go to monitoring the stock and establishing data time series to support the identification of an LRP. When developing reference points efforts should be made to take into consideration the range of factors which may affect the productivity of the stock including changes in ocean conditions, where information is available."

The PA policy also suggests that when a stock is DD, a meta analysis approach should be used to set LRPs (see annex 1b). 

This may be a bit out there but: maybe we could suggest the establishment of a data collection plan that would be analogous to the recovery plan but to address data deficiency. -This plan would include a list of data that could be collected (e.g. monitoring of spawning grounds, establishment of genetic markers, catch sampling, ageing, etc.) and potential costs associated with everything? -- Also this plan could clearly indicate if spawning grounds are too remote, inaccessible, or too costly to monitor. -- I think that having that kind of information documented would go a long way in establishing priorities. 

LW: I agree, that would be useful!
-->

### Étape 6: Examen par les pairs de l'état relatif au PRL fondé sur l'état des UC

Nous recommandons une révision par les pairs des données et des évaluations des UC utilisées dans les étapes 1 (compilation des données), 2 (évaluation des lacunes dans les données des UC) et 5 (évaluation de l'état par rapport au PRL basé sur l'état des UC) si l'évaluation des UC est élaborée en dehors d'un processus existant publié et révisé par les pairs. De plus, nous recommandons un examen par les pairs des décisions sur l'agrégation à l'échelle de l'UGS à partir des étapes 3 (représentation des UC manquant de données) et 4 (proportion des UC requises pour être au-dessus de l'état rouge). <!--KH: note that I added descriptions in brackets after each step as a refresher. Is this ok? -->Cet examen par les pairs peut se faire, du moins en partie, grâce à la mise en œuvre annuelle de l'explorateur de l'état du saumon du Pacifique du programme sur l'état du saumon du ministère des Pêches et des Océans (MPO). L'explorateur des saumons sera appliqué annuellement dans le cadre d'un processus intégrant les résultats avec l'expertise locale pour fournir des états pour les UC. Un examen par des experts est nécessaire pour vérifier les états obtenus par l'application de l'explorateur des saumons afin de s'assurer qu'ils sont cohérents avec les catégories biologiques sous-jacentes, compte tenu des dimensions multiples et parfois contradictoires de l'état. <!--CH: Ann-Marie suggested an example from Fraser Sockeye Shuswap here, but I wonder if it might make the flow of this section awkward? Happy to consider an inclusion from Ann-Marie-->Les résultats de ce processus peuvent servir de base à l'élaboration d'états au niveau des UC pour éclairer les PRL au niveau de l'UGS. Nous soulignons l'importance d'un examen documenté par les pairs des PRL et des évaluations de l'état de l'UGS prescrites par la réglementation, soit dans le cadre de l'application annuelle de l'explorateur des saumons, soit dans le cadre d'un processus distinct d'examen par les pairs propre aux UGS. L'examen par les pairs peut être documenté, par exemple, dans un document de recherche du Secrétariat canadien des avis scientifiques (SCAS), une réponse des Sciences du SCAS et/ou un avis scientifique du SCAS.<!--CH question: Is this requirement for CSAS documentation okay? We should ask Julie/Jason to what extent this is consistent without marine species, and then mention the consistency here. Some TWG participants suggested LRP identification could occur in the rebuilding plan, but this seems awkward as rebuilding objectives may be related to LRPs, or at least they will in other species, so best to keep the 2 processes separate I think.
CW: Agree with keeping rebuilding plan and LRP separate. 
LW: I agree as well.-->

<!--SG comment: if status is approximated with the algorithm and the status on the metric is red, this could trigger an integrated status assessment to derive a formal WSP status prior to triggering LRP. -->

La fréquence des examens par les pairs à l'échelle de l'UGS en dehors de la mise en œuvre annuelle de l'explorateur des saumons dépendra de la variabilité de la dynamique de la population au niveau des UC au fil du temps et de la façon dont les PRL et les évaluations au niveau de l'UGS sont utilisés pour éclairer la prise de décisions (par exemple, si une UGS est classée par lots en vertu de la *Loi sur les pêches*), entre autres facteurs. À l'avenir, les procédures de gestion avec diverses fréquences d'évaluation pourraient être évaluées dans un cadre de simulation afin de déterminer les risques de retarder les évaluations par rapport aux coûts de leur mise en œuvre.

### Étape 7: Les PRL fondés sur l'abondance globale sont-ils nécessaires pour la gestion des pêches?

Bien que les PRL fondés sur l'état des UC puissent répondre aux exigences des dispositions sur les stocks de poissons pour le saumon du Pacifique, les PRL fondés sur l'abondance peuvent être nécessaires pour les décisions de gestion des pêches (section \@ref(roleLRPs)). Pour les UGS où la récolte à l'échelle globale est un facteur dominant de la dynamique de la population et où la restriction des prises dans les pêches est un levier de gestion principal, un PRL selon la mesure de l'abondance au niveau de l'UGS peut soutenir une gestion de précaution. Par exemple, lorsque les PRL sont utilisés pour éclairer une règle de contrôle des prises, la pression de pêche peut être progressivement réduite à mesure que les abondances globales diminuent vers le PRL afin d'éviter l'épuisement en dessous de ce niveau. Des points de référence fondés sur l'abondance globale peuvent dans certains cas être nécessaires pour la gestion locale ou internationale. Par exemple, des objectifs d'échappées globales sont requis pour le saumon rouge des rivières Nass et Skeena en vertu des dispositions du Traité sur le saumon du Pacifique (2019)<!--@TreatyGovernmentCanada2019. Have to figure out how to reference this without having the full name of the treaty here-->, bien que pour se conformer aux objectifs de la PSS, l'objectif d'échappées globales doive tenir compte de la diversité au niveau des UC.

Cependant, lorsque les PRL sont définis dans le contexte d'un cadre de procédure de gestion (section \@ref(roleLRPs)), un PRL fondé sur l'abondance globale peut ne pas être nécessaire si le cadre peut démontrer la probabilité que des UC individuelles aient un état supérieur à rouge pour diverses options de gestion. Pour le saumon du Pacifique, les procédures de gestion peuvent aller au-delà des règles de contrôle des prises et inclure des fermetures spatio-temporelles, des restrictions sur les engins de pêche, la mise en valeur de l'habitat ou les apports d'écloserie pour protéger les UC individuelles. Par conséquent, le choix d'élaborer un PRL d'abondance globale dépend du contexte décisionnel et devrait être fait en collaboration avec les divers secteurs et les Premières Nations responsables des décisions de gestion qui touchent l'UGS. Si les PRL fondé sur l'abondance globale ne sont pas nécessaires, l'évaluation de l'UGS se fera par les étapes 1 à 6. Les étapes suivantes (8-9) sont pertinentes si des PRL fondés sur l'abondance globale sont requis, et s'appuient sur les PRL basés sur l'état des UC dérivés dans les étapes précédentes. Les incertitudes introduites par l'inclusion de modèles pour relier les abondances globales aux états au niveau des UC doivent être prises en compte lors du choix des méthodes d'établissement du PRL (principe 5 de la section \@ref(principles)).

Dans le contexte décrit ici, les PRL fondés sur l'abondance globale sont des quantités dérivées scientifiquement qui délimitent un dommage grave pour une UGS en suivant les principes décrits dans la section \@ref(principles). En particulier, les PRL fondés sur l'abondance globale sont définis de manière à être cohérents avec l'objectif de la PSS de maintenir la biodiversité à l'échelle des UC. Bien que ces PRL puissent éclairer les règles de contrôle des prises, les décisions de gestion des pêches nécessitent la prise en compte de multiples objectifs au-delà de ceux associés à la conservation et aux dommages graves (par exemple, des objectifs socio-économiques).

### Étape 8: Estimation des PRL fondés sur l'abondance globale

**Quelle est la probabilité acceptable que les états des UC soient au-dessus du rouge?**

Pour définir les PRL fondés sur l'abondance globale, il faut d'abord déterminer une probabilité acceptable que tous les états des UC composantes soient au-dessus de rouge. Bien qu'une probabilité de 100 % ou de presque 100 % que toutes les UC composantes soient au-dessus du rouge puisse être souhaitable du point de vue de la conservation, les incertitudes inhérentes à la dynamique des populations rendent ce choix peu pratique. Souvent, des PRL supérieurs aux plus fortes abondances globales de géniteurs observées sont nécessaires pour obtenir une probabilité proche de 100 % que les composantes soient au-dessus de l'état rouge. Au lieu de cela, nous recommandons d'appliquer une probabilité d'au moins 50 % que toutes les UC dépassent l'état rouge pour s'harmoniser avec les objectifs de la PSS. Comme il est indiqué dans la section \@ref(est-methods), nous fournissons des PRL associés à une gamme de probabilités, 50 %, 66 %, 90 % et 99 % (lorsque cela est possible sur le plan analytique), dérivées des catégories de probabilités utilisées par le Groupe international d'experts sur l'évolution du climat [tableau \@ref(tab:LikelihoodsIPCC), @mastrandreaGuidanceNoteLead2010], au lieu de mentionner une seule probabilité. Nous distinguons *la probabilité que toutes les UC* soient au-dessus du rouge de *la proportion d'UC* au-dessus du rouge (indiquée comme 100 % à l'étape 4). Les PRL fondés sur l'état des UC et l'abondance globale sont fixés à des niveaux où toutes les UC sont au-dessus de l'état rouge, mais les PRL d'abondance globale attribuent une probabilité à cette occurrence.


<!--CH omit entire pgh after considering KH's comment about repetition with above pgh:
In our case studies, we provide aggregate abundance LRPs for the four probability thresholds described above, and focus sensitivity analyses on a 50% probability of all component CUs having status above Red. This approach to delineating serious harm could be considered risk neutral, where risks can be accounted for directly and explicitly in harvest control rules that consider trade-offs among multiple objectives.    
-->

<!-- from ch 6. Does this belonw here? reword?-->

<!--KH: I found the second half of the paragraph below (starting with "Alternatively ....") difficult to follow.  I understand the point being made, but I think it will be lost of most readers.  I wonder if this section could come out entirely? I feel like this type of work is a long way off, and mentioning it as part of this step 8 will just complicate things (i.e., we're telling people to choose a probablity for estimating an aggrgegate abundance LRP at this step, but then telling them that using CU status-based LRPs in a MSE may be better). If we do keep this text, it would benefit from some re-wording to make sentences shorter. Alternatively - maybe it could be put in the roles of LRP section??? -->

Bien que le cadre de l'approche de précaution du MPO (2009) stipule que les PRL en vertu des dispositions sur les stocks de poissons soient établis par les Sciences, nous n'avons pas été en mesure d'établir un niveau de probabilité précis pour que toutes les UC soient au-dessus de l'état rouge qui s'harmonise avec les principes scientifiques. Bien qu'il soit possible de sélectionner un niveau de probabilité basé sur le schéma de catégorisation des probabilités du Groupe d'experts intergouvernemental sur l'évolution du climat (GIEC) (par exemple, plus probable qu'improbable, probable, très probable, pratiquement certain), des conseils supplémentaires sur le choix entre ces options sont nécessaires. <!--Alternatively, CU status-based LRPs can be used as the basis for serious harm instead of identifying a specific probability for aggregate abundance LRPs, where biological objectives for SMUs can be derived from the probability of achieving those CU status-based LRPs over a specified time frame to inform the performance of various candidate management procedures. The probability and time frame required within the objective are identified with managers, First Nations, and stakeholders. When used as part of Management Procedure Framework [e.g.,  @dfoManagementProcedureFramework2021] or management strategy evaluation (MSE), the performance of a variety of management procedures can be evaluated against objectives, where management procedures can extend beyond aggregate abundance-based harvest control rules to include time-area closures, habitat enhancement or hatchery supplementation. Therefore, CU status-based LRPs may be preferred as the biological basis of serious harm to clearly distinguish the biologically derived component from desired probability which requires input from managers, First Nations and stakeholders.-->

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp;

**Choisir parmi les PRL fondés sur l'abondance globale**

Des lignes directrices pour choisir parmi deux types de PRL fondés sur l'abondance globale sont décrites ici: le PRL de régression logistique et le PRL de projection. Ces méthodes utilisent des données historiques ou projetées, respectivement, pour déterminer la relation entre les abondances globales et la probabilité que toutes les UC soient au-dessus de l'état rouge. Les directives présentées à cette étape sont fondées sur les hypothèses distinctes requises pour chaque méthode. Si les hypothèses ne sont pas satisfaites pour l'une ou l'autre des méthodes, il se peut qu'il ne soit pas possible d'élaborer des PRL fondés sur l'abondance globale conformes à la PSS pour l'UGS. <!--However, developing and evaluating management procedures that account for CU-level status is still prudent even in the absence of aggregate abundance LRPs (Section @ref(recommendations)).-->

Les deux méthodes reposent sur l'hypothèse d'une covariation positive de la dynamique de la population entre les UC composantes. Si cette hypothèse est respectée, alors lorsqu'une UC a un état épuisé et fournit relativement peu de géniteurs à l'ensemble, il est probable que d'autres UC composantes auront également un état épuisé fournissant peu de géniteurs à l'ensemble. De même, si une UC est considérée comme saine et contribue à de nombreux géniteurs, les autres UC sont plus susceptibles d'être saines.

Compte tenu de l'éventail des incertitudes et des limites associées à chaque méthode, il peut être prudent d'appliquer et de comparer les deux méthodes au lieu de limiter les analyses à une seule approche (voir l'étape 9).

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp; 

**PRL de régression logistique**

Les PRL fondés sur la régression logistique empirique sont dérivés de séries chronologiques historiques de la proportion d'UC au-dessus de l'état rouge, indiqué par un seul paramètre sur l'abondance ou la répartition des géniteurs.

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp; 

Les PRL de régression logistique peuvent être appropriés lorsque les hypothèses suivantes sont respectées:

-   Les évaluations des UC sont dérivées principalement des abondances par rapport aux points de référence ou de la répartition des géniteurs au lieu des tendances temporelles, ou l'état sur les abondances de géniteurs par rapport aux points de référence est considéré comme une approximation convenable. Il est possible de combiner deux ou plusieurs types de points de référence basés sur l'abondance pour évaluer les UC au sein d'une UGS (par exemple, utiliser à la fois les points de référence fondés sur le centile et G~gén~ pour évaluer différentes UC).

-   Comme il est requis pour les PRL fondés sur l'état des UC, les UC manquant de données répondent aux critères décrits à l'étape 3 de sorte que leur état puisse être représenté par des UC avec des données.

-   Les séries chronologiques de la proportion d'UC au-dessus du point de référence inférieur contiennent un contraste tel que toutes les UC sont au-dessus de leur point de référence inférieur pendant au moins une année et qu'au moins une UC est en dessous de son point de référence inférieur pendant au moins une année. <!--CW: I suspect we would not get the model to converge if there was only one year with one of the outcomes, could we change it to a few:
     Time-series of the proportion of CUs above the lower benchmark contain contrast such that all CUs are above their lower benchmark in a few years and at least 1 CU is below its lower benchmark in a few years.
     
    CH: you're probably right, but I'm unsure how much a few is, and wonder if some (possibly rare) case having one year might work..?
    -   -->

-   Il existe une relation positive statistiquement significative entre les abondances globales et les probabilités logarithmiques que toutes les UC composantes soient supérieures à leur point de référence inférieur sans valeurs aberrantes influentes, comme le confirment les diagnostics du modèle décrits dans @holtCaseStudyApplicationsInpress. Cette relation tend à être significative et positive lorsque les corrélations par paires dans les abondances de géniteurs entre les UC sont fortes et positives. Par exemple, pour notre étude de cas sur le saumon coho du Fraser intérieur, les diagnostics de qualité de l'ajustement ont indiqué une relation significative entre les abondances globales et les probabilités logarithmiques de toutes les UC composantes qui étaient supérieures à leurs points de référence inférieurs (p\<0,01) et les corrélations moyennes par paires de géniteurs parmi les UC étaient relativement élevées, soit 0,56. En revanche, pour notre étude de cas sur le saumon kéta de l'intérieur de la côte sud, *Oncorhynchus keta*, le même diagnostic de qualité de l'ajustement n'était pas statistiquement significatif (p=0,13) et les corrélations moyennes par paire de géniteurs étaient relativement faibles, 0,12.

-   Les résidus de l'ajustement du modèle de régression logistique sont indépendants (c'est-à-dire qu'ils ne sont pas autocorrélés dans le temps). <!--CH: “Or if autocorrelation is present in residuals, it is accounted for in the model with an AR(1) term.”  Don’t think we need it though  KH: agree - not needed.-->

-   Les facteurs environnementaux et les menaces qui pèsent sur les UC sont restés stables au cours des séries chronologiques disponibles, ou ont changé de la même manière dans les UC, de sorte que la covariance dans la dynamique des populations entre les UC est susceptible d'être restée stable au fil du temps. Par conséquent, la relation entre les abondances globales et les probabilités logarithmiques que toutes les UC soient supérieures aux points de référence inférieurs est également susceptible d'être restée stable.

-   La dynamique de la population au niveau de l'UC ne subit pas de changements directionnels entraînant des déclins ou des augmentations des paramètres dynamiques de la population et des points de référence connexes.

Dans les analyses préliminaires pour l'étude de cas du saumon coho du Fraser intérieur, nous avons considéré l'état des UC basé sur l'état multidimensionnel de l'explorateur des saumons, mais nous avons choisi de nous concentrer sur l'approche à paramètre unique pour plusieurs raisons. Premièrement, l'explorateur des saumons inclut l'état sur des données d'abondance lissées (moyenne géométrique générationnelle courante) par rapport à des points de référence basés sur l'abondance, et donc l'état d'une année dépend de l'état de l'année précédente. L'autocorrélation vient à l'encontre de l'hypothèse d'indépendance des observations requise dans la régression logistique. Bien que les régressions logistiques puissent être révisées pour tenir compte des résidus autocorrélés, lorsque l'autocorrélation est détectée, les degrés de liberté disponibles sont souvent insuffisants étant donné les séries temporelles relativement courtes des évaluations des UC. <!--CH remove: "and changes in environmental conditions which sometimes precludes including older data."--> <!--CH: also sometimes skew in data points towards most years with all CUs above lower benchmarks which limits power of LR-->In addition, the Salmon Scanner includes metrics on short- and long-term trends in spawner abundances which are less directly related to, and may be completely unrelated to, aggregate abundances. For CUs that rely on time trends for status assessments, aggregate abundance-based metrics are likely not appropriate (see below). <!--CH remove: "However, future analyses could explore the possibility of including CU statuses derived from the Salmon Scanner that rely primarily on abundance-based benchmarks with alternative logistic regression model forms that include autocorrelation.-->

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp; 

Les PRL fondés sur des régressions logistiques peuvent ne pas être appropriés lorsque:

-   Les évaluations des UC sont dérivées des tendances de l'abondance des géniteurs au fil du temps (par exemple, dans le cadre de l'explorateur des saumons), et non des points de référence basés sur l'abondance.

-   Les UC dont les données sont insuffisantes ne répondent pas aux critères décrits à l'étape 3, de sorte que leur état ne peut être représenté par des UC disposant de données.

-   Les séries chronologiques de la proportion d'UC au-dessus de leurs points de référence inférieurs manquent de contraste (c'est-à-dire qu'elles sont égales à 100 % pour toutes les années, ou inférieures à 100 % pour toutes les années).

-   La relation entre les abondances globales et les probabilités logarithmiques que toutes les UC composantes soient supérieures à leur point de référence inférieur n'est pas statistiquement significative ou contient des valeurs aberrantes influentes. En d'autres termes, les diagnostics du modèle ne soutiennent pas l'utilisation de la régression logistique.

-   Les résidus de l'ajustement du modèle de régression logistique sont autocorrélés dans le temps, de sorte que l'état d'une année dépend de l'état de l'année précédente.

-   Les menaces et/ou les facteurs environnementaux ont changé de telle sorte que les points de référence au niveau des UC estimés à partir de données historiques ne sont plus significatifs, et il n'y a aucune attente que ces changements reviennent naturellement à leur état antérieur, ou soient réalisables par la gestion. Ou bien, les facteurs environnementaux et les menaces qui pèsent sur les UC ont changé au cours de la série chronologique disponible, de sorte que la covariance de la dynamique des populations entre les UC est susceptible d'avoir changé.

-   Il n'y a qu'une UC dans l'UGS. Dans ce cas, l'état de l'UC représente l'état de l'UGS.


<!--CH Tentative exclusion b/c may be implied by stepwise order, but happy to add back in:
- Current CU-level assessments are not available. Aggregate-abundance LRPs are intended to supplement CU status-based LRPs and not replace them. In this case, there may be risk of loss of CU-level biodiversity due to infrequent extreme events not captured in the model.

CW: Agree with the exclusion, otherwise we would also have to point out that aggregate abundance methods may not be appropriate when one or more CU's are missing data. -->

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp;

**PRL de projection**

Les PRL fondés sur la projection sont dérivés des projections de la dynamique de la population au niveau des UC et des séries temporelles associées des UC au-dessus de l'état rouge comme indiqué par un seul paramètre, l'abondance des géniteurs par rapport à un point de référence inférieur. L'état des UC dérivé des évaluations multidimensionnelles dans le cadre de l'explorateur des saumons n'a pas été pris en compte pour les PRL de projection parce que le modèle de projection indique des abondances globales d'équilibre à long terme associées à des probabilités indiquées d'UC de composantes supérieures aux points de référence inférieurs, et n'est pas structuré pour refléter les tendances temporelles. Les tendances temporelles peuvent être évaluées dans des modèles de simulation qui évaluent les répercussions des procédures de gestion sur la dynamique des populations à partir de l'état actuel, comme dans les évaluations de la stratégie de gestion (ESG).

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp;

Les PRL de projection peuvent être inappropriés lorsque:

-   Des modèles d'évaluation des stocks propres aux UC ont été élaborés, y compris la paramétrisation des modèles géniteur-recrutement et la covariance des résidus de recrutement entre les UC. Ces modèles et leurs paramètres tiennent compte des contributions des écloseries lorsque les populations sont influencées par celles-ci, sont examinés par des pairs et représentent la dynamique actuelle des géniteurs naturels et du recrutement. <!--KH: The above suggests that a peer-review of SR models is required, however, the next bullet goes in to say that it is not. Perhaps just remove the mention of peer-review in the first bullet? In general, any application of projection LRPs will need to go through peer-review, so having previously peer-reviewed models is not needed  -->

-   Lorsque des paramètres de dynamique des populations évalués par des pairs ne sont pas disponibles ou ne sont plus d'actualité, des limites plausibles peuvent être placées sur des paramètres incertains (par exemple, la productivité et la capacité), y compris ceux qui peuvent avoir changé au cours de la série chronologique pour représenter une meilleure estimation des conditions actuelles. Ces limites peuvent être dérivées d'UC voisines, de méta-analyses ou d'avis d'experts.

-   Ces paramètres propres aux UC sont disponibles pour les UC représentatives au sein de l'UGS (telles qu'indiquées à l'étape 3).


<!--CH: extra text I don't think is needed (but this point can be highlighted in Case Study paper): 
For example, if there is a high probability that any one CU will be below the lower benchmark in a given year due to asynchronous dynamics, there is also a high probability that aggregate abundances are below the aggregate abundance LRP.  In contrast, when correlations in population dynamics and status assessments are relatively high among CUs, aggregate abundance LRPs tend to be lower. -->

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp; 

Les PRL de projection peuvent être inappropriés lorsque:

-   Les paramètres de la dynamique de la population ne peuvent pas être estimés, et/ou les plages plausibles ne sont pas connues.

-   Les PRL de projection sont utilisés pour évaluer l'état sous une nouvelle procédure de gestion qui n'est pas prise en compte dans le modèle de projection. Les PRL de projection dépendent de la procédure de gestion précise appliquée dans les projections, mise en œuvre comme une stratégie d'exploitation constante pour nos études de cas. Cependant, les analyses de sensibilité des PRL de projection à divers taux d'exploitation ou procédures de gestion peuvent démontrer les abondances globales requises pour maintenir les UC au-dessus de leurs points de référence inférieurs dans divers scénarios de gestion possibles, et la sensibilité du choix de gestion au PRL d'abondance globale.

-   Il n'y a qu'une UC dans l'UGS. Dans ce cas, l'état de l'UC équivaut à l'état de l'UGS.


<!--CH: this bullet was tentatively removed from logistic regression LRP, so removing here:

- Current CU-level assessments are not available. Aggregate-abundance LRPs are intended to supplement CU status-based LRPs and not replace them. There may be risk of loss of CU-level biodiversity when relying on projection LRPs alone due to unforeseen processes (e.g., infrequent extreme events) not captured in the projection model that are reflected in current CU statuses. 
-->

De plus, les PRL de projection peuvent être plus appropriés lorsque les corrélations par paires dans les abondances de géniteurs entre les UC sont positives et fortes, mais ce n'est pas une exigence. Il est possible d'estimer les PRL de projection pour une UGS avec des UC composantes qui varient indépendamment. Cependant, lorsque les corrélations entre les UC sont faibles, l'abondance globale du PRL sera élevée, car il y a une plus grande probabilité qu'une UC ait l'état rouge. Dans ces cas, les PRL basés sur l'état des UC et les règles de contrôle des prises qui gèrent les UC de manière indépendante peuvent être plus appropriés. <!--CH omit? : When used to inform operational control points, very high aggregate abundance LRPs may conflict with harvest or other socioeconomic objectives.--> Bien que des PRL plus élevés dans le cadre d'une dynamique asynchrone puissent initialement être contre-intuitifs en raison de la stabilité que l'asynchronisme confère aux séries chronologiques agrégées [@schindlerPopulationDiversityPortfolio2010a], les trajectoires indépendantes entre les composantes augmentent les risques que les UC composantes individuelles tombent en dessous des points de référence inférieurs dans les pêches à UC mixtes, ce qui nécessite des PRL plus élevés.

<!--KH: Next paragraph added as a revision after CSAS meeting -->

L'évaluation du modèle pour le PRL de projection est plus subjective que pour le PRL de régression logistique. La pertinence des ajustements du modèle de régression logistique peut être évaluée à l'aide de diagnostics statistiques d'ajustement du modèle, ce qui rend le processus d'évaluation relativement objectif et reproductible. Cependant, l'ajout d'hypothèses et de décisions analytiques nécessaires pour paramétrer les modèles de projection est un processus plus subjectif dans lequel les résultats peuvent varier d'un analyste à l'autre. L'examen par les pairs, tel que décrit à l'étape 6 ci-dessus, sera nécessaire pour soutenir l'élaboration des PRL de projection.

### Étape 9: Appliquer les PRL fondés sur l'abondance globale pour obtenir l'état au niveau de l'UGS et comparer cet état avec les PRL fondés sur l'état des UC.

Les méthodes d'abondance globale sont ensuite appliquées pour calculer les PRL selon les orientations ci-dessus. Voir l'annexe \@ref(app:case-studies) et @holtCaseStudyApplicationsInpress pour des exemples d'applications. Lorsque l'état d'une UGS est déduit des PRL de l'abondance globale en utilisant un sous-ensemble d'UC considérées comme représentatives des UC restantes dont les données sont insuffisantes, l'état résultant doit être considéré comme « provisoire » (c'est-à-dire avec une incertitude accrue) jusqu'à ce que l'état de toutes les UC composantes puisse être évalué. Lorsque l'état des UC dont les données sont insuffisantes ne peut pas être déduit des UC riches en données, l'état ne peut pas être évalué avec des PRL fondés sur l'abondance globale.

Nous utilisons la moyenne générationnelle de l'abondance des géniteurs comme base pour déterminer si l'UGS est au-dessus ou au-dessous de son PRL. Une moyenne générationnelle intègre l'état des cohortes au sein d'une génération, qui sont généralement indépendantes les unes des autres en raison du cycle biologique anadrome et sémelpare du saumon du Pacifique et de la prédominance d'un seul âge à la maturité pour de nombreux stocks [@holtIndicatorsStatusBenchmarks2009; @porsztReliabilityIndicatorsDecline2012]. En conséquence, le lissage générationnel réduit le bruit dans la détermination annuelle de l'état des UC provenant à la fois de la variabilité interannuelle des abondances des UC de différentes cohortes et de l'erreur d'observation annuelle dans les abondances estimées des géniteurs. Cela rend également notre détermination de l'état du PRL conforme à l'approche adoptée pour les points de référence basés sur l'abondance dans les évaluations publiées de la PSS [par exemple, @grant2017FraserSockeye2020] et l'explorateur des saumons au niveau de l'UC. De plus, nous recommandons que l'état de l'UGS soit évalué environ à chaque génération de saumon afin de s'harmoniser avec les directives pour les évaluations de l'UC générationnelle dans le cadre de la PSS [@grantIntegratedBiologicalStatus2013; @grant2017FraserSockeye2020].

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp; 

**Comparer les PRL fondés sur l'abondance globale**

L'utilisation de plusieurs approches analytiques pour définir les PRL est conforme au principe d'utiliser les meilleures informations disponibles si les preuves pour soutenir une méthode plutôt qu'une autre font défaut. Les états qui convergent d'une méthode à l'autre fournissent un poids de la preuve plus fort que le PRL choisi représente un niveau au-dessus duquel un dommage grave peut se produire. Bien que les PRL qui convergent puissent être basés sur des hypothèses qui sont incorrectes par coïncidence, le principe du rasoir d'Occam soutient les explications avec moins d'exceptions. Lorsque les PRL divergent, les hypothèses sous-jacentes à l'origine de ces divergences doivent être explorées et réexaminées. <!--CH repeated above: We suggest comparing aggregate abundance LRPs to current generational (geometric) average spawner abundances instead of annual abundances to integrate across independent cohorts within a generation when deriving SMU status. This approach is consistent with methods used in formal WSP assessments of CUs [e.g., @grant2017FraserSockeye2020]. -->

<!--CH: the following 2 lines give a line break before the next heading-->

\
&nbsp;

**Comparer l'état des PRL fondés sur l'abondance globale à celui des PRL fondés sur l'état des UC.**

Dans cette étape, nous recommandons de comparer l'état obtenu à partir des PRL fondés sur l'abondance globale à celui obtenu à partir des PRL fondés sur l'état des UC indiqués à l'étape 5. Alors que le PRL fondé sur l'abondance globale exploite la covariation observée dans la dynamique de la population entre les UC composantes, plusieurs facteurs peuvent entraîner une rupture de cette relation (p. ex. erreurs d'observation, variation temporelle de la covariation et/ou événements extrêmes peu fréquents). Par conséquent, les états provenant des PRL fondés sur l'abondance globale peuvent différer de ceux basés sur les PRL fondés sur l'état des UC. Nous recommandons que les PRL fondés sur l'état des UC soient les PRL par défaut pour mettre en œuvre les dispositions relatives aux stocks de poissons, avec des PRL fondés sur l'abondance globale en complément lorsque cela est nécessaire pour la gestion de la récolte.


<!-- CW: Can we say how often these comparisons should happen? 
Is it realistic to suggest that comparisons will be done every year? Or would these comparisons be done every X years?
CH: We had recommended generationally (~4yrs) for WSP assessments, but this is really a resource-availability vs management-need question that is specific to species and stock.
 -->


<!-- CW: Could the sections below be moved to another chapter? I think it would be good to have the steps as their own chapter to reflect their importance
Maybe "Time-varying parameters and impacts on LRPs"  could go under chapter 5 (after editing to be more recommendation based?)
and " Consistency with National Guidance on LRPs" can go under Chapter 2?
I moved the sections to the chapters listed above.
 -->
