# DISCUSSION {#recommendations}

## PRINCIPALES INCERTITUDES AYANT UNE INCIDENCE SUR LES ESTIMATIONS DES POINTS DE RÉFÉRENCE LIMITES (PRL)

```{=tex}
\begin{tcolorbox}[standard jigsaw,opacityback=0.8,colframe=black,boxrule=0.7pt,left=0.1in, sharp corners]
\subsection*{Principaux points:}
\begin{itemize} 
\item Les incertitudes dans les \textbf{points de référence au niveau de l’unité de conservation (UC)} touchent à la fois les PRL fondés sur l’état des UC et l’abondance globale, et peuvent survenir en raison des éléments suivants:
\begin{itemize} 
\item des erreurs d’observation dans les données sous-jacentes, par exemple, liées à l’incertitude entourant la contribution des poissons d’écloserie aux géniteurs;
\item l’incertitude de l’estimation des points de référence découlant de l’ajustement du modèle statistique et des paramètres variant dans le temps;
\item les incertitudes structurelles dans les modèles.
\end{itemize}
\item Des incertitudes peuvent également apparaître dans les \textbf{états des UC} en raison du choix des paramètres utilisés (unidimensionnels ou multidimensionnels). Pour les deux PRL d’abondance globale, des incertitudes peuvent survenir parce que l’état au niveau des UC n’est fondé que sur un seul paramètre comme approximation de l’état sur de multiples dimensions. 
\item La répartition des géniteurs parmi les populations au sein d’une UC peut être importante pour la viabilité de l’UC et de l’unité de gestion des stocks (UGS), et ignorer ou mal identifier cette structure de stock peut augmenter l’incertitude de l’état évalué.
\item Des incertitudes dans tous les PRL potentiels peuvent découler de l’exclusion des UC limitées en données des analyses lorsque ces UC sont mal représentées par les UC riches en données qui sont incluses. Nous recommandons la prudence lors de l’application de PRL qui n’incluent pas toutes les UC.
\item Les incertitudes dans \textbf{les PRL de régression logistique} proviennent de l’estimation statistique des modèles de stock-recrutement et de régression logistique, ainsi que des changements dans les paramètres de la population et de la covariance entre les UC au fil du temps.
\item Les incertitudes dans les \textbf{PRL de projection} peuvent provenir d’une mauvaise spécification des modèles utilisés dans les projections.
\item Pour les PRL de projection, les incertitudes des paramètres sous-jacents et des points de référence au niveau des UC sont intégrées dans la probabilité que toutes les UC soient au-dessus de leurs points de référence inférieurs, et le PRL lui-même n’a pas d’incertitude d’estimation statistique. Les PRL de projection tiennent compte explicitement des incertitudes sous-jacentes dans les paramètres de la population, comme la productivité et la capacité au niveau des UC, la structure par âge, la covariance dans les écarts de recrutement et la variabilité dans la mise en œuvre des stratégies d’exploitation au fil du temps et entre les UC. 
\end{itemize}
\end{tcolorbox}
```
### Évaluations des UC

Les incertitudes dans les points de références au niveau de l'UC touchent à la fois les PRL fondés sur l'état des UC et sur l'abondance globale, et surviennent en raison d'erreurs d'observation dans les données sous-jacentes, d'incertitudes d'estimation dans les points de référence, et d'incertitudes structurelles dans les formes de modèles. Chacune de ces trois sources d'incertitude dans les points de référence est décrite ici.

Premièrement, les incertitudes des données peuvent provenir d'erreurs d'observation dans l'abondance des géniteurs, la proportion de géniteurs issus d'écloseries, les captures, l'affectation des captures aux stocks et l'âge à la maturité. Ces incertitudes ont une incidence sur les estimations du recrutement dans les « reconstitutions des remontes » et l'évaluation de l'état.

En particulier, l'incidence des écloseries sur les séries chronologiques des géniteurs et du recrutement est une incertitude clé en raison des faibles taux de marquage des saumons d'écloserie et d'échantillonnage dans les frayères. Même lorsque des données sur la proportion de poissons provenant d'écloseries sont disponibles et que les séries chronologiques d'abondance sont ajustées pour en tenir compte (comme dans l'étude de cas sur le saumon coho du Fraser intérieur), les impacts génétiques des écloseries peuvent se perpétuer sur plusieurs générations [@arakiCarryoverEffectCaptive2009; @christieReproductiveSuccessEarly2014], et sont difficiles à quantifier parce que les poissons de deuxième génération provenant d'écloseries ne sont pas marqués ou suivis. Il s'agit d'une source d'incertitude pour les populations touchées par les installations d'écloserie à l'intérieur du bassin (ou à l'intérieur de la population) ainsi que pour celles touchées par les poissons errants provenant de l'extérieur du bassin. Un marquage et une surveillance ciblés des frayères pour connaître les proportions de poissons marqués et des analyses génétiques pour déterminer l'introgression génétique à partir des animaux errants permettraient de lever ces incertitudes. De plus, pour les populations<!--LW: changed from stocks--> qui ne sont pas dominées par la production d'écloserie, la décision d'exclure la contribution des poissons d'écloserie des séries chronologiques d'abondance des géniteurs, lorsque cela est possible, suppose que ces poissons ne contribuent pas à l'évaluation et à la gestion du saumon sauvage qui en découle, comme dans les évaluations précédentes de la Politique concernant le saumon sauvage (PSS)[p. ex., @dfoWildSalmonPolicy2015], malgré leur contribution possible aux objectifs de conservation et de rétablissement, et aux services écosystémiques en général. L'examen et l'évaluation des objectifs pour les populations intégrées en transition et les populations intégrées sauvages (avec une influence naturelle proportionnelle [INP] $\geqslant$ 0,5), ainsi que les données appropriées sur lesquelles fonder les évaluations, dépassaient la portée de ce projet.

Deuxièmement, dans l'estimation des points de référence, les incertitudes statistiques peuvent être représentées par des intervalles de confiance à 95 % dérivés analytiquement ou par la méthode bootstrap (ou des intervalles de crédibilité à 95 % pour les analyses bayésiennes). Les séries chronologiques courtes ou celles qui présentent un contraste insuffisant dans l'abondance des géniteurs peuvent augmenter les incertitudes d'estimation des points de référence. Pour les points de référence fondés sur le recrutement des stocks, en particulier, les erreurs d'observation dans l'abondance des géniteurs peuvent fausser les estimations des points de référence (« erreurs dans les variables »), tout comme les corrélations qui se produisent lorsque l'abondance des géniteurs d'une année donnée dépend du recrutement de la génération précédente [biais de séries chronologiques, @waltersFisheriesEcologyManagement2004]. Les incertitudes dans les points de référence fondés sur les centiles peuvent provenir des incertitudes dans la productivité et les taux de récolte nécessaires pour catégoriser les populations pour la détermination des points de référence [comme il est décrit dans @holtEvaluatingBenchmarksBiological2018]. Il pourrait y avoir des incertitudes dans les points de référence dérivés du modèle de bassin versant [@parkenHabitatbasedMethodsEstimate2006; @liermannUsingAccessibleWatershed2010] en raison de sa paramétrisation fondée sur des ensembles de données sur les géniteurs et les recrues qui sont périmés (se terminant en 2000) et probablement plus productifs que les populations utilisées dans notre étude de cas. Pour aborder cette dernière source d'incertitude, nous avons dérivé les estimations de productivité et les incertitudes à partir d'un modèle propre aux stades de vie du saumon chinook de la côte ouest de l'île de Vancouver (COIV), combiné à des avis d'experts. Tous ces points de référence peuvent être biaisés lorsque les paramètres sous-jacents de la population changent au fil du temps et que ces changements ne sont pas reflétés dans la procédure d'estimation (voir la section \@ref(futureResearch) pour plus de détails).

Troisièmement, l'incertitude structurelle des modèles stock-recrutement qui sous-tendent l'estimation des points de référence peut submerger d'autres sources d'incertitude, et nécessite un examen attentif fondé sur les données disponibles et la compréhension biologique de la dynamique de la population, idéalement avec un examen par les pairs. Nous fournissons un exemple d'incertitude structurelle dans l'étude sur le saumon coho du Fraser intérieur fondée sur des hypothèses préalables sur la capacité de la population, mais d'autres composantes, telles que les décisions sur la dépensation à de faibles abondances, la variabilité partagée ou indépendante de la productivité parmi les UC, et la force de la surcompensation (p. ex. Ricker par rapport à Beverton-Holt) devraient être considérées.

<!--CH removed: Both structural and parameter uncertainties in run reconstructions may also impact CU assessments. However, @peacockEvaluatingConsequencesCommon2020 found that CU statuses were generally robust to most common assumptions in run reconstructions but that overestimating catch tended to increase rates of status misclassification. -->

```{=html}
<!--CH comment to CW: Catarina, now that you've reminded me about the delta method, I'm not sure I estimated CIs correctly here. I used 95%CI of SREP (capacity) from TMB outputs, and then used a distribution of productivity from expert opinion (leaning on Wilf's life-stage model) and drew randomly from both to get a bootstrapped 95% CI of Sgen, where Sgen is F(Srep, prod). Is this okay mathematically?
CH: not it's not, but have used 95%CIS to apprpoximate credible intervals for now...
-->
```
En plus des incertitudes dans les points de référence, des incertitudes peuvent apparaître dans les états estimés des UC en raison des hypothèses faites pendant l'évaluation de l'état. L'incertitude associée à l'état peut résulter du choix du paramètre utilisé (unique ou multidimensionnel). Dans certains cas, l'état est mieux représenté par un composite de plusieurs paramètres, ce qui entraîne des incertitudes sur l'état lorsqu'un seul paramètre (p. ex., l'abondance des géniteurs) est appliquée. En outre, la répartition de la fraie parmi les populations au sein d'une UC peut être importante pour la viabilité du complexe, et ignorer ou mal identifier cette structure de stock peut entraîner une plus grande incertitude dans l'état évalué. Des incertitudes peuvent également découler de l'application de points de référence fondés sur le stock-recrutement à des échelles spatiales plus grandes ou plus petites que l'échelle à laquelle la densité-dépendance se produit.

Les incertitudes dans les évaluations de la PSS revues par les pairs sont saisies qualitativement, comme il est documenté dans les exposés associés à chaque évaluation de l'UC [p. ex., @dfoWildSalmonPolicy2015]. Ces estimations qualitatives de l'incertitude proviennent d'experts qui intègrent les incertitudes des données et des points de référence et concilient souvent des mesures contradictoires. Ce processus nécessite un examen attentif de l'expertise prise en compte afin de garantir que les meilleures informations disponibles sont intégrées dans les évaluations et la description des incertitudes. Bien que les incertitudes sur l'état des UC dérivées de l'explorateur des saumons ne soient pas actuellement fournies, cette fonctionnalité est envisagée pour les itérations futures de l'outil. L'explorateur des saumons sera appliqué chaque année dans le cadre d'un processus dirigé par des experts, sous la direction du Programme sur l'état du saumon du MPO, afin que les incertitudes sous-jacentes soient prises en compte et que les résultats soient vérifiés. Une revue complète de l'explorateur des saumons incluant les incertitudes est à venir (Pestal et al. en révision).<!--CH comment: There are many uncertainties associated with this tool, but I'm not sure that it's useful for us to include them here as it will invite discussion on topics that are outside scope. Example uncertainties are that the Tool does not include distributional metrics or productivity which may be important in formal WSP assessments, and the Tool was parameterized based on a set of southern stocks so does not necessarily represent the entire range.-->

### PRL fondés sur l'état des UC

Les incertitudes associées à l'état dérivé de PRL fondés sur l'état des UC peuvent provenir de l'exclusion des UC limitées en données des analyses lorsque ces UC sont mal représentées par les UC riches en données qui sont incluses. Pour communiquer clairement cette incertitude, nous suggérons de qualifier ces PRL de provisoires lorsque toutes les UC riches en données ont un état supérieur à rouge. Même lorsque des UC limitées en données présentent des menaces, des conditions et des facteurs environnementaux, des caractéristiques du cycle biologique et des capacités similaires à celles des UC riches en données, la dynamique des populations peut diverger en raison d'autres processus qui ne sont pas pris en compte. Nous recommandons la prudence lors de l'application de PRL provisoires qui ne comprennent pas d'informations directes de toutes les UC. Dans ces cas, nous recommandons de mettre en œuvre un programme de surveillance pour éclairer les évaluations propres à l'UC.

### PRL fondés sur l'abondance globale

**PRL de régression logistique**

Pour les PRL fondés sur la régression logistique, les incertitudes peuvent provenir de l'estimation statistique des modèles stock-recrutement et logistique. Dans nos études de cas, nous fournissons des intervalles de confiances (IC) à 95 % et évaluons leur chevauchement avec l'état actuel. Ces IC représentent l'incertitude dans l'estimation de la régression logistique incorporant l'incertitude dans les points de référence sous-jacents (par exemple, à partir des relations géniteur-recrutement ou du modèle bassin versant-zone). Ceci est dû au fait que l'estimation du modèle de régression logistique a été statistiquement intégrée à l'estimation des points de référence sous-jacents fondés sur le recrutement des géniteurs. Cette intégration statistique permet de propager les incertitudes des points de référence au niveau des UC aux PRL au niveau de l'UGS. Lorsqu'elle est estimée dans un cadre bayésien, la répartition de probabilité des PRL peut être générée pour fournir la probabilité que l'état actuel soit supérieur au PRL compte tenu des incertitudes du PRL. Dans les analyses futures, l'incertitude relative à l'abondance actuelle des géniteurs pourrait être intégrée à l'incertitude pour obtenir des probabilités de dépassement des PRL qui tiennent compte des deux sources.

Comme pour les PRL fondés sur l'état des UC, les incertitudes des PRL de régression logistique peuvent provenir de l'exclusion des UC limitées en données des analyses lorsque ces UC ne sont pas bien représentées par les UC riches en données qui sont incluses. D'autres incertitudes dans les PRL par régression logistique peuvent survenir si le système de gestion a changé au fil du temps, de sorte que la sélectivité des pêches entre les UC a divergé, ou si la covariance dans la dynamique des populations a changé en raison de facteurs naturels ou anthropiques. Dans certains cas, la covariance entre les UC peut être déterminée par des tendances synchrones dans l'apport des écloseries, ce qui crée des estimations trompeuses et peut-être biaisées du PRL.<!--CH omit: such that the relationship between aggregate abundances and CU statuses has changed-->

De plus, des incertitudes dans les deux PRL fondés sur l'abondance globale (PRL de régression logistique et de projection) peuvent survenir parce que ces PRL sont dérivés des états des UC sur un seul paramètre comme approximation de l'état sur plusieurs dimensions. Dans certains cas, ces états peuvent diverger en raison des paramètres supplémentaires pris en compte et des séries chronologiques lissées par génération utilisées pour évaluer l'état actuel dans l'approche multidimensionnelle (telle que mise en œuvre par l'explorateur des saumons).

```{=html}
<!--CH comment: Suggest removing next bullet as I feel like it's getting into the weeds too much, and only makes sense after a bullet describing how logistic regression LRPs can be statistically integrated with SR-based benchmarks and CU status.

For logistic regression LRPs derived from CU assessments that are independent of spawner-recruitment models (e.g, that use habitat-based benchmarks), it is still be possible to integrate uncertainties from the CU assessments to SMU-level LRPs though bootstrapping methods. For example, where CU benchmark estimates are provided with uncertainties, benchmarks can be sampled from those distributions randomly and used to estimate a distribution of LRPs. In preliminary analyses, this approach was applied to the case study for West Coast Vancouver Island Chinook Salmon to derive uncertainty in logistic regression LRPs that accounted for uncertainty in status of component inlets from a watershed-area model. However, because the data did not support the use of logistic regression for that case study, results are not presented, but code to apply this method is available in our repository.
-->
```
<!--CH: the following 2 lines give a line break before the next heading-->

\
  **PRL de projection**

Les PRL fondés sur la projection tiennent compte explicitement des incertitudes sous-jacentes dans les paramètres de la population et de l'exploitation, comme la productivité et la capacité au niveau des UC, la structure selon l'âge, la covariance dans les écarts de recrutement et la variabilité dans la mise en œuvre des stratégies d'exploitation au fil du temps et entre les UC. L'inclusion de l'incertitude structurelle sous la forme de différentes relations stock-recrutement est démontrée pour l'étude de cas sur le saumon coho du Fraser intérieur. Nous recommandons un examen approfondi des hypothèses et nous recommandons de les inclure directement dans l'échantillonnage aléatoire des projections ou de les inclure en tant qu'analyses de sensibilité.

Une mise en garde de cette approche est que le PRL dépend de la procédure de gestion appliquée dans les projections, mise en œuvre comme une stratégie d'exploitation constante pour nos études de cas. Bien que les procédures de gestion du saumon du Pacifique comprennent souvent des objectifs d'échappée, des limites d'exploitation fixes et/ou un ensemble fixe de taux d'exploitation qui varient en fonction de l'abondance, nous avons supposé que ces procédures<!--omit: salmon are managed through regulations on effort or exploitation rate and not allowable catches, and emergent time-series of exploitation--> peuvent être grossièrement rapprochées d'un taux d'exploitation constant avec une erreur de mise en œuvre. D'autres procédures de gestion plus réalistes pourraient être envisagées dans les itérations futures. Les PRL de projection obtenus de cette manière ne peuvent pas être utilisés pour évaluer l'état lorsque les procédures de gestion changent au fil du temps et que ces changements n'ont pas été évalués dans la projection.

Une différence entre les PRL de projection et les PRL de régression logistique est que pour les PRL de projection, les incertitudes dans tous les paramètres sous-jacents et les points de référence au niveau des UC sont intégrés dans la probabilité que toutes les UC soient au-dessus de leurs points de référence inférieurs, de sorte que le PRL lui-même n'a pas d'incertitude statistique associée. En revanche, les IC à 95 % associés aux PRL de régression logistique tiennent compte de l'incertitude de l'estimation non incluse dans les PRL de projection.

Lorsque l'on examine les PRL de régression logistique et les PRL de projection en fonction d'autres hypothèses de modèle, comme différentes formulations du modèle stock-recrutement, on peut choisir les PRL en fonction de la force de la preuve pour les hypothèses sous-jacentes ou faire la moyenne lorsque les autres hypothèses sont toutes également plausibles. Il faut être prudent lorsqu'il y a peu ou pas de chevauchement dans la distribution des PRL selon diverses hypothèses du modèle, car le calcul de la moyenne peut masquer différentes réalités plausibles qui nécessiteraient des mesures de gestion différentes.

## INCIDENCE DE L'ABSENCE D'UC SUR L'ÉTAT AU NIVEAU DE L'UGS

```{=tex}
\begin{tcolorbox}[standard jigsaw,opacityback=0.8,colframe=black,boxrule=0.7pt,left=0.1in, sharp corners]
\subsection*{Principaux points:}
\begin{itemize} 
\item Pour \textbf{les PRL fondés sur l’état des UC}, lorsqu’une UGS contient des UC dont les données sont insuffisantes et que les autres UC riches en données sont au-dessus de l’état rouge, nous recommandons que l’état de l’UGS soit considéré comme étant provisoire (c.-à-d. un état avec une plus grande incertitude) ou manquant de données.
\begin{itemize}
\item L’état de l’UGS est provisoire lorsque les UC riches en données sont jugées représentatives des UC manquant de données.
\item L’état de l’UGS manque de données lorsque les UC riches en données ne sont pas représentatives des UC manquant de données.
\end{itemize}
\item De même, pour les PRL fondés sur l’état des UC, lorsqu’une UC composante a un état rouge, nous recommandons que l’état de l’UGS soit évalué comme étant inférieur au PRL, indépendamment de la présence d’UC manquant de données et si l’état des UC manquant de données peut être déduit des UC riches en données.
\item Pour les \textbf{PRL fondés sur l’abondance globale}, nous recommandons que l’état de l’UGS soit provisoire lorsque les UGS contiennent des UC manquant de données qui peuvent être déduites d’UC riches en données, quel que soit l’état des UC riches en données.
\end{itemize}
\end{tcolorbox}
```
Pour les PRL fondés sur l'état des UC, nous recommandons que l'état de l'UGS soit considéré provisoire (c'est-à-dire un état avec une plus grande incertitude) ou manquant de données lorsqu'une UGS contient des UC manquant de données et que les UC restantes riches en données sont au-dessus de l'état rouge. Cette recommandation est fondée sur la possibilité de biais positifs dans l'état fondé uniquement sur les UC riches en données. Un état provisoire peut être attribué aux UGS lorsque les UC riches en données sont représentatives des UC ayant des données insuffisantes (reflétant une grande incertitude quant à l'état), et un état d'UGS manquant de données peut être attribué lorsque les UC riches en données ne sont pas représentatives (tableau \@ref(tab:GuidanceDDCUs)). Le pouvoir de détecter un dépassement du PRL fondé sur l'état des UC est relativement faible lorsque la taille de l'échantillon des UC riches en données est petite par rapport au nombre total d'UC composantes. Par conséquent, les états qui ne reposent que sur un petit nombre d'UC au sein d'une UGS ont tendance à fournir des états plus optimistes que ceux qui comprennent un plus grand échantillon d'UC pour les PRL fondés sur l'état des UC, comme le montre l'étude de cas sur le saumon kéta de l'intérieur de la côte sud.

En revanche, si le PRL de 100 % des UC au-dessus de l'état rouge a été dépassé pour une UGS avec des UC manquant de données, l'inclusion d'UC supplémentaires peut réduire ou améliorer l'état défini comme le pourcentage d'UC au-dessus de l'état rouge, mais ne changera pas le fait que le PRL a été dépassé. Cet impact asymétrique de la surveillance accrue des UC sur l'état de l'UGS peut réduire les incitations à étendre la surveillance aux UC dont les données sont insuffisantes.

Pour les PRL d'abondance globale, nous recommandons que l'état des UGS soit provisoire lorsque les UGS contiennent des UC manquant de données qui peuvent être représentées par des UC riches en données, quel que soit l'état des UC riches en données. Pour ces PRL, nous avons constaté que le fait de retirer des UC de composantes de l'évaluation d'une UGS tendait à augmenter la variabilité de l'état au niveau de l'UGS, qui peut être plus pessimiste ou plus optimiste que lorsque toutes les UC sont prises en compte, selon l'UC retirée et le niveau de covariation entre les UC. Pour les PRL de régression logistique en particulier, la suppression des UC influe sur l'ajustement du modèle de régression logistique, ce qui a une incidence sur l'état estimé par rapport aux PRL d'une manière qui est difficile à prévoir *a priori*, comme le montre l'étude de cas sur le saumon coho du Fraser intérieur. De plus, pour les PRL fondés sur l'abondance globale, nous recommandons l'état « manquant des données » pour les UGS dont les UC composantes sont insuffisantes et ne peuvent être déduites des UC riches en données.

## RECHERCHES FUTURES {#futureResearch}

```{=tex}
\begin{tcolorbox}[standard jigsaw,opacityback=0.8,colframe=black,boxrule=0.7pt,left=0.1in, sharp corners]
\subsection*{Principaux points:}
\begin{itemize} 
\item Nous recommandons de prioriser les recherches futures de manière à évaluer les répercussions des éléments suivants:
\begin{itemize} 
\item Tendances temporelles des processus de population sous-jacents tels que la productivité intrinsèque et la capacité de charge sur les points de référence biologiques et les points de référence.
\item Adapter les PRL afin d’inclure une portée plus large pour les dommages graves, y compris les considérations relatives à l’écosystème et à l’habitat, la répartition des géniteurs au sein des UC et le savoir autochtone.
\item Évaluation par simulation des méthodes de détermination du PRL compte tenu de la variabilité temporelle des paramètres de la population et d’autres sources d’incertitude.
\end{itemize}
\end{itemize}
\end{tcolorbox}
```
Nous recommandons des recherches futures sur les répercussions des paramètres variant dans le temps, l'adaptation des PRL afin d'inclure un champ plus large pour les dommages graves, et l'évaluation des méthodes de PRL, comme il est décrit plus en détail ci-dessous. Nous mettons l'accent sur les paramètres variant dans le temps en raison de leur omniprésence dans la dynamique des populations de saumon du Pacifique et de leurs répercussions documentées sur les points de référence.

### PARAMÈTRES VARIANT DANS LE TEMPS ET RÉPERCUSSIONS SUR LES PRL

De plus en plus de données indiquent l'existence de processus démographiques variant dans le temps au sein des populations de saumon du Pacifique, notamment en ce qui concerne les tendances de la productivité [@dornerSpatialTemporalPatterns2018; @malickRegionalScaleDeclinesProductivity2016; @petermanWidespreadDecreaseProductivity2012]. Au Canada, les évaluations du MPO ont indiqué des déclins de productivité pour diverses UC, par exemple le saumon rouge du fleuve Fraser [@grantEvaluationUncertaintyFraser2012; @grantIntegratedBiologicalStatus2013; @huangRecoveryPotentialAssessment2021], le saumon chinook du sud de la Colombie-Britannique [@dfoIntegratedBiologicalStatus2016], et le saumon coho du Fraser intérieur [@arbeiderInteriorFraserCoho2020]. Ces évaluations se sont appuyées sur divers outils pour déterminer les tendances de la productivité, notamment l'évaluation des tendances de recrues par géniteur [@arbeiderInteriorFraserCoho2020] et des résidus des ajustements des courbes de recrutement [@grantEvaluationUncertaintyFraser2012], ainsi que la prise en compte explicite des paramètres variant dans le temps lors de l'ajustement des courbes de recrutement à l'aide du filtre de Kalman ou des approches récursives de Bayes [@huangRecoveryPotentialAssessment2021]. Cependant, il n'est pas toujours simple de déterminer le soutien des paramètres variant dans le temps. Les diagnostics statistiques courants tels que l'inspection des résidus et l'utilisation de critères d'information (par exemple, critère d'information d'Akaike [CIA] et critère d'information de Bayes [CIB]) produisent souvent des résultats contradictoires [@holtImpactTimevaryingProductivity2020]. Les preuves de changements de capacité dans le temps sont moins fréquentes chez les populations de saumon du Pacifique, mais les répercussions potentielles de la capacité variable dans le temps ont été explorées dans des études de simulation et peuvent être importantes, bien qu'elles soient généralement moins importantes que les changements de productivité [@holtWillDepletedPopulations2010; @dornerEvaluatingAlternativeMethods2013]. Les changements dans la démographie des populations, tels que la taille selon l'âge et l'âge à la maturité, sont également connus pour influencer la dynamique des populations et les points de référence. Le fait de ne pas suivre les changements interannuels de l'âge à la maturité peut conduire à des estimations biaisées des paramètres stock-recrutement et à une sous-estimation de la variance du modèle [@zabelSimpleAssumptionsAge2002; @bradfordEffectsAgeingErrors1991].

Les paramètres de recrutement et la démographie de la population qui varient dans le temps influent sur les estimations des points de référence du saumon, par exemple G~RMD~ et G~gén~ [@holtImpactTimevaryingProductivity2020; @statonIncorporatingDemographicInformation2021] et sont également susceptibles d'influer sur les tendances de la population, ce qui entraîne des modifications des points de référence fondés sur des observations historiques [p. ex., les points de référence fondés sur les centiles, @holtEvaluatingBenchmarksBiological2018]. Des méthodes analytiques pour des points de référence variant dans le temps ont été proposées pour d'autres espèces de poissons marins [@amarEvaluationTwoManagement2009; @puntFisheriesManagementClimate2014], dont certaines ont été évaluées empiriquement et en simulation avec des résultats mitigés [@olearyComparisonMultipleApproaches2020; @bergerCharacterTemporalVariability2019]. @bergerCharacterTemporalVariability2019 suggère que les points de référence dynamiques qui suivent les changements dans les processus de population sous-jacents sont plus utiles dans les situations où la productivité du stock change de direction et où le signal de productivité est correctement déterminé. En revanche, l'incertitude liée à une détermination incorrecte des tendances de la productivité peut être une source majeure d'inexactitude dans l'état des stocks [@bergerCharacterTemporalVariability2019].

Bien que les preuves de l'existence de processus de population variant dans le temps soient solides, les conseils sur l'intégration de ces changements dans l'évaluation et la gestion du saumon du Pacifique font défaut. Dans un examen des analyses stock-recrutement pour le saumon du Pacifique, @adkisonReviewSalmonSpawnerRecruitment2021 a souligné que même lorsqu'il existe des preuves solides de non-stationnarité dans la dynamique de la population, il n'est pas clair si les points de référence doivent être ajustés en conséquence. Lorsque l'épuisement d'un stock est associé à des paramètres variant dans le temps et que l'on pense qu'ils sont réversibles, il peut être plus approprié de protéger la population contre la récolte en maintenant des points de référence utilisant toutes les données historiques [@dfoProceedingsNationalWorkshop2013; @szuwalskiClimateChangeNonstationary2016]. @dfoHarvestStrategyCompliant2006 a recommandé que les changements de points de référence ne soient effectués que lorsqu'il existe des preuves considérables que la productivité a changé et qu'il n'est pas prévu que ces changements s'inversent naturellement ou qu'ils soient obtenus par des mesures de gestion. En outre, le cadre de l'approche de précaution du ministère des Pêches et des Océans (MPO) stipule qu'« au moment d'établir les points de référence, il faut s'efforcer de tenir compte de l'ensemble des facteurs qui peuvent influer sur la productivité du stock, y compris les changements des conditions océaniques, lorsque l'information est disponible » [@dfoFisheryDecisionmakingFramework2009]. Ces informations peuvent aider à déterminer si les réductions de productivité sont susceptibles d'être réversibles ou seulement lentement réversibles. @klaerHowMuchEvidence2015 ont conçu un cadre pour évaluer le degré de confiance à l'égard des changements de productivité dans les pêcheries australiennes, et des approches similaires pourraient être adaptées aux populations de saumon canadiennes.

Même si l'on envisage des points de référence variables dans le temps, il est difficile de définir à quelle fréquence ils doivent être modifiés [@zhangReportOceanFrontier2021]. Des changements inopportuns dans les points de référence peuvent entraîner des distorsions dans l'état des stocks et la volatilité des réponses de la gestion peut entraîner une incertitude dans la gestion, réduisant ainsi la confiance dans le processus de gestion [@adkisonReviewSalmonSpawnerRecruitment2021]. Des études récentes recommandent l'utilisation d'exercices de simulation de rétroaction propres à chaque cas afin de déterminer l'échelle appropriée pour ajuster les points de référence lorsque les paramètres stock-recrutement sont non stationnaires [@holtImpactTimevaryingProductivity2020; @zhangAccountingNonstationaryStock2021; @olearyComparisonMultipleApproaches2020]. Cependant, les études de simulation de rétroaction complète pourraient ne pas être réalisables pour chaque UC où des tendances sont suspectées en raison des ressources limitées.

D'autres recherches visant à déterminer quand et comment tenir compte des paramètres et des données démographiques variant dans le temps dans les évaluations et la gestion du saumon du Pacifique sont justifiées et sont actuellement en cours au sein du MPO. Les méthodes actuelles d'évaluation de la PSS ne tiennent pas systématiquement compte des dynamiques variables dans le temps et de leurs répercussions sur l'état et les estimations du PRL qui en résultent. Des orientations sur la comptabilisation des paramètres variables dans le temps qui diffèrent entre les UC au sein d'une UGS sont également justifiées. Les dynamiques de recrutement des stocks variant dans le temps se produisent généralement au niveau des UC, et les répercussions pour les PRL fondés sur les UGS qui contiennent plusieurs UC ne sont pas simples. Il n'existe pas de directives claires sur la manière de traduire les paramètres de recrutement des stocks variant dans le temps pour les UC en PRL au niveau agrégé. Les effets de la dynamique de recrutement des UC variant dans le temps sur l'abondance globale et les PRL fondés sur l'état des UC dépendront du degré de synchronisation entre les UC, de la direction du changement des paramètres de recrutement et de l'état passé et actuel des stocks, entre autres facteurs. Par exemple, dans notre étude de cas sur le saumon coho du Fraser intérieur, lorsqu'un niveau de productivité constamment plus faible a été introduit par le biais d'une autre formulation du modèle stock-recrutement (une formulation qui incluait des valeurs a priori informatives sur la capacité dans les modèles stock-recrutement au niveau des UC), les points de référence ont augmenté pour la plupart des UC, tout comme le PRL fondé sur l'abondance globale pour l'UGS. Cependant, dans les cas où la productivité varie à des taux différents entre les UC ou si la capacité change également, les répercussions sur les points de référence au niveau des UC et les PRL au niveau de l'UGS ne seront pas facilement prévisibles.

### ADAPTATION DES PRL POUR INCLURE UN CHAMP PLUS LARGE POUR LES DOMMAGES GRAVES

Nous recommandons des recherches futures sur les PRL qui tiennent compte de la composante écosystémique des dommages graves pour le saumon du Pacifique et qui prévoient des délais plus longs pour l'évaluation des seuils de dommages graves. La composante écosystémique du dommage grave pourrait être envisagée en tenant compte de l'importance des populations de saumon du Pacifique pour les écosystèmes marins [@nelsonWildChinookSalmon2019; @waltersHasStellerSea2020; @trochtaApplyingBayesianModel2021] et des répercussions de la migration des saumons sur l'afflux de nutriments d'origine marine dans les écosystèmes d'eau douce et estuariens [@schindlerPacificSalmonEcology2003; @hockingConsumptionDistributionSalmon2006; @fieldSeaSkyImpacts2011; @quinnMultidecadeExperimentShows2018]. Bien que la définition de dommage grave selon le cadre de l'approche de précaution du MPO englobe les répercussions sur l'écosystème, les espèces associées et la perte à long terme des possibilités de pêche [@dfoFisheryDecisionmakingFramework2009], l'évaluation du dommage à ces composantes dépend dans une certaine mesure de l'horizon temporel considéré. Les évaluations qui n'incluent que des données très récentes peuvent passer à côté d'importantes diminution de l'état et de répercussions sur les écosystèmes qui se sont produits historiquement avant le début des relevés modernes. Dans certains cas, la prise en compte d'une vision à plus long terme à partir de connaissances génétiques, archéologiques, paléoécologiques ou autochtones a démontré que les déclins récents font partie de déclins historiques beaucoup plus importants associés à des répercussions à grande échelle sur les écosystèmes [@eckertDivingBackTime2018; @leeDiverseKnowledgeSystems2019; @priceGeneticsCenturyOld2019; @mckechnieArchaeologicalDataProvide2014].

Le savoir autochtone a été pris en compte dans l'élaboration de points de référence cibles pour la gestion des pêches [@caddyReferencePointsFisheries1995], et il serait utile d'examiner plus avant son rôle dans la détermination des dommages graves. @reidTwoEyedSeeingIndigenous2021 introduisent le concept de double perspective (Etuaptmumk en mi'kmaq), où les perspectives de la science autochtone et de la science occidentale sont valorisées par le biais du processus suivant: apprendre à voir d'un œil avec les forces des connaissances et des modes de connaissance autochtones, et de l'autre œil avec les forces des connaissances et des modes de connaissance occidentaux, et utiliser ces deux perspective ensemble, au bénéfice de tous. En examinant les dommages graves, les points de référence et la nature variable dans le temps de ces concepts du point de vue des Autochtones et des scientifiques occidentaux, les PRL peuvent mieux refléter les processus biologiques qui sous-tendent les deux systèmes de connaissances. Cette étape nécessite un engagement et une collaboration avec les peuples autochtones pour codiriger et coproduire des recherches sur l'association des connaissances autochtones avec les PRL fondés sur la science occidentale. <!--CH: I see the internal inconsistency here where our direction from NHQ is to provide scientifically based LRPs, yet reconciliation says we should change our perspective and not focus entirely on western science. However, our TWG really wasn’t equipped to do this and was beyond our ToR-->

<!--CH omit: too focused on Scanner tool for this paper and would need reworking... “More specifically, methods for CU assessments could further consider serious harm to habitat or ecosystems, for example by extending the Pacific Salmon Status Scanner Tool to account for ecosystem components of serious harm, as well as divergent levels of data quantity and quality among CUs. Furthermore, the Rapid Multidimensional Scanner Tool could be extended to provide management triggers that occur prior to reaching the LRP, for example that require precautionary management and/or increased monitoring, as in @dowlingGuidelinesDevelopingFormal2015.”-->

```{=html}
<!--CH suggest removing as I don’t want to focus too much on the recommendation for Bayes analyses though I briefly mention this in section on uncertainties. It brings up the Q, why didn’t we do it? Also this is more a guidance piece that future research.
“We recommend that the application of LRPs and SMU status account for uncertainty in CU-level assessments where possible, ideally in  probabilistic framework. For example, for CU status-based LRPs derived from single metrics of status, the probability of all CUs being above lower benchmark could be derived by integrating the probability of CU-level benchmarks from Bayesian estimation and the associated status relative to those benchmarks across all CUs, e.g. by sampling from the posterior distributions of CU-level statuses across all CUs.”-->
```
En outre, la répartition des géniteurs au sein des UC est une composante des évaluations des UC dans le cadre de la PSS, mais des mesures et des points de référence robustes de la répartition font défaut. Les recherches futures sur les méthodes d'évaluation qui considèrent plus rigoureusement la structure de la population au sein des UC seraient bénéfiques à la fois pour les évaluations des UC dans le cadre de la PSS et pour les évaluations pertinentes pour les Premières Nations qui dépendent souvent des populations de saumon à des échelles spatiales relativement fines.

D'autres méthodes de PRL peuvent être élaborées à l'avenir pour saisir un plus large éventail de disponibilité, de qualité et de types de données, ainsi que des dimensions de l'état biologique, en accord avec les principes clés de la section \@ref(principles). Au fur et à mesure que les méthodes sont élaborées et révisées, les états de l'UGS peuvent également être mis à jour conformément au principe 1, en utilisant les meilleures informations disponibles pour l'élaboration des PRL.

### ÉVALUATION DES MÉTHODES DE PRL

Nous recommandons un examen et une évaluation plus approfondis des quatre critères proposés pour déterminer si les UC limitées en données peuvent être déduites des UC riches en données (étape 3, section \@ref(guidelines)). Par exemple, ces critères (et/ou d'autres considérations) pourraient être appliqués aux UGS où les états des UC sont disponibles afin d'évaluer dans quelle mesure les états covarient lorsque les UC sont jugées représentatives les unes des autres. L'évaluation par simulation pourrait également évaluer la mesure dans laquelle les états des UC sur un seul paramètre d'état covarient sous une gamme de structures de covariance sous-jacentes plausibles dans le recrutement, l'âge à la maturité et les taux d'exploitation.

De plus, nous recommandons une évaluation par simulation des PRL de régression logistique et des PRL de projection afin d'évaluer les répercussions des limitations des données liées au nombre d'UC avec des données et aux hypothèses sur la dynamique de la population et la covariance entre les UC. Nous recommandons que ces évaluations soient paramétrées aux UGS où leur application est proposée afin de s'assurer que les résultats sont pertinents au contexte précis considéré.

Lors de l'application des méthodes à des études de cas spécifiques, nous recommandons que les PRL d'abondance globale tiennent compte des principales incertitudes structurelles, soit par des analyses de sensibilité, soit par des approches d'ensemble de modèles. Ces analyses peuvent déterminer la sensibilité des PRL de l'abondance globale aux principales incertitudes du modèle, y compris celles liées aux paramètres variant dans le temps, à la dépensation aux faibles abondances, aux erreurs d'observation et à la covariance de la dynamique de la population et de la vulnérabilité à la récolte. Nous soulignons l'importance critique de cette étape en considérant un large éventail d'hypothèses sur la dynamique sous-jacente. En effet, les modèles standard stock-recrutement peuvent avoir une utilité limitée s'ils ne rendent pas compte de la dynamique actuellement observée. En outre, nous recommandons une évaluation par simulation afin d'évaluer la robustesse des PRL à la violation des hypothèses analytiques sous-jacentes. L'évaluation par simulation pourrait en outre être utilisée pour évaluer la fréquence des mises à jour des PRL nécessaires pour atteindre les objectifs, compte tenu des modifications sous-jacentes des paramètres et de la structure du modèle. <!--CH: observation errors in CU-status are relevant for logistic-regression LRPs as they might inflate noise in the LR, and they are relevant to the projection LRPs in the noise in the spawner and recruitment data-->

```{=html}
<!--

CW: I moved this here from ch 4.
CH: suggest keeping out for  now

- Question: could serious harm may mean extinction rather that in the red zone?  

- The question of whether a CU within a larger SMU can persist in the red zone is something that could be simulation tested; although, this would require harvest control rules to be specified for testing.  Such an approach would be case-specific and outside of the scope of our work.  However, we could consider recommending that if a decision is made for a CU to allow some proportion of CUs to be in the red zone, quantitative evaluation (e.g., simulation testing) should be used to demonstrate that red CUs will not be lost. [Although, we may still want to consider putting some bounds on what proportion would be allowed to be below their lower benchmark, i.e., a large proportion of CUs persisting in the red zone may not be acceptable ].

-if using $<$100 $\%$ of CUs $>$ red, could recommend simulation testing



Beyond scope: CU-level benchmark considerations
- How do data availability and biological considerations interact to inform a decision about which CU-level benchmark to use? (e.g, Sgen from SSR vs. Sgen from Watershed-Area vs. percentile vs. distributional benchmarks, etc)?  
- Under what conditions should Watershed-Area based LRPs be used? 
- How do mean and distributions (uncertainties) of watershed-area based and stock-recruitment based benchmarks compare?
- Under which levels of data uncertainties do stock-recruitment based LRPs outperform habitat-based LRPs? 
- In cases where watershed-area based benchmarks and stock-recruitment based benchmarks are available, both should be presented and used to derive complementary LRPs to capture our underlying model uncertainties.
- Alternatively, could be combined by using watershed area to inform prior on beta in the stock-recruitment model
- What if stocks have different levels of data, e.g., Fraser Sockeye, where stock-recruitment as available for some CUs, while others have only escapement data.  When is it beneficial to use available data for data poor CUs vs when to exclude them?

-->
```
```{=html}
<!--

old notes on time-varying parameters
- Briefly document evidence for time-varying productivity for Pacific salmon
- Summarizing recent DFO CSAS documents that include discussion of time-varying reference points for Pacific salmon, and recent primary publications:
- Summarize approach for considering time-varying productivity in WSP CU assessments (e.g., Kalman filter on productivity parameters))

@adkisonReviewSalmonSpawnerRecruitment2021 reviews stock recruitment analysis for Pacific salmon, including the use of environmental covariates and time-varying parameters. They highlight that even though there might be strong evidence for non stationarity in salmon populations, it is not clear if reference points should me adjusted accordingly. 

@kronlundConsiderationsDesignRebuilding2021 recommends that any decision to introduce time-varying reference points be based on evidence supporting that rebuilding could reasonably be expected. They recommend the use of feedback simulations to illustrate the consequences of time-varying benchmarks and identify exceptional circumstances that should lead to re-examination of reference point and management measures. 

 @zhangAccountingNonstationaryStock2021 illustrates the effects of time-varying recruitment parameters on MSY-based reference points for iteroparous fish stocks (cod and plaice). They highlight that more precautionary benchmarks are necessary to account for the parameter uncertainty in highly dynamic ecosystems. However, they observed that effects on reference points depend on the magnitude and structure of the stochasticity in stock-recruitment relationships, therefore they recommend case specific simulation studies be performed to identify explicit impacts on MSY-based reference points.

-->
```
