# REMERCIEMENTS

Nous tenons à remercier le groupe de travail technique sur les PRL pour le saumon pour le soutien considérable qu’il nous a apporté au cours des trois années qui ont mené au présent examen. Les membres de ce groupe sont (par ordre alphabétique de nom de famille, à l’exception des co-auteurs) Michael Arbeider, Jessy Bokvist, Nicholas Brown, Charmaine Carr-Harris, Kelsey Campbell, Steve Cox-Rogers, Sabrina Crowley, Shaun Davies, Brooke Davis, Diana Dobson, Michael Folkes Aaron Foos, Nicole Frederickson, Wilf Luedke, Diana McHugh, Pete Nicklin, Chuck Parken, Candace Picco, Mike Staley, Pieter Van Will, Antonio Velez-Espino, et Ryan Whitmore.

Nous aimerions particulièrement remercier de leur contribution les membres des Premières Nations du groupe de travail technique, qui ont apporté des perspectives et des idées uniques à nos discussions.

Le programme sur l’état du saumon, dirigé par Sue Grant, a fourni un leadership et des conseils utiles sur l’explorateur de l’état des saumons du Pacifique. Merci à Bronwyn MacDonald et à Gottfried Pestal pour leur travail d’analyse sur cet outil, et pour avoir répondu à nos questions à son sujet.<!--CH: although I’d like to thank Sue directly, it feels funny as she’s a co-author. I could revise anyways...? -->

En outre, Brooke Davis a fourni une aide précieuse en élaborant les premières versions du code du modèle de régression logistique intégré, ce dont nous lui sommes extrêmement reconnaissants.

Nous remercions également Julie Marentette, Tim Barrett, Mary Thiess, Jason Ladell et Danny Ings pour leurs points de vue sur les PRL à l’échelle nationale et appliqués à d’autres groupes taxonomiques. Julie Marentette, Tim Barrett et Mary Thiess ont également fourni des commentaires utiles sur une version antérieure.

Enfin, nous remercions Mike Bradford (MPO) et Will Atlas (Wild Salmon Center) pour leurs commentaires détaillés dans le cadre du processus d’examen du CSAP, qui ont contribué à améliorer le présent document de recherche.

<!-- Full list of TWG members:
Michael Arbeider,
Jessy Bokvist,
Nicholas Brown,
Charmaine Carr-Harris,
Kelsey Campbell,
Brendan Connors,
Steve Cox-Rogers,
Sabrina Crowley,
Shaun Davies,
Brooke Davis,
Diana Dobson,
Michael Folkes
Aaron Foos,
Nicole Frederickson,
Sue Grant,
Carrie Holt,
Kendra Holt,
Wilf Luedke,
Ann-Marie Huang,
Diana McHugh,
Pete Nicklin,
Chuck Parken,
Candace Picco,
Mike Staley,
Pieter Van Will,
Antonio Velez-Espino,
Luke Warkentin,
Ryan Whitmore,
Catarina Wor,
-->

