<!-- The following code should appear at the beginning of the first appendix.
After that, all subsequent sections will be turned into appendices. -->

`r if(knitr:::is_latex_output()) '\\Appendices'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

# ÉTUDES DE CAS {#app:case-studies}


Nous illustrons l’application des méthodes potentielles pour les points de référence limites (PRL) élaborés dans la section \@ref(est-methods) à trois unités de gestion des stocks (UGS) comme études de cas, évaluons la sensibilité des PRL à diverses hypothèses, et utilisons ces applications pour éclairer les directives présentées dans la section \@ref(guidelines). Les études de cas comprenaient le saumon coho du Fraser intérieur, le saumon chinook de la côte ouest de l’île de Vancouver (COIV) et le saumon kéta de la côte sud intérieure (à l’exception des unités de conservation [UC] du Fraser), chaque UGS comprenant de 3 à 7 UC. Ces UGS ont été choisies parce qu’elles couvrent un large éventail de types de données et de disponibilités, allant de données riches (saumon coho du Fraser intérieur) à des données limitées (saumon kéta de la côte sud intérieure). En outre, elles variaient sur le plan des contributions d’écloseries, allant d’un niveau élevé (saumon chinook de la COIV) à un niveau relativement faible (saumon coho du Fraser intérieur et saumon kéta de la côte sud intérieure), et deux de ces études de cas sont incluses dans le premier lot proposé de stocks à réglementer en vertu des dispositions sur les stocks de poissons (saumon coho du Fraser intérieur et saumon chinook de la COIV). Pour chaque étude de cas, l’ensemble des méthodes de PRL considérées est fonction des données disponibles et des méthodes d’évaluation précédemment élaborées pour les UC composantes. Dans cette section, nous fournissons une brève description de chaque étude de cas et des méthodes appliquées à chacune. Pour des descriptions plus complètes des études de cas, y compris les caractéristiques des UGS, les sources de données, les méthodes d’analyse et les résultats, voir @holtCaseStudyApplicationsInpress. 


## SAUMON COHO DU FRASER INTÉRIEUR

L’UGS de saumon coho du Fraser intérieur comprend le saumon coho qui fraye dans le fleuve Fraser et ses affluents en amont de Hells Gate, dans le canyon du Fraser. Cette UGS est composée de 5 UC: le moyen Fraser, le canyon du Fraser, la basse Thompson, la Thompson Nord et la Thompson Sud [@dfoWildSalmonPolicy2015]. Le déclin de l’abondance des géniteurs de saumon coho du Fraser intérieur tout au long des années 1990 a conduit à une série de mesures de gestion visant à favoriser le rétablissement, y compris d’importantes restrictions de la pêche à partir de 1998 [@deckerAssessmentInteriorFraser2014]. Les travaux antérieurs de l’équipe chargée du rétablissement du saumon coho du Fraser intérieur (ÉRCFI) ont permis de désigner 11 sous-populations nichées dans les cinq UC et d’élaborer des objectifs de rétablissement fondés sur le maintien de l’abondance de chaque sous-population au-dessus des seuils de conservation [@interiorfrasercohorecoveryteamConservationStrategyCoho2006]. En 2014, une évaluation de l’état de la Politique concernant le saumon sauvage (PSS) revue par des pairs a classé trois de ces UC dans la catégorie ambre (moyen Fraser, canyon du Fraser, Thompson Sud) et les deux autres UC dans la catégorie ambre/vert (basse Thompson, Thompson Nord) [@dfoWildSalmonPolicy2015]. Dans le cadre de l’évaluation de la PSS, G~gén~ a été estimé pour chaque UC et utilisé comme l’un des nombreux points de référence pris en compte pour déterminer l’état de l’UC intégrée. 

Pour calculer des points de référence fondés sur le rapport géniteur-recrutement au niveau de l’UC, nous avons utilisé les données sur l’abondance annuelle totale des géniteurs, le recrutement selon l’âge (des géniteurs naturels), et les indices du taux de survie de l’état de saumoneau à l’état adulte provenant des écloseries pour les années de remonte 1998 à 2020. Les données sur l’abondance des géniteurs d’origine naturelle dans chacune des 11 sous-populations, additionnées au niveau des UC, ont été utilisées pour évaluer l’état et les tendances au niveau des UC pour les PRL basés sur l’état des UC et de régression logistique. Ces données, ainsi que les taux d’exploitation, ont été utilisés pour paramétrer le modèle de projection pour les PRL de projection. La contribution des écloseries à la production était généralement faible dans cette UGS, avec des valeurs d’influence naturelle proportionnelle (INP) >0,5, et habituellement >0,72. L’abondance des géniteurs est positivement corrélée entre les UC, avec une corrélation moyenne de 0,56 (figure \@ref(fig:density-cor-plot)).

<!--CH: to do for next iteration: add rug plot for data points, and limit x-axis to 00.5=-->

```{r density-cor-plot, fig.cap="Distribution des corrélations dans l’abondance des géniteurs entre les UC (ou les bras de mer pour le saumon chinook de la COIV) pour les trois études de cas.", out.width = '100%', warning=FALSE, echo=FALSE, fig.align="center"}
download.file('https://github.com/Pacific-salmon-assess/SalmonLRP_RetroEval/raw/master/WCVIChinookStudy/DataOut/WCVI_Spawner_cors.csv', './data/chinook-Scors.csv',  mode="wb")

download.file('https://github.com/Pacific-salmon-assess/SalmonLRP_RetroEval/raw/master/SCChumStudy/DataOut/chum-escapement-correlation-matrix.csv', './data/chum-Scors.csv',  mode="wb")

#download chum data from here: https://github.com/Pacific-salmon-assess/SalmonLRP_RetroEval/raw/master/SCChumStudy/DataOut/chum-escapement-correlation-matrix.csv 

df <- data.frame(read.csv("data/chinook-Scors.csv", header=TRUE))
colnames(df) <- c("cor")
df$SMU <- rep("WCVI Chinook", length(read.csv("data/chinook-Scors.csv", header=TRUE)))

chum <- read.csv("data/chum-Scors.csv", header=TRUE)[,2:8]
df_chum <- data.frame(cor=chum[lower.tri(chum)==TRUE], SMU="ISC Chum")

coho <- read.csv("data/coho-amongCUCorr-natSpawners.csv")
df_coho <- data.frame(cor=coho$amongCUCorr, SMU="IFR Coho")

df <- df %>% add_row(df_chum) %>% add_row(df_coho)
ggplot(df, aes(cor, fill=SMU, colour=SMU)) + geom_density(alpha=0.1) + 
  xlim(-1,1) + xlab("Corrélation de Pearson par paires dans l’abondance des géniteurs")

```


Nous avons caractérisé l’état de l’UC de trois façons, en utilisant: 1) l’explorateur de l’état du saumon du Pacifique, 2) les abondances au niveau de l’UC par rapport à G~gén~ comme point de référence inférieur sur l’abondance dérivée de la relation géniteur-recrutement dans le cadre de la PSS, et 3) la répartition de l’abondance des géniteurs par rapport aux objectifs de répartition élaborés par l’ÉRCFI [@interiorfrasercohorecoveryteamConservationStrategyCoho2006]. Dans la seconde approche, nous avons considéré deux hypothèses structurelles sur la relation géniteur-recrutement fondées sur @kormanEvaluationFrameworkAssessing2019 et @arbeiderInteriorFraserCoho2020, qui concernent la force de la densité-dépendance. La troisième approche reconnaît qu’une répartition adéquate des géniteurs entre les sous-populations peut être nécessaire à la persistance à long terme de l’UGS [@interiorfrasercohorecoveryteamConservationStrategyCoho2006], et qu’une contraction de cette répartition peut représenter un risque accru de disparition [@arbeiderInteriorFraserCoho2020]. Bien que les approches multidimensionnelles, comme l’explorateur de l’état du saumon du Pacifique, soient recommandées pour les évaluations de la PSS [@holtIndicatorsStatusBenchmarks2009], nous avons appliqué les deux autres approches (2 et 3) pour appuyer l’élaboration des PRL de l’abondance globale et pour avoir un point de comparaison avec l’explorateur des saumons. Même si les PRL d’abondance globale ne sont pas requis pour la gestion de la récolte de cette UGS, nous fournissons des PRL de régression logistique et de projection à des fins de démonstration. Les pêches du saumon coho du Fraser intérieur sont gérées en vertu d’un régime de gestion bilatéral entre le Canada et les États-Unis, décrit en détail à l’annexe IV, chapitre 5, du Traité sur le saumon du Pacifique.

Pour cette UGS, nous avons évalué la sensibilité des PRL fondés sur les abondances globales à la disponibilité des données à l’aide d’une analyse rétrospective en réestimant les points de référence au niveau des UC, les états des UC et les PRL au niveau de l’UGS chaque année en utilisant uniquement les données antérieures à cette année. Nous avons également mis en œuvre une analyse de sensibilité dans laquelle une ou deux UC ont été retirées des analyses de manière itérative et les points de référence au niveau de l’UC, les états des UC, les PRL au niveau de l’UGS et les états au niveau de l’UGS ont été réestimés. Nous avons également effectué des analyses de sensibilité liées aux hypothèses structurelles concernant la relation stock-recrutement lors de la dérivation des points de référence au niveau de l’UC pour les méthodes de PRL fondées sur l’état des UC et sur l’abondance globale.

Nous avons constaté que les PRL et l’état qui en découle étaient les plus sensibles aux hypothèses structurelles sur la forme de la relation stock-recrutement. Les PRL étaient moins sensibles aux méthodes de PRL ou à l’approche d’évaluation des UC (explorateur de l’état du saumon du Pacifique par rapport à un paramètre unique sur l’abondance des géniteurs par rapport à un paramètre unique sur la répartition) ou à l’ajout de plus d’années ou d’UC de données. Cependant, nous notons que pour les PRL de régression logistique, l’exclusion des UC a entraîné de plus grandes incertitudes quant à l’état au niveau des UGS, bien que les intervalles de confiance (IC) à 95 % de l’état se recoupent généralement avec l’état estimé en utilisant toutes les données. <!--CH: I removed all mention of status being more optimistic with fewer CUs. As we spoke about, this result is likely not generalizable for logistic regression based LRPS. -->

Pour cette étude de cas, nous avons également démontré l’approche consistant à faire la moyenne des incertitudes structurelles pour fournir un PRL de projection qui tient compte de cette incertitude. Un calcul de moyenne similaire est également possible pour les PRL de régression logistique.


## SAUMON CHINOOK DE LA CÔTE OUEST DE L’ÎLE DE VANCOUVER


L’UGS du saumon chinook de la COIV comprend trois UC [@holtbyConservationUnitsPacific2007], sept grands bras de mer (ou détroits) et 20 populations indicatrices d’échappée réparties dans les sept bras de mer et les trois UC. Les populations indicatrices d’échappée sont celles pour lesquelles on dispose de séries chronologique relativement complètes de l’abondance des géniteurs avec une méthodologie d’observation cohérente [@riddellReview2001Chinook2002; @pacificsalmoncommissionsentinelstockscommitteePacificSalmonCommission2018]. La mise en valeur des écloseries est une composante substantielle de plusieurs de ces populations <!--LW: changed from stocks-->, cependant, seules les populations indicatrices d’échappées sans mise en valeur significative des écloseries (INP $\geqslant$ 0,5) ont été incluses dans nos analyses (voir section \@ref(est-methods)). Puisque les séries chronologiques de la proportion de géniteurs provenant d’écloseries ne sont pas disponibles pour ces populations <!--LW: changed from stocks-->, les abondances totales de géniteurs ont été utilisées dans l’évaluation des états des UC et des UGS globales, ce qui peut entraîner des évaluations trop optimistes de l’état par rapport aux analyses excluant les poissons provenant d’écloseries (comme dans l’étude de cas du saumon coho du Fraser intérieur). L’abondance des géniteurs tend à être positivement corrélée entre les bras de mer de l’UGS, avec une corrélation moyenne de 0,28 (figure \@ref(fig:density-cor-plot)).


Pour le saumon chinook de la COIV, les bras de mer nichés dans les UC sont considérés comme une échelle spatiale importante de la biodiversité étant donné la séparation géographique des habitats de fraie entre les bras de mer et le faible nombre de saumons errants observé entre les bras de mer (D. McHugh comm. pers. Évaluation des stocks de la côte sud du MPO). Nous avons donc considéré les abondances de géniteurs à l’échelle des bras de mer au sein des UC en raison des échanges démographiques limités attendus à cette échelle spatiale.


Deux des trois UC de cette UGS, COIV-Sud et COIV-Nootka et Kyuquot, ont été évaluées comme étant dans la zone d’état rouge dans une récente évaluation intégrée de la Politique concernant le saumon sauvage [@dfoIntegratedBiologicalStatus2016]. Le saumon chinook de la COIV a été indiqué comme un stock préoccupant dans le plan de gestion intégrée des pêches (PGIP) de 2021 et un plan de rétablissement est en cours d’élaboration [@dfoSouthernSalmonIntegrated2021]. Le faible taux de survie des saumons chinooks de la COIV jusqu’à l’âge 2 et les faibles niveaux de géniteurs au cours des deux dernières décennies ont été soulignés comme étant des motifs de préoccupation sur le plan de la conservation dans le PGIP [@dfoSouthernSalmonIntegrated2021].


Les points de référence biologiques ont été estimés pour les populations indicatrices de la COIV à l’aide d’une relation empirique entre la superficie du bassin versant et deux points de référence biologiques stock-recrutement, G~REMP~ (abondance des géniteurs au moment du remplacement) et G~RMD~, basés sur une méta-analyse de 25 stocks de  saumons chinook en Amérique du Nord [@parkenHabitatbasedMethodsEstimate2006]. Le manque de données rigoureuses sur le recrutement des stocks de saumon chinook de la COIV empêche l’utilisation de points de référence basés sur le recrutement des stocks. Pour l’élaboration des PRL pour le saumon chinook de la COIV, la relation empirique entre la superficie du bassin versant et le G~REMP~ a été réestimée à l’aide d’un modèle hiérarchique bayésien [comme dans @liermannUsingAccessibleWatershed2010], et appliquée aux entrées du saumon chinook de la COIV. 

Nous avons caractérisé l’état des UC de deux façons pour cette étude de cas, en utilisant: 1) l’explorateur de l’état du saumon du Pacifique, 2) les abondances au niveau des UC par rapport à G~gén~ dérivées des estimations du modèle de bassin versant de G~REMP~ et de la productivité dérivée d’un modèle de survie spécifique au stade de vie avec l’avis d’experts. Nous avons calculé deux types de PRL: les PRL fondés sur l’état des UC et les PRL de projection. Selon des évaluations au niveau des UC, il n’y a pas eu d’années dans les données historiques où toutes les UC étaient au-dessus de la zone rouge; il n’a donc pas été possible de déterminer les PRL de régression logistique. Même si les PRL d’abondance globale ne sont pas nécessaires pour la gestion des prises de cette UGS, nous fournissons des PRL de projection à des fins d’illustration. Les pêches sont gérées en fonction d’une combinaison du régime de gestion bilatéral Canada-États-Unis indiqué dans le Traité sur le saumon du Pacifique et de la cogouvernance locale. Nous avons mis en œuvre des analyses de sensibilité sur les PRL de projection pour deux incertitudes clés: la variabilité de l’exploitation entre les bras de mer et la productivité intrinsèque. D’autres analyses explorant les répercussions de l’exploitation, la variabilité de la productivité intrinsèque et la capacité sont fournies à l’annexe D de @holtCaseStudyApplicationsInpress.

Nous avons constaté que l’état était cohérent entre les méthodes de PRL disponibles et avec une évaluation publiée précédemment. Cependant, les PRL de projection étaient très sensibles aux productivités sous-jacentes de la population. Bien que le PRL du scénario de base suppose une répartition relativement diffuse des productivités, conforme à la gamme des avis d’experts, les réductions (de 25 %) ou les augmentations (de 50 %) de la productivité dans les bras de mer ont entraîné des changements relativement importants dans les estimations des PRL. 


## SAUMON KÉTA DE LA CÔTE SUD INTÉRIEURE – SAUF LE FLEUVE FRASER

L’UC de saumon kéta de la côte sud intérieure (ci-après appelée « UC de saumon kéta de l’intérieur de la côte sud ») comprend sept UC de saumon kéta provenant de rivières qui se déversent dans le détroit de Johnstone et la mer des Salish le long de la partie continentale de la Colombie-Britannique et de la côte est de l’île de Vancouver. Les UC de saumon kéta frayant dans le bassin versant du fleuve Fraser sont exclues de cette UGS, car elles ont été classées dans une UGS distincte (saumon kéta de la côte sud intérieure – Fraser). Bien que ces deux UGS présentent un chevauchement important au niveau des pêches océaniques, elles ont été séparées en deux UGS en raison des différences observées sur le plan des pêches terminales et des habitats d’eau douce. @godboutStockStatusWild2004 ont relevé un état variable, mais stable dans les parties centrale et méridionale de cette UGS, avec des déclins dans le nord, en particulier dans la région définie par la composante UC des ruisseaux côtiers du sud. @holtEvaluatingBenchmarksBiological2018 ont trouvé des résultats similaires dans une évaluation provisoire de l’état selon la PSS. Les abondances de géniteurs ont tendance à n’être que très faiblement corrélées entre les UC pour cette UGS, avec une corrélation moyenne de 0,12 (figure \@ref(fig:density-cor-plot)). 

L’UGS du saumon kéta de l’intérieur de la côte sud est considérée comme limitée sur le plan des données. Bien que des séries chronologiques d’échappée soient disponibles pour de nombreux cours d’eau à partir de 1953, plusieurs séries sont incomplètes et nécessitent des hypothèses de comblement afin de produire un ensemble de données normalisées sur toute la série chronologique. La qualité des données de recrutement n’est pas suffisante pour estimer de manière fiable les paramètres des relations stock-recrutement en vue de leur utilisation dans les points de référence du stock-recrutement. Au lieu de cela, les points de références ont été calculés en tant que centile de la série chronologique historique de l’abondance des géniteurs au niveau de l’UC (centiles de référence) pour éclairer l’état selon la PSS, comme il est recommandé par @holtEvaluatingBenchmarksBiological2018. Nous avons retiré trois systèmes avec des niveaux élevés d’aménagement de l’UC du détroit de Georgia (un avec une grande production d’écloserie et deux avec des chenaux de fraie artificiels étendus). Les autres systèmes avaient un mélange de production d’écloserie relativement faible ou aucune production d’écloserie [voir @lynchAssessmentEnhancedChum2020]. Lorsqu’elles étaient disponibles, les estimations annuelles des géniteurs issus d’écloseries ont été retirées de l’abondance totale des géniteurs. 

Pour cette étude de cas, nous considérons deux approches pour caractériser l’état des UC: 1) l’explorateur de l’état du saumon du Pacifique et 2) une mesure unique sur les abondances de géniteurs utilisant des points de référence fondés sur le centile. Nous avons appliqué le PRL fondé sur l’état des UC et le PRL de régression logistique à cette étude de cas et évalué la sensibilité de l’état au niveau de l’UGS à partir du PRL fondé sur l’état des UC à diverses entrées de données. Nous n’avons pas été en mesure de générer des PRL de régression logistique fiables pour cette UGS, car les modèles de régression logistique ne s’ajustaient pas bien aux données, comme le montrent les diagnostics des modèles.


Nous avons constaté que les évaluations basées sur l’explorateur de l’état du saumon du Pacifique donnaient des résultats identiques à ceux du monomètre sur les abondances de géniteurs par rapport aux points de référence fondés sur le centile. De plus, comme pour le coho du Fraser intérieur, l’augmentation du nombre d’UC incluses dans les analyses a toujours donné lieu à des états plus pessimistes par rapport au PRL. 


