---
title: "Lignes directrices pour la définition des points de référence limites pour les unités de gestion des stocks de saumons du Pacifique"
author: |
  Carrie. A. Holt^1^
  Kendra Holt^2^
  Luke Warkentin^1^ 
  Catarina Wor^1^ 
  Brendan Connors^2^ 
  Sue Grant^3^
  Ann-Marie Huang^3^ 
  Julie Marentette^4^
author_list: "Holt, C.A., Holt, K., Warkentin, L., Wor, C., Connors, B., Grant, S., Huang, A.-M., and Marentette, J."
address: |
  ^1^Station biologique du Pacifique\
     Pêches et Océans Canada, 3190, chemin Hammond Bay\
     Nanaimo (Colombie-Britannique)  V9T 6N7\
  \smallskip
  ^2^Institut des sciences de la mer\
     Pêches et Océans Canada, Sidney (Colombie-Britannique), Canada\
  \smallskip
  ^3^Bureau régional de l’île d’Annacis\
     Pêches et Océans Canada, Delta (Colombie-Britannique), Canada\
  \smallskip
  ^4^Administration centrale nationale\
     Pêches et Océans Canada, Ottawa (Ont.), Canada\

french_address: |
  ^1^Station biologique du Pacifique\
     Pêches et Océans Canada, 3190, chemin Hammond Bay\
     Nanaimo (Colombie-Britannique)  V9T 6N7\
  \smallskip
  ^2^Institut des sciences de la mer\
     Pêches et Océans Canada, Sidney (Colombie-Britannique), Canada\
  \smallskip
  ^3^Bureau régional de l’île d’Annacis\
     Pêches et Océans Canada, Delta (Colombie-Britannique), Canada\
  \smallskip
  ^4^Administration centrale nationale\
     Pêches et Océans Canada, Ottawa (Ont.), Canada\

month: "July" # fill in
french_month: "Juillet"
year: 2023
report_number: nnn
region: "Région du Pacifique"
french_region: "Région du Pacifique"
citation_other_language: "Holt, C.A., Holt, K., Warkentin, L., Wor, C., Connors, B., Grant, S. et Huang, A.-M.. Guidelines for Defining Limit Reference Points for Pacific Salmon Stock Management Units. DFO Secr. can. de consult. sci. du MPO. Doc. de rech 2022/nnn. iv + 13 p."

french_abstract: |
  Les points de référence limites (PRL) définissent l’état du stock en deçà duquel on s’attend à ce que le stock subisse des dommages graves. Les PRL sont requis pour les principaux stocks de poissons, ou unités de gestion des stocks (UGS), qui sont prescrits par règlement en vertu des modifications apportées à la *Loi sur les pêches* (2019) du Canada. Les saumons du Pacifique sont uniques parmi les stocks de poissons marins en raison de leur haut niveau de diversité intraspécifique, ce qui donne lieu à un large éventail de données disponibles, de considérations et d’approches pour les évaluations et l’élaboration du PRL. Dans ce document, nous présentons six principes pour l’élaboration de PRL pour le saumon du Pacifique, qui sont adaptés de principes utilisés plus largement parmi les espèces marines. Un principe propre au saumon du Pacifique est que les PRL doivent être harmonisés avec l’objectif de la Politique concernant le saumon sauvage (PSS) du Canada de préserver la biodiversité du saumon à l’échelle des unités de conservation (UC), qui sont souvent imbriquées dans les UGS. Nous avons élaboré des méthodes de calcul des PRL et établi des lignes directrices sur la manière de les mettre en œuvre, y compris les conditions dans lesquelles elles doivent ou ne doivent pas être appliquées. Nous proposons que les PRL soient déterminés à partir de la proportion d’UC dont l’état est supérieur à la zone rouge pour les évaluations de l’état prévues par la PSS, comme approche par défaut. Cela permet d’assurer une certaine cohérence avec les évaluations de l’état déjà produites dans le cadre de la PSS, et peut éclairer les décisions de gestion concernant la récolte, l’habitat et les écloseries qui se prennent souvent à des échelles plus fines, celles des UC. Pour compléter l’approche par défaut, nous fournissons des PRL fondés sur des mesures d’abondances agrégées (globales) pour l’ensemble de l’UGS, ce qui peut être nécessaire à des fins de gestion des pêches dans certains cas. Ces derniers PRL sont dérivés pour avoir une probabilité souhaitée que toutes les UC composantes soient au-dessus de l’état rouge étant donné une relation supposée entre l’abondance globale et la probabilité que toutes les UC soient au-dessus de l’état rouge. Nous cernons les incertitudes associées à chaque approche, et décrivons comment elles peuvent être appliquées à une gamme de types, de qualités et de quantités de données. Les analyses visant à soutenir l’élaboration de lignes directrices se sont appuyées sur trois études de cas : le saumon coho du Fraser intérieur *Oncorhynchus kisutch*, le saumon chinook de la côte ouest de l’île de Vancouver, *O. tshawytscha*, et le saumon kéta de la côte sud intérieure, *O. keta*, à l’exclusion du fleuve Fraser.
  
header: "" # or "" to omit
output:
 csasdown::resdoc_pdf:
   french: true
   copy_sty: true
   line_nums: false
   line_nums_mod: 1
   lot_lof: false
# ------------ resdoc_word or resdoc_pdf
# End of options to set
knit: bookdown::render_book
# knit: (function(input, ...) {
#        csasdown::render('_bookdown.yml')
#       })
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
  -  \usepackage{amsmath}   \usepackage{tcolorbox} \usepackage{tikz} \usetikzlibrary{shapes, arrows.meta, shapes.arrows, shapes.geometric, positioning}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if(length(grep("pdf", names(meta)))){
  french <- meta$`csasdown::resdoc_pdf`$french
  prepub <- meta$`csasdown::resdoc_pdf`$prepub
}else if(length(grep("word", names(meta)))){
  french <- meta$`csasdown::resdoc_word`$french
  prepub <- meta$`csasdown::resdoc_word`$prepub
}
csl <- "csl/csas.csl"
if(french){
  csl <- "csl/csas-french.csl"
  options(OutDec =  ",")
}

# add other packages here:
library(dplyr)
library(readr)
library(tibble)
library(csasdown)
```

---
csl: `r csl`    
---
