
# GUIDELINES FOR APPLYING LRPS {#guidelines}

<!--CH: could change list level as this next section is the only one at that level, but then need to capitalize all level 2 title
CW: CSASdown automatically capitalizes the titles and subtitles according to the rules - see below:
-->
## STEPWISE APPROACH FOR SELECTING LRPS

We recommend a step-wise approach for identifying LRPs, with the proportion of component CUs with status above red as the default method. Aggregate abundance-based LRPs are presented as an option for cases in which they are required for fisheries management (e.g., local or international), but are considered supplemental to the proportion of CUs with status above red. The step-wise approach considers data availability for candidate LRP methods and provides guidance when inconsistencies in status occur from applying multiple LRP methods. These steps can be adapted in the future as more methods are developed and/or these methods are further evaluated.

### Data Availability and Spatial Scale (Step 1)


The first step is to compile CU-level data to support biological status assessments as described under the WSP [@holtIndicatorsStatusBenchmarks2009a; @holtEvaluatingBenchmarksBiological2018], where those data exist. These data include (but are not limited to) time-series of spawner abundances, recruitment, hatchery contributions, productivity, and biological benchmarks on spawner abundances.   This step generally includes aggregating fine scale data on streams or spawning sites to the CU level. 

In some cases, finer spatial scales than CU (e.g., watersheds or subpopulations within CUs) may be considered to delineate serious harm to the SMU. Although CUs are the population unit of assessment and conservation required under the WSP, the distribution of spawning within CUs (e.g., among watersheds) can be an important component of status [@holtIndicatorsStatusBenchmarks2009a] and these finer scales can be considered. 


Distribution is a commonly cited component of salmon viability and recovery [@mcelhanyViableSalmonidPopulations2010]. When applied to the identification of recovery targets for Pacific salmon, @bradfordReviewBiologicalPrinciples2004 defined the relevant scale of distribution as spatial units that are demographically independent such that the  population dynamics of one unit are unlikely to affect the dynamics of another, but that genetic exchange is expected to occur at greater rates than observed among populations (CUs), and would likely exceed 10 effective migrants per generation. When applying these criteria to Interior Fraser River Coho salmon, @bradfordReviewBiologicalPrinciples2004 defined subpopulations on the basis of large watersheds or lakes, or partial barriers to migration. 

We recommend that the decision on spatial scale of conservation for biological assessments be part of the peer-review process for CU and SMU assessments, and be based on biological principles of conservation and viability (e.g., as reviewed in @bradfordReviewBiologicalPrinciples2004 and @mcelhanyViableSalmonidPopulations2010). 


Within this step, information on hatchery enhancement is used to identify populations where production is dominated by hatchery-origin fish.  Populations in which production is dominated by hatchery-origin fish (defined as PNI values < 0.5) should be excluded from analyses, while those that are dominated by natural-origin fish (PNI values are $\geqslant$ 0.5), should be included in analyses.  These thresholds are based on guidelines established by [@withlerGeneticallyBasedTargets2018]. Further, where time-series of the proportion of marked fish on the spawning grounds are available and production is dominated by natural-origin fish, these proportions can be used to identify time-series of natural-origin recruitment for benchmark estimation and natural-origin spawners for status assessment against benchmarks. When the influence of hatchery production is removed in this way, the assessments are less sensitive to annual variation in hatchery practices.  

Infilling among streams or spawning sites for years with missing data is commonly used when compiling CU-level spawner abundance series. When infilled time series are used to estimate LRPs and monitor stock status relative to LRPs, consideration should be given to the scale at which infilling is done at. For example, if LRPs are based on maintaining CU-level (or inlet-level) diversity, infilling of missing data should not be based on escapements from outside of the CU (or inlet). In addition, hatchery enhancement should be carefully considered when infilling to avoid overestimating abundances when infilled numbers are based on sites that are artificially enhanced, to the extent possible. 

<!--KH:

I am wondering if it would be relevant to include mention of infilling here.  Or, maybe in the next step 2?  Luke uses it for Chum, but it is not used for Chinook (likely because of complications with hatchery enhancement).  I also think that stream-level infilling was done for some of the coho data before I received it. I did add an edit to the case study paper that said to refer to the guidlines paper on infilling guidelines, so let me know if it isn;t relevant to the guidelines paper, and I will remove the case study paper reference.

Maybe adding a paragraph along the lines of:

Infilling among streams or spawning sites for years with missing data is commonly used when compiling CU-level spawner abundance series. When infilled time series are being  LRPs and monitoring stock status relative to LRPs, consideration should be given to the scale at which infilling is being done at.  For example, if LRPs are based on maintaining CU-level (or inlet-level) diversity, infilling of missing data should not be based on escapements from outside of the CU (or inlet). Similarly, for CUs with moderate or high hatchery enhancement and / or straying among sites of hatchery fish, infilling should not be done among sites with varying levels of hatchery enhancement.  (KH: is this the best way to say this?  Are there other ways)      

CH: added, rewording the last sentence. Does it look okay? I think avoiding strays is pretty hard, and may be  as much a genetic concern as a demographic numbers concern.

KH: Looks good. I agree on strays.
-->


  
### Assessing Data Deficiency (Step 2)

Second, CUs with data to support biological assessments are identified. CUs are assessed based on a variety of metrics including abundances and trends, and are considered data deficient when data or benchmarks are insufficient on all metrics for assessments under the WSP [@holtIndicatorsStatusBenchmarks2009a]. For example, CUs are only considered data deficient when data to assess temporal trends in spawner abundances (over at least 3 generations) and data on current spawner abundances and associated CU-level abundance benchmarks are missing or insufficient. As a general guideline, we define current spawner abundances as the geometric average spawner abundances over the most recent generation, where data are insufficient on abundances if there are no data in the most recent generation. For short-term trend analyses, data are considered insufficient if they include less than half of available years in the last three generations or are of low quality representing only presence/absence. These criteria for trend detection are similar to criteria described in @brown2020SummaryAbundance2020  and applied to spawning sites of Chinook Salmon in Southern BC. 


CU-specific benchmarks on spawner abundances can be derived from spawner-recruitment models, percentiles of spawner time-series, or habitat characteristics. Data requirements for benchmark estimation on spawner abundances differ according to the methods applied and are not explicitly defined here. For example, spawner-recruitment benchmarks developed from hierarchical multi-stock models require fewer years of data than those based on individual stock-recruitment models. In addition, changes in environmental conditions over time may result in historical data that are no longer representative of current conditions, resulting in data deficiencies. Local biological expertise is required to review available data and benchmarks prior to assessments to identify data deficiencies.

In addition, a CU may be data deficient if data to resolve the existence of the CU is insufficient. For example, @holtbyConservationUnitsPacific2007 describe provisional CUs pending acquisition of genetic samples to differentiate them from neighbouring CUs. Further work ground-truthing, expanding, and updating these guidelines for data deficiencies in the context of different salmon species, life-histories, and assessment metrics is warranted. 


### Can Data Deficient CUs be Represented by CUs With Data? (Step 3)
<!-- CH comment: send this section to Diana Dobson and Brendan for review-->

Third, the extent to which status of data deficient CUs can be inferred from CUs with data is evaluated. By definition, data deficient CUs do not have data on population dynamics to rigorously evaluate this inference through SMU-specific correlation analyses, though information on threats and biological characteristics may be available. To infer status for data deficient CUs, at a minimum we recommend providing evidence that: (i) the threats impacting data deficient CUs are likely to be the same as for CUs with data and their magnitudes are similar,  (ii) environmental drivers are similar among CUs, e.g., as reflected by the distribution of CUs across freshwater and marine ecosystems, (iii) biological characteristics, such as life-history type and dominant age-at-maturity of data-deficient CUs are represented in the CUs with data, and (iv) population capacity of data deficient CUs is likely in the range of those represented by CUs with data. Evidence supporting these criteria should be clearly documented and reviewed by local experts. The burden of proof would be to identify that data deficient CUs have similar properties to neighbouring CUs, with the default assumption that each CU represents unique biodiversity where status and trends cannot be represented by other CUs. We describe the four criteria in more detail below.


**Threats** are defined here as any human activity <!-- Luke: could this also include natural processes and hazards (e.g., landslides)? Some processes could be not directly linked to human activity (e.g., scouring floods) but could be exacerbated by human activity (logging, climate change). CH: I took this defn directly from SARA, so would prefer to keep as is for now-->or process that causes harm, death, or behavioural changes to a species, or the destruction, degradation, and/or impairment of its habitat, to the extent that population-level effects occur [@dfoGuidanceAssessingThreats2014]. Information on threats may be derived from published threats and habitat assessments, and may incorporate harvest, effects of land-use in freshwater and estuarine habitats, climate change, and genetic impacts from hatcheries. Because SMUs are defined as groups of CUs that are managed together with the objective of achieving a joint status, it is likely that CUs within an SMU will have similar vulnerabilities to fisheries. Data on genetic stock identification from fisheries can be used to further assess similarities in vulnerabilities in harvest. Beyond fisheries, CUs that are vulnerable to different threats in freshwater and marine environment within an SMU may have divergent statuses and trends.  

Although SMUs are usually defined to be spatially cohesive groups of CUs, SMUs and their component CUs can vary in **environmental conditions**,  related to variability in freshwater and marine ecosystems,  macroclimate, and hydrology within an SMU. CUs containing unique environmental conditions may diverge in status and trends from neighbouring CUs, either due to the different environmental drivers or the interaction of the different environments with anthropogenic threats. <!--LW: could probably use some more refs here to strengthen the logic. I will look for some--> @holtbyConservationUnitsPacific2007 used freshwater ecological drainage units [@ministryoftheenvironmentEcologicalAquaticUnits2021] to differentiate freshwater ecosystems for Pacific salmon ("Freshwater Adaptive Zones", FAZs). These FAZs account for differences in climate conditions, river gradient, hydrology and connectivity. They consist of salmon populations with shared zoogeographic histories at relatively fine spatial scales. In some cases neighbouring CUs share a common FAZ (e.g., WCVI Chinook Salmon), but more often CUs tend to be associated with unique FAZs and therefore they may be less useful for identifying similarities in environmental conditions among CUs. Other levels of aggregation of ecological drainage units could be developed in the future to inform similarities in freshwater conditions among CUs.

In addition, variability in hydrological regime (the typical pattern of annual river flow) within an SMU and the macroclimate of spawning and rearing areas can impact salmon behaviour and survival. For example, for Chinook salmon, the hydrological regime of their home rivers is correlated with return age, life-history type, and spawn timing, and thus their exposure to various threats [@beechieHydrologicRegimeConservation2006]. Broad similarities in macroclimate can be represented by biogeoclimatic zones, defined as "geographic areas having similar patterns of energy flow, vegetation and soils as a result of a broadly homogenous macroclimate" [@medingerEcosystemsBritishColumbia1991], which vary across CUs within SMUs.<!--remove; (BC Ministry of Forestry 2021, https://www.for.gov.bc.ca/hfd/library/documents/glossary/Glossary.pdf). In other words, these terrestrial zones have relatively uniform climate and vegetation. There are approximately 18 biogeoclimatic zones in BC and the Yukon, ranging from Coastal Douglas-Fir on southeastern Vancouver Island to Boreal White and Black Spruce in northern BC. --> CUs with spawning and rearing grounds within different biogeoclimatic zones may experience different macroclimates and hence environmental drivers in estuaries and freshwater. Overall, we recommend using a combination of variables (e.g., FAZs, hydrological regimes, and biogeoclimate zones) when identifying similarities in freshwater conditions among CUs.


To identify similarities in environmental conditions in the nearshore marine environment, @holtbyConservationUnitsPacific2007 describe Marine Adaptive Zones, MAZs, for Pacific salmon which reflect "watershed-coastal ecosystems of distinct physical characteristics, including the full sequence of riverine, estuarine, and near-short marine habitats used by juvenile anadromous salmonids". There are 12 MAZs for Pacific salmon in BC and the Yukon, ranging from the Strait of Georgia in the south to the Bering Sea in the north (COSEWIC, in press)^[COSEWIC. Designatable Units for Chinook Salmon *Oncorhynchus tshawytscha* in Canada, In Press].




CUs with similar **life-history characteristics** are more likely to respond to common threats and environmental drivers in the same way compared with those with divergent characteristics. For example, Chinook Salmon exhibit at least two distinct life-histories, named stream and ocean types. Stream-type fish rear for more than a year in freshwater and tend to migrate far offshore during their marine stage, whereas ocean-type fish migrate to the ocean as subyearlings (< 1 year) and tend to remain near shore during marine life. These different emigration patterns are believed to have evolved as a consequence of differences in food resources and survival rates in the freshwater and marine environments [@bourretDiversityJuvenileChinook2016], and result in different vulnerabilities to physical and biological conditions in those environments.  Therefore, CUs with different life-history characteristics may experience different status and trends, and may be less appropriate for inferring status under data deficiencies. In some cases, SMUs have been defined to account for differences in life-history in order to better achieve joint status under common management regime (e.g., Fraser Chinook where SMUs are defined in part based on dominant ages at maturity). In other SMUs, CUs with various life-history types are combined (e.g., the Mainland Inlet Chinook SMU which contains CUs with ocean and stream-type fish)<!--CH: to confirm with Diana and Ron. CU34-HOMATH (ocean-type) and CU35-KLINA (stream-type) both in Mainland Inlets CK SMU-->.

CUs with very different **population capacities** may respond differently to similar threats. For example, very small CUs may be more vulnerable to moderate fishing pressure if abundances drop below critical conservation thresholds (e.g., 1500 fish, an abundance threshold within the Pacific Salmon Status Scanner), whereas very large CUs may be more resilient to common threats.    <!--CH: I think about COSEWIC criteria which identify DUs < 1000 as Threatened, and also DUs < 10,000 with declining trend as Threatened. For Pacific salmon, the habitat capacity of CUs can span this range (<1000 to >10,000) making some CUs inherently more vulnerable than others, presumably.-->
<!--CW: I believe Luke also saw this effect in the Chum study case - i.e. smaller CUs were more likely to be below their benchmarks.-->


<!--KH: Do we know what the 1500 used in the salmon scanner tool was based on? Was it a result from the decision tree analysis?  Or, was it picked a priori as a threshold based on some other rationale?  I'm wondering if it makes more sense to use the COSEWIC 1000 fish threshold for this example if it's somehow more firmly rooted in conservation theory / literature as a criticical threshold?  I'm not sure on this - just a thought.  
CH: I agree, and pushed SoS on this point. However, the wSP assessments show that experts tended to designate a CU as red when abundances dropped below 1500 not 1000. This does make some senes if there supposed to be a buffer between lower benchmark/red status and extinction risk. So, I suggest we leave it for now.

-->


Covariation in productivity is well documented among spatially proximate populations across species [@petermanPatternsCovariationSurvival1998; @pyperSpatialCovariationSurvival2002; @dornerSpatialTemporalPatterns2018], providing some support for the use of data-rich CUs to inform CUs without data. In a meta-analysis of spawner time-series across Pacific salmon species throughout BC using data extracted from the Pacific Salmon Explorer Tool [@pacificsalmonfoundationMethodsAssessingStatus2020],  pairwise correlations in spawner abundances among CUs within SMUs tended to be positive for Pink, Chum, Coho, and Sockeye Salmon (Appendix app:meta-analysis-appendix, Figure \@ref(fig:lrp-smu-corr-plot)). For Chinook Salmon, correlations were more variable among CUs and sometimes negative, in part due to the influence of hatchery production in some of those systems. <!--CH: The 2 SMUs with negative correlations are Georgia Strait Chinook and Johnstone Strait/Mainland Inlet Chinook which have significant hatchery production, and my read of PSE report looks like they used total spawners, not natural-origin spawners--> A pervasive problem with correlation analyses for Pacific salmon is that populations with available time-series tend to be more heavily managed and may not be representative of those without data which tend to be remote and without direct management interventions. <!--CH remove: In addition, the four criteria described have not been accounted, and so correlations may be biased low.--> 

Overall, we suggest caution when representing SMU status with only a subset of CUs, and recommend evaluating and documenting the risks of incorrectly assigning status of data deficient CUs based on neighboring CUs. We also recommend further quantitative evaluation of these criteria using empirical data disaggregated into groups of CUs with similar environmental conditions, life-history types and management intensity, among other variables, and supported by simulation evaluation.  These criteria are not meant to be prescriptive, but to provide general guidelines for assessing possible inference for data deficient CUs. 

If data-deficient CUs do not meet the criteria for inference from the remaining CUs within an SMU, we recommend collection of CU-level data to inform biological assessments. Data collection would therefore be prioritized for CUs that diverge in threats, environmental drivers, life-history capacities and/or habitat capacities from neighbouring CUs. 

<!--KH: If there are data defieicnt CUs that do not meet criteria for inference, do we recommend that the SMU be designated data deficient, in which case status against an LRP cannot be estimated?  If so, could we desrcibe this by replacing the above paragraph with:  

If data-deficient CUs do not meet the criteria for inference from the remaining CUs within an SMU, SMU status relative to an LRP cannot be assigned. In this case, the entire SMU should be designated as data deficient, with a recommendation to collect CU-level data to inform biological assessments. Data collection would therefore be prioritized for CUs that diverge in threats, environmental drivers, life-history capacities and/or habitat capacities from neighbouring CUs. 
CW: I am uneasy about determining a SMU DD if we are missing data for one CU. Ad I think we contradict that on the section on interim stats below.  We could still assess the remaining CUs and come up with a below LRP or "interim above LRP" status. -- This would be in line with the PA policy recommendation that lack of data should not be used as justification for lack of management action.

CH: I think we've landed on an SMU is DD only if status is amber/green on data-rich CUs and status of data-deficient CUs cannot be inferred from other data-rich CUs. We describe this in Step 6 (assessing status on ppn-based LRPs. okay??). 

As an aside. I wonder if we need a table to show these 4 options from combinations of : status of DD CUs can or cannot be inferred from other CUs, and status of data-rich CUs are all above red status or at least one has red status.

-->

### Proportion of CUs Above Red Status Required to Avoid Serious Harm (Step 4)

@dfoFisheryDecisionMakingFramework2009 indicates that LRPs are based on biological criteria identified by Science, independent of management processes. Given the goal of the WSP to protect the biodiversity of Pacific salmon in part by maintaining CUs above lower biological benchmarks, we have identified 100$\%$ of CUs as an LRP that will avoid serious harm. Exceptions to this may occur where there is uncertainty or mis-identification in the delineation of CUs (e.g., as for some transboundary CUs @holtbyConservationUnitsPacific2007) or CUs are designated extinct. Those CUs would be omitted from the total number of (extant) CUs within the SMU. <!--LW: question, so if a CU goes extinct it doesn't count in the 100% LRP for the SMU anymore? Wouldn't a CU going extinct represent serious harm/impaired productivity?- CH: but when it's extinct by definition it can't be recovered so a rebulidng plan is moot; unlike extirpated or critically endangered. CH: if it's extinct it cannot be rebuilt by definition. I think out goal is to  assess serious harm on extant CUs. Proof of extinction takes a long time (.e., 30-50 years under COSEWIC), so I don't think this the case for many; Until it's designated extinct it would still be considered serious harm. -->This step does not include decisions about how to prioritize CUs for conservation under growing threats, including climate change. <!--LW: unclear whether this sentence is saying that you don't need to do a cost-benefit analysis or whether that is part of another step, or that we didn't do this. Also the phrase of 'if only a portion can be conserved under growing threats, including climate change' has a lot wrapped up in it. Seems like there is unwritten context about history and how much we can do to preserve stocks, and what measures could be taken (moratoriums?) vs. what would actually be done. Suggest removing that phrase or clarifying. Removing CUs for this reason seems like a cultural/value idea than based off serious harm. I'm thinking about CUs/populations that could have been in 'serious harm' category for many decades, from a biological perspective they have just been below LRP for a long time. Does that justify disregarding them? Has this come up at TWG meetings?  CH: changed wording to omit, if only a portion can be conserved. This did come up in TWG mtgs, but we can't make those decision here.-->Those decisions would require collaboration with various sectors involved in the management of the SMU, beyond those involved in the science-based process of identifying LRPs. Some CUs may be naturally more vulnerable to threats because of their biological or population characteristics (e.g., due to small habitat capacities), however, that natural vulnerability does not diminish the serious harm associated with the biodiversity loss if that CU is lost in the face of ongoing threats. <!--CH: this last sentence is meant to get at the possible exemption of CUs that are naturally at low abundance and "red". The counter argument I heard at the TWG meeting was that those CUs still have ongoing threats and so separating 'natural' vulnerability from threats that deplete a CU is tricky, and probably too hard for us to attempt. And the loss of any CU is serious harm.".-->  In addition, for some CUs the potential for rebuilding to above the red zone may be extremely low. These considerations should be identified in a rebuilding potential analysis to prioritize where resources should be allocated in a rebuilding plan (e.g., @carwardinePriorityThreatManagement2019)<!--LW: I like this point, in light of above comments it distinguishes the setting of LRP at 100% of CUs (which might trigger LRP based on very low abundance CUs which might be at very low probability of recovery based on current/future conditions) vs. the rebuilding plan which can then weigh practicality of recovery. I think this is an important distinction-->.  Considerations on rebuilding potential should be part of the management objectives [@kronlundConsiderationsDesignRebuilding2021] but are outside scope of identifying LRPs.

Furthermore, unlike many other marine fisheries, threats and management levers for Pacific salmon extend beyond those associated with fisheries that underlie the definition of SMUs and LRPs. The scale of SMUs is often incongruent with the scale of dominant threats and management levers so that LRPs based on 100$\%$ of CUs being above red status may trigger the development of rebuilding plans under Fish Stock provisions when only a component (e.g., a single CU) requires intervention that are not related to harvest (e.g., hatcheries or habitat amelioration).  Nevertheless, we have identified 100$\%$ of CUs within the SMU should be above their benchmarks to avoid serious harm under the Fish Stock provisions; triggers and interventions at finer and coarser spatial scales will also be essential to sustain Pacific salmon.<!--CH: This is meant to capture the concern that we might trigger RP when CU is already being managed in other ways, and at a different scales-->


Once LRPs are identified, SMU-level objectives can be specified and nd management procedures can then be evaluated to identify those approaches that best meet objectives, including the prioritization of CU-specific interventions. Furthermore, objectives and management actions can be adapted to a range of spatial scales from CU to regional or multi-SMU scales and then evaluated in a hierarchical context. The proposed LRP presented here of 100$\%$ of component CUs above the red status within an SMU is a first step in that process.


### Assess Status Relative to Proportion-based LRP (Step 5)

The status of individual CUs is assessed and the proportion of CUs with status above red is then compared to the LRP of 100% identified from step 4.  Where available, we recommend applying CU assessments from recent peer-reviewed WSP Integrated Status Assessments, in which multiple metrics, such as abundances and short- and long-term trends, are integrated to assign CU status within an expert-driven process [@holtIndicatorsStatusBenchmarks2009a; @dfoWildSalmonPolicy2015; @dfoIntegratedBiologicalStatus2016; @grant2017FraserSockeye2020]. Here we define recent as within the most recent generation as a general guideline, though major perturbations such as landslide events may make even recent assessments unrepresentative of current conditions if the impact of those events are not accounted for. <!--CH remove: Over time-periods longer than a generation, the extent to which the assessment is still representative depends on the dynamics of the specific system.-->


Because WSP Integrated status assessments are resources-intensive processes involving large groups of experts over multiple days [@grantIntegratedBiologicalStatus2013] and are not available for most CUs, we demonstrate the application of the Pacific Salmon Status Scanner, which is a tool developed by DFO's State of the Salmon Program to rapidly assess CU status under the WSP multidimensional assessment framework (Pestal et al. in prep). More details on this approach are provided in Section \@ref(cu-est-methods) and our companion working paper (Holt et al. in review). Within this framework, CU status depends on a variety of population metrics, where the choice of metrics depends on data availability and may differ among CUs within an SMU. The Salmon Scanner integrates status on available metrics to derive an overall status that is comparable among CUs. 

**Interim status**

Given a proportion-based LRP of 100% of CUs above red status, when data deficient CUs are represented by CUs with data we refer to resulting status as 'interim' when all CUs included in assessment are above red status (Table \@ref(tab:GuidanceDDCUs)). This 'interim status' is provisional until all component CUs can be assessed. In some cases natural variability alone may result in differences in status and trends even if the four criteria listed above are met, which underscores the value of monitoring and assessing all component CUs. Where data deficient CUs are not represented by CUs with data, and all CUs included in the assessment are above red status, then the SMU is considered data deficient and SMU status cannot be evaluated. In both cases, we recommend improved monitoring to fill CU-level assessment gaps.

When data are missing for one or more CUs, and at least one of data-rich CUs have red status, the LRP of 100% CUs above the red zone is considered breached, regardless of whether the data-deficient CUs are represented by data-rich CUs or not <!--(Table \@ref(tab:GuidanceDDCUs2))-->. A breach of the LRP (i.e., at least one CU with red status) can be used to trigger a rebuilding plan under the Fish Stock provisions since the improved monitoring of data-deficient CUs alone will not result in an increase in SMU status to 100% (all CUs above red status). Further monitoring of data-deficient CUs is still warranted in this case to inform status of remaining components of the SMU and associated rebuilding efforts. 



\renewcommand*{\arraystretch}{1.6}
\begin{longtable}[]{p{5cm} p{3.5cm} p{3.5cm}}
\caption{Guidelines on assessing status for proportion-based LRPs of 100\% of CUs being above red status, when at least one CU is data-deficient}\\
\hline
 & Status of data-rich CUs: all above red status &  Status of data-rich CUs: at least one red status \\ 
\hline
\endhead
Status of data-deficient CUs can be inferred from data-rich CUs  &  Interim SMU status above LRPs & SMU Status = below LRP\\
Status of data-deficient CUs {\it cannot} be inferred from data-rich CUs  &  SMU Status = Data Deficient & SMU Status = below LRP\\

\hline
(\#tab:GuidanceDDCUs)
\end{longtable}



<!--
+--------------------------+-------------------------+-------------------------+
|                          | Status of data-rich CUs:| Status of data-rich CUs:                         
|                          | all above red status    | at least one red status 
+==========================+=========================+=========================+
| Status of data-deficient | Interim SMU status=     | SMU Status = below LRP  
| CUs can be inferred from | above LRP               |                         
| data-rich CUs            |                         |                         
+--------------------------+-------------------------+-------------------------+
| Status of data-deficient | SMU status = data-      | SMU Status = below LRP  
| CUs cannot be inferred   | deficient               |                         
| from data-rich CUs       |                         |                         
+--------------------------+-------------------------+-------------------------+


Table: (\#tab:GuidanceDDCUs2) Guidelines on assessing status for proportion-based LRPs of 100\% of CUs being above red status, when at least one CU is data-deficient. 

-->

<!--CW: From the PA Policy:

"In resource management, the PA is, in general, about being cautious when scientific information is uncertain, unreliable or inadequate and not using the absence of adequate scientific information as a reason to postpone or fail to take action to avoid serious harm to the resource."
But also:
"In data deficient cases, priority should go to monitoring the stock and establishing data time series to support the identification of an LRP. When developing reference points efforts should be made to take into consideration the range of factors which may affect the productivity of the stock including changes in ocean conditions, where information is available."

The PA policy also suggests that when a stock is DD, a meta analysis approach should be used to set LRPs (see annex 1b). 

This may be a bit out there but: maybe we could suggest the establishment of a data collection plan that would be analogous to the recovery plan but to address data deficiency. -This plan would include a list of data that could be collected (e.g. monitoring of spawning grounds, establishment of genetic markers, catch sampling, ageing, etc.) and potential costs associated with everything? -- Also this plan could clearly indicate if spawning grounds are too remote, inaccessible, or too costly to monitor. -- I think that having that kind of information documented would go a long way in establishing priorities. 

LW: I agree, that would be useful!
-->



### Peer-review Assessments of Status Relative to Proportion-based LRP (Step 6)
<!--CH comment: this section needs input from Sue-->

We recommend peer-review of the CU data and assessments used in steps 1 and 5 if CU assessment are developed outside of an existing published, peer-reviewed process. Also, we recommend peer-review of decisions on SMU-scale aggregation from steps 2, 3 and 4. This peer review can occur, at least in part, through DFO's State of the Salmon Program's annual implementation of the Pacific Salmon Status Scanner. The Salmon Scanner will be applied annually as part of of a process integrating outputs with local expertise to provide provisional statuses for CUs. Expert review is required to vet statuses derived from the implementation of the Salmon Scanner to ensure they are consistent with underlying biological categories given the multiple and sometimes conflicting dimensions of status. <!--CH: Ann-Marie suggested an example from Fraser Sockeye Shuswap here, but I wonder if it might make the flow of this section awkward? Happy to consider an inclusion from Ann-Marie--> The outputs from that process can be used as a basis for developing CU-level statuses to inform SMU-level LRPs. We emphasize the importance of rigorous peer-review of LRPs and status assessments against them for those SMUs prescribed under regulation, either as part the annual application of Salmon Scanner or in a separate SMU-specific  peer-review process. This peer review process would include assessment of component CUs and decisions about data deficiencies and CU representativeness covering steps 1-5 above, and be documented in a CSAS Research Document, CSAS Science Response, and/or CSAS Science Advice Report.<!--CH question: Is this requirement for CSAS documentation okay? We should ask Julie/Jason to what extent this is consistent with out marine species, and then mention the consistency here. Some TWG participants suggested LRP identification could occur in the rebuilding plan, but this seems awkward as rebuilding objectives may be related to LRPs, or at least they will in other species, so best to keep the 2 processes separate I think.
CW: Agree with keeping rebuilding plan and LRP separate. 
LW: I agree as well.-->



<!--KH comments on above paragraph: 

1) Also agree that LRPs need to be defined seperate from a rebuilding plan.   

2) It seems to me that the following sentences from above are saying that SMU-level CSAS reviews are not needed if CU statuses for all CUs within an SMU are reviewed through the annual SOTS expert review:

"The outputs from that process can be used as a basis for developing CU-level statuses to inform SMU-level LRPs. For CUs or SMUs not included or not fully reviewed in that annual process and where SMU-scale LRPs are required under the Fisheries Act, we recommend a separate SMU-scale peer-review process that includes assessment of component CUs and decisions about data deficiencies and CU representativeness, covering steps 1-5."

Is this the intention?  It seems to contradict the following statement that 

"When used to support decisions under Canada's Fisheries Act, the steps involved in LRP development should be documented in a CSAS Research Document, CSAS Science Response, and/or CSAS Science Advice Report."

Because it still seems a bit unknown what annual expert SOTS reviews will look like (i.e., to what extent will external participants be involved), perhaps we should just highlight the importance of peer-review, and note that whether the SOTS annual process will be enough to meet that bar is still uncertain.  (This is just a thought though; i'm open to other options too)

CW: I have the same question as Kendra, I thought Sue mentioned that the SOS assessments would not entail a CSAS? 
Although, since we do not know what the SOS process will look like, it may be useful to suggest it goes through CSAS? I think it would be ideal that at least a SAR gets generated form the annual assessments. That would be consistent with stock assessments for other species. 

CH: revised accordingly. Does this revised text capture it?
-->

<!--SG comment: if status is approximated with the algorithm and the status on the metric is red, this could trigger an integrated status assessment to derive a formal WSP status prior to triggering LRP. -->

The frequency of SMU-scale peer reviews outside of the annual implementation of the Salmon Scanner will depend on variability in CU-level population dynamics over time and how LRPs and SMU-level assessments are used to inform decision making (e.g., if an SMU is batched under the Fisheries Act), among other factors. In the future, management procedures with various frequencies of assessments could be evaluated in a simulation framework to identify risks of delaying assessments relative to costs of implementing them. 

### Are Aggregate Abundance-Based LRPs Required For Fisheries Management? (Step 7)

Although proportion-based LRPs may meet requirements under the Fish Stock provisions for Pacific salmon, abundance-based LRPs may be needed for fisheries management decision making (see Section \@ref(roleLRPs)).  For SMUs where harvest at the aggregate scale is a dominant driver of population dynamics and restricting fisheries harvest is a principle lever, an LRP along the metric of aggregate abundances of the SMU may support precautionary management. For example, when LRPs are used to inform a harvest control rule, fishing pressure can be gradually curtailed as aggregate abundances drop towards the LRP to avoid depletion below it. Aggregate abundance-based benchmarks may in some cases be required for local or international management. For example, for Nass and Skeena Sockeye aggregate escapement goals are required under the Pacific Salmon Treaty [@TreatyGovernmentCanada2019], though to comply with the WSP, the status of component CUs should also be considered. 

However, when LRPs are defined within the context of a Management Procedure framework (see Section \@ref(intro)), then an aggregate abundance-based LRP may not be required if the framework can demonstrate the probability of individual CUs having status above red for various management options. For Pacific salmon, management procedures extend beyond harvest control rules to include time-area closures, habitat enhancement or hatchery supplementation to protect individual CUs. Therefore, the choice to develop an aggregate abundance-based LRP depends on the decision context, and should be made in collaboration with various sectors responsible for management decisions within the SMU. If aggregate abundance-based LRPs are not required, assessment of the SMU would be provided from steps 1-6. The following steps (8-12) are relevant if aggregate abundance-based LRPs are required, and build on proportion-based LRPs derived in the previous steps. Risks associated with uncertainties introduced by the inclusion of models to relate aggregate abundances to CU-level statuses should be considered when choosing LRP methods (Principle 5 in Section \@ref(principles)). 


In the context described here, aggregate abundance-based LRPs are scientifically derived quantities that delineate serious harm to an SMU following the principles outlined in Section \@ref(principles). Although these LRPs can inform harvest control rules, harvest management decisions require consideration of multiple objectives beyond those associated with conservation and serious harm (e.g., socioeconomic objectives). 


### What is Acceptable Probability of Achieving Proportion-Based LRP? (Step 8)


Aggregate abundance-based LRPs are defined to be consistent with the WSP objective of maintaining biodiversity at the scale of CUs. First, an acceptable probability of achieving the proportion-based LRP (i.e., all CUs above red status) is identified. We recommend applying a probability of at least 50% of all CUs being above red status to align with WSP objectives. We provide LRPs associated with four probabilities, 50%, 66%, 90%, and 99% derived from categories of likelihoods used by the International Panel on Climate Change [@mastrandreaGuidanceNoteLead2010], instead of specifying a single probability because we could not identify a scientific basis for the choice (see Section \@ref(logisticMethods)). 


\renewcommand*{\arraystretch}{1.6}
\begin{longtable}[]{p{3.7cm} p{6.3cm}}
\caption{Likelihood definitions adapted from the Intergovernmental Panel on Climate Change.}\\
\hline
Probability & Definition \\ 
\hline
\endhead
$>$ 50\%  &  more likely than not that all CUs are above their lower benchmark\\
$>$ 66\%  &  likely that all CUs are above their lower benchmark\\
$>$ 90\%  &  very likely that all CUs are above their lower benchmark\\
$>$ 99\%  &  virtually certain that all CUs are above their lower benchmark\\
\hline
(\#tab:LikelihoodsIPCC)
\end{longtable}



Future applications of this Step 8 when setting LRPs may want to consider the relevance of probability thresholds for triggering LRPs described in DFO's Guidelines for the Implementation of Rebuilding Plans [@dfoScienceGuidelinesSupport2021].  These guidelines specify that, "unless otherwise defined in stock-specific precautionary approach frameworks, the LRP should be considered breached if the terminal year stock status indicator is estimated to be at or below the LRP with a greater than 50% probability or if the projected stock status indicator falls below the LRP with a greater than 50% probability under a zero catch scenario in a 1 year projection". While using a 50$% probability threshold of one or more CUs having red status is not directly analogous, in both cases the probability threshold chosen represents the probability of the stock avoiding serious harm. In our case studies, we provide logistic regression-based LRPs for the four probability thresholds described above, and focus sensitivity analyses on a 50% probability of all component CUs having status above red. This approach to delineating serious harm could be considered risk neutral, where risks may be accounted for directly and explicitly in harvest control rules that trade-off multiple objectives.    





### Choose among aggregate abundance-based LRPs (Step 9)

Guidelines for choosing among two types of aggregate abundance-based LRPs are described here: empirical logistic regression-based LRPs and projection-based LRPs that use historical data or projected data, respectively to identify the relationship between aggregate abundances and the probability that all CUs are above red status. These guidelines are based on assumptions required for each method. If assumptions are not met for either method presented below, then developing aggregate abundance-based LRPs that are aligned with the WSP may not be possible for this SMU. However, developing and evaluating management procedures that account for CU-level status is still prudent even in the absence of aggregate abundance-based LRPs (Section \@ref(recommendations)).

Both methods exploit covariation in population dynamics among component CUs, such that when one CU has depleted status and contributes relatively few spawners, it is likely that others CUs also have depleted status contributing few spawners to the aggregate abundance. In contrast, when one CU is considered healthy and contributes many spawners, it is more likely that other CUs are the same when they covary. 

Given, uncertainties and limitations associated with each method, application and comparison of both methods may be prudent instead of choosing a single approach (as described in Step 11)

#### Empirical logistic regression-based LRPs

Empirical logistic regression-based LRPs are derived from historical time-series of the proportion of CUs above red status, indicated by a single metric metric on spawner abundances or distribution.  


LRPs based on logistic regressions may be appropriate when the following assumptions are met:

- CU assessments are derived primarily from abundances relative to benchmarks or distribution of spawners instead of time trends. It is possible to combine two or more types of abundance-based benchmarks to assess CUs within an SMU (e.g., use both percentile and S~gen~ benchmarks to assess different CUs).

- As required for proportional-based benchmarks, data-deficient CUs meet criteria outlined in Step 3 such that their status can be represented by CUs with data. 

- Time-series of the proportion of CUs above the lower benchmark contain contrast such that all CUs are above their lower benchmark in at least one year and at least 1 CU is below its lower benchmark in at least one year. <!--CW: I suspect we would not get the model to converge if there was only one year with one of the outcomes, could we change it to a few:
 Time-series of the proportion of CUs above the lower benchmark contain contrast such that all CUs are above their lower benchmark in a few years and at least 1 CU is below its lower benchmark in a few years.
 
CH: you're probably right, but I'm unsure how much afew is, and wonder if some (possibly rare) case having one year might work..?
-   -->

- There is a significant positive relationship between aggregate abundances and log-odds of all component CUs being above their lower benchmark without influential outliers, as supported by model diagnostics described in Holt et al. (in review). This relationship tends to be strong and positive when pairwise correlations in spawner abundances are strong and positive among CUs. For example, for Interior Fraser Coho, goodness-of-fit diagnostics identified a significant relationship between aggregate abundances and log-odds of all component CUs being above their lower benchmarks (p<0.01) and the average pairwise spawner correlations among CUs was relatively high, 0.56. In contrast, for Inside South Coast Chum, the same goodness-of-fit diagnostic was not statistically significant (p=0.13) and average pairwise spawner correlations was relatively weak, 0.12.  <!--CH or Kendra: Check exact cor and p-values for IFR coho.--> <!--KH: I have updated to 0.56, which is the average among-CU pairwise correlation for natural-origin spawners. (Note - the value is very similar for total spawners) -->

- Residuals for logistic regression model fit are independent (i.e., not temporally autocorrelated). <!--CH: "Or if autocorrelation is present in residuals, it is accounted for in the model with an AR(1) term."  Don't think we need it though  KH: agree - not needed.-->

- Environmental drivers and threats among CUs have remained stable over the available time-series, or have changed in the same way across CUs such that covariance in population dynamics among CUs is likely to have remained stable over time. As a result, the relationship between aggregate abundances and log-odds of all CUs being above lower benchmarks is also likely to have remained stable. 

- CU-level population dynamics are not undergoing directional changes resulting in declines or increases in population dynamic parameters and benchmarks


In preliminary analyses for the Interior Fraser Coho case study, we considered CU status based on multidimensional status from the Pacific Salmon Status Scanner, but have chosen to focus on the single metric approach for several reasons. First, the Salmon Scanner includes status on smoothed abundance data (running generational geometric mean) relative to abundance-based benchmarks, and therefore the status in one year depends on the status in the previous year. Autocorrelation violates the assumption of independence of observations required in the logistic regression. Although logistic regressions can be revised to account for autocorrelated residuals, the available degrees of freedom are often insufficient given the relatively short time-series of CUs <!--CU?-->assessments. <!--CH remove: "and changes in environmental conditions which sometimes precludes including older data."--> <!--CH: also sometimes skew in data points towards most years with all CUs above lower benchmarks which limits power of LR--> In addition, the Salmon Scanner includes metrics on short- and long-term trends in spawner abundances which are less directly related to, and may be completely unrelated to, aggregate abundances. For CUs that rely on time trends for status assessments, aggregate abundance-based metrics are likely not appropriate (see below). <!--CH remove: "However, future analyses could explore the possibility of including CU statuses derived from the Salmon Scanner that rely primarily on abundance-based benchmarks with alternative logistic regression model forms that include autocorrelation.-->


LRPs based on logistic regressions may not be appropriate when:

- CU assessments are derived from trends in spawner abundances over time (e.g., as part of the Pacific Salmon Status Scanner), and not abundance-based benchmarks.

- Data-deficient CUs do not meet criteria outlined in Step 3 such that their status cannot be represented by CUs with data.

- Time-series of the proportion of CUs above the lower benchmark are equal to 100% for all years, or less than 100% for all years.

- The relationship between aggregate abundances and log-odds of all component CUs being above their lower benchmark is not statistically significant or contains influential outliers. In other words, model diagnostics do not support the use of logistic regression. The relationship between aggregate abundances and log-odds of all component CUs being above their lower benchmark tends to be insignificant when pairwise correlations in spawner abundances are weak or negative among CUs.

- Residuals for logistic regression model fit are temporally autocorrelated such that status in one year depends on the status in the previous year.

- Threats and/or environmental drivers have changed such that CU-level benchmarks estimated from historical data are no longer meaningful, and there is no expectation that these changes will be reverted naturally of achieved through management. Or, environmental drivers and threats among CUs have changed over the available time-series such that *covariance in population dynamics among CUs* is likely to have changed. 


- There is only 1 CU in the SMU. In this case, the CU-level status equates to the SMU-level status.

<!--CH Tentative exclusion b/c may be implied by stepwise order, but happy to add back in:
- Current CU-level assessments are not available. Aggregate-abundance LRPs are intended to supplement proportion-based LRPs and not replace them. In this case, there may be risk of loss of CU-level biodiversity due to infrequent extreme events not captured in the model.

CW: Agree with the exclusion, otherwise we would also have to point out that aggregate abundance methods may not be appropriate when one or more CU's are missing data. -->


#### Projection based LRPs

Projection-based LRPs are derived from projections of CU-level population dynamics and associated time-series of CUs above red status as indicated by a single metric, spawner abundances relative to a lower benchmark. We did not consider CU-status derived from the Pacific Salmon Status Scanner for projection-based LRPs because the projection model identifies long-term equilibrium aggregate abundances associated with specified probabilities of component CUs being above lower benchmarks and is not structured to reflect time trends. Time trends can be assessed in simulation models that evaluate the impacts of management procedures on population dynamics from current status, as in MSEs.<!-- CH: we should mention in the other paper that projection-based LRP is an equilibrium approach-->


Projection-based LRPs may be appropriate when:

- CU-specific stock assessment models have been developed including parameterization of spawner-recruitment models, covariance in recruitment residuals among CUs, and ages-at-maturity. These models are peer reviewed and they represent current population dynamics.
<!--KH: The above suggests that a peer-review of SR models is required, however, the next bullet goes in to say that it is not. Perhaps just remove the mention of peer-review in the first bullet? In general, any application of projection-based LRPs will need to go through peer-review, so having previoulsy peer-reviewed models is not needed  -->
- Where peer-reviewed model parameters are not available or are no longer current, plausible bounds can be placed on uncertain parameters (e.g., productivity and capacity), including those that may have changed over the time-series to represent a best-estimate of current conditions. 

- These CU-specific parameters are available for representative CUs within the SMU (as identified in step 3)

- Projection-based LRPs may be more appropriate when pairwise correlations in spawner abundances among CUs are positive and strong, but this is not a requirement. It is possible to estimate projection-based LRPs for an SMU with component CUs that vary independently. However, when correlations between CUs are low, the aggregate abundance-based LRP will be high to support weak CUs. In these cases, proportion-based LRPs, and harvest control rules that manage CUs independently may be more appropriate.


<!--CH: extra text I don't think is needed (but this point can be highlighted in Case Study paper): 
For example, if there is a high probability that any one CU will be below the lower benchmark in a given year due to asynchronous dynamics, there is also a high probability that aggregate abundances are below the aggregate abundance-based LRP.  In contrast, when correlations in population dynamics and status assessments are relatively high among CUs, aggregate abundance-based LRPs tend to be lower. -->



Projection-based LRPs may be inappropriate when:

- Population dynamics parameters cannot be estimated, and/or plausible ranges are not known.

- As described above, when pairwise correlations in spawner abundances among CUs are weakly positive or negative projection-based LRPs will be relatively high to support weak CUs, 

- Projection-based LRPs are used to evaluate status under a new management procedure that is not considered in the projection model. Projection-based LRPs depend on the specific management procedure applied in the projections, implemented as a constant exploitation strategy for our case studies. However, sensitivity analyses of projection-based LRPs to various exploitation rates or management procedures can demonstrate aggregate abundances required to maintain CUs above their lower benchmarks under a variety of possible management scenarios, and the sensitivity of management choice to the aggregate abundance-based LRP.

- There is only 1 CU in the SMU. In this case, the CU-level status equates to the SMU-level status.

<!--CH: this bullet was tentatively removed from logistic regression-based LRP, so removing here:

- Current CU-level assessments are not available. Aggregate-abundance LRPs are intended to supplement proportion-based LRPs and not replace them. There may be risk of loss of CU-level biodiversity when relying on projection-based LRPs alone due to unforeseen processes (e.g., infrequent extreme events) not captured in the projection model that are reflected in current CU statuses. 
-->


### Apply aggregate abundance-based LRPs (Step 10)

Any aggregate-abundance methods that meet the above criteria are applied. See the companion working paper, Holt et al. (in review) for details of applications of these methods. Summaries are provided in Section \@ref(case-studies). When status of an SMU is inferred from aggregate abundance-based LRPs using a subset of CUs that are considered representative of the remaining data-deficient CUs, then the resulting status should be considered 'interim' until all component CUs can be assessed. When status of data-deficient CUs cannot be inferred from data-rich CUs, status can not be assessed with aggregate abundance-based LRPs.

### Compare aggregate abundance-based LRPs (Step 11)

Principle 6 for the development of LRPs states that alternative paradigms for developing LRPs should be evaluated (Section \@ref(principles)). If multiple aggregate abundance-based methods are applied and statuses differ depending on the method chosen, we suggest (re)considering if all assumptions are met. Statuses that converge among methods provide more strength that LRPs represent a level above serious harm.  Although LRPs that converge may be based on assumptions that are coincidentally incorrect, the principle of Occam's razor supports explanations with fewer exceptions. When LRPs diverge, the underlying assumptions causing those divergences should be explored and further reviewed. We suggest comparing aggregate abundance-based LRPs to current generational (geometric) average spawner abundances instead of annual abundances to integrate across independent cohorts within a generation when deriving SMU status. This approach is consistent with WSP assessments [e.g., @grant2017FraserSockeye2020]. 

### Compare status from aggregate abundance-based LRPs to that from Prorportion-based LRPs (Step 12)

In this step, we recommend comparing status from aggregate abundance-based LRPs to that from proportion-based LRPs identified in step 5. While aggregate abundance-based LRPs exploit observed covariation in dynamics among CUs, observation errors, temporal variation in covariation, and/or infrequent extreme events may result in a break-down in that covariation, and hence statuses from abundance-based LRPs that differ from those based on proportion-base LRPs. We recommend proportion-based LRPs as the default LRP to implement Fish Stock provisions, with aggregate abundance-based LRPs supplemental where required for harvest management. 

<!-- CW: Can we say how often these comparisons should happen? 
Is it realistic to suggest that comparisons will be done every year? Or would these comparisons be done every X years?
CH: We had recommended generationally (~4yrs) for WSP assessments, but this is really a resource-availability vs management-need question that is specific to species and stock.
 -->


<!-- CW: Could the sections below be moved to another chapter? I think it would be good to have the steps as their own chapter to reflect their importance
Maybe "Time-varying parameters and impacts on LRPs"  could go under chapter 5 (after editing to be more recommendation based?)
and " Consistency with National Guidance on LRPs" can go under Chapter 2?
I moved the sections to the chapters listed above.
 -->




