---
title: "Case Study Applications of LRP Estimation Methods to Pacific Salmon Stock Management Units"
author: |
  Kendra Holt^1^
  Carrie A. Holt^2^
  Luke Warkentin^3^
  Catarina Wor^2^
  Brooke Davis^3^
  Michael Arbeider^4^
  Jessy Bokvist^5^
  Sabrina Crowley^6^
  Sue Grant^7^
  Wilf Luedke^5^
  Diana McHugh^5^
  Candace Picco^8^
  Pieter Van Will^5^

author_list: "Holt, K.R., Holt, C.A., Warkentin, L., Wor, C., Davis, B., Arbeider, M., Bokvist, J., Crowley, S., Grant, S., Luedke, W., McHugh, D., Picco, C., and Van Will, P."
address: |
  ^1^Fisheries and Oceans Canada\
     Institute of Ocean Sciences\
     9860 W Saanich Rd\
     Sidney, BC, V8L 5T5\
  ^2^Fisheries and Oceans Canada\
     Pacific Biological Station\
     3190 Hammond Bay Rd.\
     Nanaimo, BC, V9T 6N7\
  ^3^Fisheries and Oceans Canada\
     Annacis Office\
     100 Annacis Pkwy Unit 3\
     Delta, BC, V3M 6A2\
  ^4^Fisheries and Oceans Canada\
     BC Interior Area Office\ 
     986 McGill Place\
     Kamloops, BC V2C 6X6\
  ^5^Fisheries and Oceans Canada\
     Southcoast Area Office\
     3225 Stephenson Point Rd\
     Nanaimo, BC, V9T 1K3\
  ^6^Nuu-chah-nulth Tribal Council\
     5001 Mission Rd\
     Port Alberni, BC, V9Y 8X9\
  ^7^Fisheries and Oceans Canada\
     Regional Headquarters, Pacific\
     200-401 Burrard Street\
     Vancouver, BC, V6C 3S4\
  ^8^Ha'oom Fisheries Society\
     320 Opitsaht IR Road\
     Tofino, BC, V0R 2Z0\
month: Month # fill in
year: 2022
report_number: nnn
region: Pacific Region
citation_other_language: "Holt, K.R., Holt, C.A., Warkentin, L., Wor, C., Davis, B., Arbeider, M., Bokvist, J., Crowley, S., Grant, S., Luedke, W., McHugh, D., Picco, C., et Van Will, P.. Title Here (*Latin Species Name*). DFO Secr. can. de consult. sci. du MPO. Doc. de rech 2022/nnn. iv + 13 p."
abstract: |
  The revised fisheries act required that Limit Reference Points (LRPs) be identified for all major fish stocks. For Pacific salmon, major fish stocks are represented by stock management units (SMUs), which are composed of one or more salmon conservation units (CUs), which are the assessment units under the Wild Salmon Policy. We introduce LRP estimation methods based on aggregating status assessments from the CU level to the SMU level. We demonstrate and evaluate the LRPs for three case study SMUs: Interior Fraser Coho, West Coast Vancouver Island (WCVI) Chinook, and Inner South Coast Chum - excluding Fraser. Methods are divided into two categories: Proportion-based LRPs and Aggregate abundance-based LRPs, which is further sub divided into Logistic regression-based LRPs and Projection-based LRPs. The suitability of each method depends on the availability and quality of data for each SMU, as well as on the historic CU statuses. Proportion-based LRPs are recommended as the default method, while aggregate abundance-based methods are complementary and may be needed to meet management requirements. Proportion-based LRPs are based on individual CU status assessments. Aggregate abundance Logistic regression-based LRPs are based on past status assessments and are estimable when abundance-based CU status is available, and the SMU has observations when the LRP has been breached (at least one CU under red status) and not breached (all CUs above red status). Aggregate abundance Projection-based LRPs are based on future projections and do not require contrast in previous status observations. However, projections require estimates for population dynamics parameters, as well as estimates of covariation among CUs. We discuss suitability and requirements for the applications of the LRP estimation methods drawing from the range of data and information availability in the study cases.  

header: "Draft working paper --- Do not cite or circulate" # or "" to omit
output:
 csasdown::resdoc_pdf:
   french: false
   copy_sty: true
   line_nums: true
   line_nums_mod: 1

# ------------
# End of options to set
knit: bookdown::render_book
link-citations: true
bibliography: bib/refs.bib
# Any extra LaTeX code for the header:
header-includes:
  - \usepackage{amsmath}
  - \usepackage{graphics}
  - \usepackage{tcolorbox}
# - \usepackage{tikz}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if(length(grep("pdf", names(meta)))){
  french <- meta$`csasdown::resdoc_pdf`$french
  prepub <- meta$`csasdown::resdoc_pdf`$prepub
}else if(length(grep("word", names(meta)))){
  french <- meta$`csasdown::resdoc_word`$french
  prepub <- meta$`csasdown::resdoc_word`$prepub
}
csl <- "csl/csas.csl"
if(french){
  csl <- "csl/csas-french.csl"
  options(OutDec =  ",")
}

# add other packages here:
library(dplyr)
library(readr)
library(tibble)
library(csasdown)
library(kableExtra)
library(ggplot2)
library(viridis)
library(tidyr)

```

---
csl: `r csl`    
---
